### ISSUE TITLE
Navigation changes between children and active pages

### ISSUE THREAD

**Issue by brendo** [mkdocs/mkdocs#1375] opened 2018-01-09 02:41 UTC
This is a new behaviour that have only noticed when using MkDocs 0.17.2.

I created a sample site to showcase the bug @ http://bloodbone.ws/mkdocs-test/.

When the navigation is created, the title of pages is derived from the filename. When the user actually lands on a page though, it appears the title of the page is derived [slightly differently](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/nav.py#L215-L220), and the first Markdown H1 is used instead.

In the [sample site](https://github.com/brendo/mkdocs-test/tree/master) I have two pages:

- index.md contains a h1 of `Home`
- README.md, contains a h1 of `Random README title`.

When a user first lands on the site, the two navigation items read as `Home` and `README`.

When a user clicks on `README`, the navigation items now read as `Home` and `Random README title`.

I would expect that navigation items be consistent and not change.

Repo @ https://github.com/brendo/mkdocs-test

**Comment by brendo** [comment] 2018-01-09 02:56
Ah apologies I think this is a dupe of #1347

**Comment by waylan** [comment] 2018-01-09 03:05
Yes, this is a duplicate of #1347.

**Closed by waylan** 2018-01-09 03:05 UTC
