### ISSUE TITLE
Enable GitHub Discussions for this Repository

### ISSUE THREAD

**Issue by Andre601** [mkdocs/mkdocs#2256] opened 2020-12-20 17:56 UTC
GitHub made their Discussions open Beta and I strongly believe that this repository could benefit from having this.

Why?
People like me feel kinda uncomfortable to use issues for asking basic questions regarding the software/tool in general and often don't like to use sites/services like IRC or similar.
Having a discussion here would help us to more easily ask questions since it now would have a dedicated place for it and as an added bonus could be used as a nice collection of answers to questions someone might have.

**Comment by facelessuser** [comment] 2020-12-20 18:35
I know there is a mailing list on Google groups, but Discussions here might be nice.

**Comment by waylan** [comment] 2020-12-21 14:31
As @facelessuser mentioned, there is a [Google Group][1], which serves this purpose and is linked to from our [Readme][2]. I don't see any sense in maintaining two separate discussion forums. Therefore, I will assume this is a request to move the discussion forum from Google Groups to GitHub Discussions. Is there any benefit to changing forums? I've never used GitHub discussions myself so I don't have any way to judge this.

[1]: https://groups.google.com/g/mkdocs
[2]: https://github.com/mkdocs/mkdocs#mkdocs

**Comment by facelessuser** [comment] 2020-12-21 14:50
I think it's, honestly, just a matter of personal preference. It does give you one place to manage everything for a project. You have issues pull requests, and general questions all managed in one place. User's don't have to have multiple accounts, they can just get all the support they need at the repo site.

Its really up to you as they serve the same purpose. There purposely small differences as I think you can make a thread as answered etc. In discussions. There is probably cross linking of issues to discussions etc.

**Comment by Andre601** [comment] 2020-12-21 14:52
> As @facelessuser mentioned, there is a [Google Group][1], which serves this purpose and is linked to from our [Readme][2]. I don't see any sense in maintaining two separate discussion forums. Therefore, I will assume this is a request to move the discussion forum from Google Groups to GitHub Discussions. Is there any benefit to changing forums? I've never used GitHub discussions myself so I don't have any way to judge this.
> 
> [1]: https://groups.google.com/g/mkdocs
> [2]: https://github.com/mkdocs/mkdocs#mkdocs

Not everyone wants to use google groups as it by default litters your inbox with every response made and not just those you're actually participating in.
Additionally is GitHub discussions similar in style to StackOverflow, meaning it can be a good place to collect answers to common questions.
Finally don't you need a separate account to use it. If you have a GitHub account can you make issues, prs or ask in discussions.
For Google Groups do you require a separate google account.

While the argument of having a second place to care for is valid would it imo be a fairly minor one as it would at most require mod actions for inapropriate posts which I think is a minority here.

**Comment by Andre601** [comment] 2020-12-21 14:56
> Its really up to you as they serve the same purpose. There are probably small differences as I think you can mark a thread as answered etc. There is probably cross linking of issues to discussions etc.

Yes. The categories can be set to open questions, so that responses can be marked as answers similar to StackOverflow.

**Comment by waylan** [comment] 2020-12-21 15:43
> Not everyone wants to use google groups as it by default litters your inbox with every response made and not just those you're actually participating in.

Its ironic that you mention this first as I have all notifications turned off for the group (because I don't want it littering my inbox). The only way I see anything posted there is to go visit the page manually. As it turns out, I hadn't looked at the page in the last 8 months.

> There is probably cross linking of issues to discussions etc.

I would assume so as it's all on the same platform. However, is there a way to migrate a posting from one to the other. For example, can I click a button and get: "This is not a bug report or feature request and it has been moved to discussions." Or do we need to close it and manually repost? If therein no migrate feature, then what's the point?

My point is that if we are going to have a clear distinction between discussions and issues, then we need to enforce that distinction. However, if it is not easy to enforce, then enforcement won't happen. And if enforcement doesn't happen, then there is no point in having two separate forums; we might as well just keep everything in 'issues.'

**Comment by facelessuser** [comment] 2020-12-21 15:51
You can migrate issues to discussions.

**Comment by Andre601** [comment] 2020-12-21 15:59
> I would assume so as it's all on the same platform. However, is there a way to migrate a posting from one to the other. For example, can I click a button and get: "This is not a bug report or feature request and it has been moved to discussions." Or do we need to close it and manually repost? If therein no migrate feature, then what's the point?

It's a planned feature. Discussions are still in open beta, so they're not final yet.

> My point is that if we are going to have a clear distinction between discussions and issues, then we need to enforce that distinction. However, if it is not easy to enforce, then enforcement won't happen. And if enforcement doesn't happen, then there is no point in having two separate forums; we might as well just keep everything in 'issues.'

I can see your point, but enforcement would be hard.
Even with a migration tool would people still open issues for common questions forcing you to move it to discussions.
The best and on the other hand worst option would be to close issues not matching bugs or feature requests and ask them to move it to discussion.
This however could be automated with the help of GitHub Actions like label-commenter-action to send canned responses and/or close issues based on labels assigned.

**Comment by Andre601** [comment] 2020-12-21 16:01
> You can migrate issues to discussions.

Really? I recall this to still be planned. Perhaps it was released just recently?

**Comment by facelessuser** [comment] 2020-12-21 16:06
> It's a planned feature. Discussions are still in open beta, so they're not final yet. 

This is already available. I see a convert to discussion link on existing issues.

> Really? I recall this to still be planned. Perhaps it was released just recently?

You can see the link here. I haven't used it yet, but it seems to imply migration:

<img width="131" alt="firefox_7GR9XTkdVw" src="https://user-images.githubusercontent.com/1055125/102796526-a7295e80-436b-11eb-92bc-f3e1f0b9a88f.png">

Also, if you don't want notifications from discussions, I believe you can change your "watch" options to ignore discussion events.

**Comment by waylan** [comment] 2020-12-21 16:31
> This is already available. I see a convert to discussion link on existing issues.

Cool!

If we do this, we need to update any mention of the Google Group in the Readme and docs. We also should probably make an announcement on the Group and close the group. However, I'm not the group owner, @tomchristie is.

**Comment by facelessuser** [comment] 2020-12-21 16:35
I've just started playing with it, so I'm still waiting to see how well it works in all these areas, but it may be worth considering.

**Comment by Andre601** [comment] 2020-12-21 16:43
> > This is already available. I see a convert to discussion link on existing issues.
> 
> Cool!
> 
> If we do this, we need to update any mention of the Google Group in the Readme and docs. We also should probably make an announcement on the Group and close the group. However, I'm not the group owner, @tomchristie is.

I can later prepare a pr for the readme, so that you have less work to do 😉

**Comment by squidfunk** [comment] 2021-01-12 21:22
> Also, if you don't want notifications from discussions, I believe you can change your "watch" options to ignore discussion events.

This. I just look in there from time to time and users seem to love the new discussions feature. Some already shared some solutions/recipes.

**Comment by facelessuser** [comment] 2021-01-12 21:24
The one unfortunate thing is GitHub removed the ability to convert issues to discussions. This greatly confuses me and actually makes it less useful. I am hoping they add it back.

**Comment by waylan** [comment] 2021-01-12 21:25
> The one unfortunate thing is GitHub removed the ability to convert issues to discussions. This greatly confuses me and actually makes it less useful. I am hoping they add it back.

Until they do, I'm not interested. But even if they do, what's to stop them from changing it again?

**Comment by facelessuser** [comment] 2021-01-12 21:30
> Until they do, I'm not interested. But even if they do, what's to stop them from changing it again?

🤷‍♂️ I mean you could say that about anything with GitHub, but I assume it was probably because they weren't ready to release that feature, and then backed it out for now.

I mainly mention it because that was something you expressed interest in, which I happened to have noticed was there at the time. But it was also mentioned that:

> Really? I recall this to still be planned. Perhaps it was released just recently?

So I imagine it was only present by accident.

**Comment by waylan** [comment] 2021-01-12 21:36
My concern is that we already have a discussion forum in Google Groups. The only benefit moving to GitHub gives us is that we can transfer conversations between issues (bug reports) and discussions. But if that feature isn't offered, then there is no reason to make the switch.

By the way, I realize that some people will cite a second reason to abandon Google Groups: it requires a user account on two systems. While I understand the sentiment, who doesn't have a Google account? Regardless, that in itself isn't enough for me.

**Comment by Andre601** [comment] 2021-01-12 21:47
> My concern is that we already have a discussion forum in Google Groups. The only benefit moving to GitHub gives us is that we can transfer conversations between issues (bug reports) and discussions. But if that feature isn't offered, then there is no reason to make the switch.

The other reason that probably many agree on is, that you won't need a separate account for the forums as most people using MkDocs probably also have a GitHub Account, while this might not be guaranteed for the forums (And you would be surprised about how many people don't have a google account).
Next does the forums do that *absolutely lovely* thing where you get notified about every post made there and not just those you actually participated in...
Finally do the forums look like a repurposed version of GMail. Condensed, showing e-mails instead of actual names to name two things.
No categorization, no option to pin a post (I assume?) to inform about specific stuff, search also seems somewhat odd, you can't differenciate between if a support request is "solved" or still open (Hard to find solutions that way).

I assume another reason is, that you would have more moderation to do? I'm pretty sure there would be quite a few members of the community that would help you with that when needed.

**Comment by Andre601** [comment] 2021-02-15 21:30
It seems like you can now again transfer issues over to discussions 🙌

**Comment by facelessuser** [comment] 2021-02-16 14:49
Yup, I was happy to see these return

**Comment by jmdye** [comment] 2021-02-17 20:55
> By the way, I realize that some people will cite a second reason to abandon Google Groups: it requires a user account on two systems. While I understand the sentiment, who doesn't have a Google account? Regardless, that in itself isn't enough for me.

True story - I'd not used my Google account in ages and only started using it again for the purpose of making posts in the Google Groups for this project. I don't really use it for much else.

**Comment by fu-sen** [comment] 2021-03-24 10:36
I use Gmail and so on, but I recognize Google Groups as a very old project.

For example, a project using GitHub decussion:
https://github.com/vercel/vercel/discussions

They have switched several forums in the past and settled on this forum.

**Comment by fu-sen** [comment] 2021-03-24 10:47
I saw the existence of Google Group in the [README](https://github.com/mkdocs/mkdocs/blob/master/README.md).
It's also on the top page of [www.mkdocs.org](https://www.mkdocs.org/#getting-help]), but it's at the bottom of the page. This is hard to find.
That's probably one of the reasons why this issue is flooded with rudimentary questions and can't be dealt with.

Having a community on GitHub may help make an issue a place to get real problem reports.

**Comment by squidfunk** [comment] 2021-03-24 11:18
BTW, GitHub added back the ability to convert issues to discussions:

<img width="301" alt="Bildschirmfoto 2021-03-24 um 12 17 01" src="https://user-images.githubusercontent.com/932156/112302013-dae19080-8c9a-11eb-91b5-1e19f16e1f11.png">

**Comment by Andre601** [comment] 2021-03-24 11:20
> BTW, GitHub added back the ability to convert issues to discussions:
> 
> <img width="301" alt="Bildschirmfoto 2021-03-24 um 12 17 01" src="https://user-images.githubusercontent.com/932156/112302013-dae19080-8c9a-11eb-91b5-1e19f16e1f11.png">

I mentioned this already.

**Comment by fu-sen** [comment] 2021-03-24 11:55
Yes, The fact that it is repeated may be the reason why some users are asking for it.
I haven't joined the Google Group yet, and probably won't. I'm putting a comment here instead. Is it you too?

**Comment by squidfunk** [comment] 2021-03-24 13:04
> I mentioned this already.

Sorry, I thought I read all comments but seem to have overlooked yours 😅

**Comment by waylan** [comment] 2021-03-24 18:50
@tomchristie @d0ugal do either of you have any objections to migrating from the Google Group to GitHub Discussions? I don't see any good reason to keep the Google Group open and have GitHub Discussions enabled. I recommend that the administrator for the group close it after making an announcement that all discussions should be taken to GitHub.

**Comment by d0ugal** [comment] 2021-03-24 19:10
Yup, go for it! I think @tomchristie is the group admin but I’m not sure. I’ll try and figure out if I have access.

**Comment by waylan** [comment] 2021-03-24 19:24
GitHub Discussions has been enabled for this project. When the Google Group is closed, we can close this issue.

**Comment by Andre601** [comment] 2021-03-24 20:52
Just for those who didn't notice, I created a PR to update the links from the forums to discussions.

Something I would like to quickly discuss here: Wouldn't it be an idea to move some things from the Wiki in this repository into a dedicated category on the discussions?

For example the deployments page could be in a category "Deployment guides" or similar. Or perhaps move the themes to a "Themes" category?

I just think that the wiki is a bit messy right now and could deserve a bit love...

**Comment by waylan** [comment] 2021-03-24 23:45
I've been pretty hands-off with the wiki. However, if you want to do some cleanup, feel free. Let's hold off on moving any of that content to Discussions for now. Perhaps we can reconsider when we have more experience with the new system.

**Comment by fu-sen** [comment] 2021-03-25 01:27
> For example the deployments page could be in a category "Deployment guides" or similar. Or perhaps move the themes to a "Themes" category?

The theme will need to be considered separately. All we need is:
- https://themes.gohugo.io/
- http://jekyllthemes.org/

The current MkDocs theme is ignored by some users because some themes are not visible.

**Comment by fu-sen** [comment] 2021-03-25 07:10
I expected the first post of someone here, but it became my post.
It didn't have a corresponding place on the Wiki.

**Closed** 2021-03-25 17:39 UTC
Labels: Needs design decision, Process
