### ISSUE TITLE
[FR] auto-restart live reload server after config errors are fixed

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [mkdocs/mkdocs#3290] opened 2023-07-14 08:38 UTC
currently the server simply exits when the config is changed and saved with a error

instead the build should either rerun the with the last working file content of the config or only skip the build waiting for a file fix

my current workaround is to simply have a shell loop with a half second sleep around the live reload server
i'd much prefer if the server could simply wait out the file change from broken config to working config

**Comment by oprypin** [comment] 2023-07-14 08:47
Duplicate of #3166, already solved

**Closed by oprypin** 2023-07-14 08:47 UTC

**Comment by RonnyPfannschmidt** [comment] 2023-07-14 09:17
The server currently crashes with broken config Changes,

**Comment by oprypin** [comment] 2023-07-14 09:18
needs a release. expect in ~days.

**Comment by RonnyPfannschmidt** [comment] 2023-07-14 09:23
thanks for the clarification  also just noted i misunderstood the scope of the fix at first (content changes vs config changes
