### ISSUE TITLE
How can I remove the side bar?

### ISSUE THREAD

**Issue by notalentgeek** [mkdocs/mkdocs#1069] opened 2016-10-07 16:33 UTC
I have already tons of MarkDowns as my notes. However, I rarely use the heading.
As I have no heading, the side bar has no use for me. How can I remove this completely?

**Comment by waylan** [comment] 2016-10-07 17:10
I closing this as a duplicate of #454, #700 and possibly #951. See [this comment][1] for the way I would accomplish this.

[1]: https://github.com/mkdocs/mkdocs/issues/951#issuecomment-222392977

**Closed by waylan** 2016-10-07 17:10 UTC

**Comment by notalentgeek** [comment] 2016-10-07 19:44
`div.bs-sidebar.hidden-print.affix.well{ display: none; }` this does the job. Is it fine?

**Comment by notalentgeek** [comment] 2016-10-07 19:47
I need to erase the `col-md-3` and change `col-md-9` into `col-md-12` any idea how to this?

**Comment by notalentgeek** [comment] 2016-10-07 19:59
```markdown
$("div.col-md-3").remove();
$("div.col-md-9").attr("class", "class-md-12");
```

**Comment by waylan** [comment] 2016-10-07 22:41
FYI, I just added a [recipe][1] for this to the wiki. These seems to be a highly requested feature so we might as well document how to do it. __Note__, however, that the method documented there only works with version 0.16 or later (the current release is 0.15). Sorry, its not so easy <0.16.

[1]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Recipes#remove-the-table-of-contents-sidebar-from-the-mkdocs-theme

**Comment by notalentgeek** [comment] 2016-10-08 09:29
No problem mate. Cheers!

**Comment by nodesocket** [comment] 2017-10-06 03:41
👍 on an option to hide the table of contents _(TOC)_.
