### ISSUE TITLE
Allow building all files in a directory

### ISSUE THREAD

**Issue by aishmitk** [mkdocs/mkdocs#1136] opened 2017-02-09 21:38 UTC
We have a directory with a very large number of files which are constantly being added to by contributors that are not necessarily so tech savvy. We currently have an explicit list of pages with titles, so we cannot remove the pages section and allow mkdocs to auto discovered. 

We have a few suggestions to solve this, would you be willing to merge any of these back in?

1. A `glob pattern`:

        mdFiles: docs/*/*.md

2. Have the entry point to a script in perhaps python which is run to generate the list

3. Change the build pattern so that when a change is detected, a hook is run and then the instance is built

**Comment by waylan** [comment] 2017-02-10 00:40
I was sure this was a duplicate of a previous request, but I can't seem to find it. Regardless, I would expect this sort of thing would be addressed by a plugin (see #206).

**Comment by waylan** [comment] 2017-04-18 15:13
Closing this as a duplicate of #714.

**Closed by waylan** 2017-04-18 15:13 UTC
