### ISSUE TITLE
Search no longer works

### ISSUE THREAD

**Issue by nibblesnbits** [mkdocs/mkdocs#1807] opened 2019-06-06 13:48 UTC
Version: 1.0.4
Platform: Windows 10 Pro Build 10.0.17763
Browsers: Edge Version 76.0.176.1 (Official build) dev (64-bit), Chrome Version 74.0.3729.169 (Official Build) (64-bit), Firefox Developer Edition 68.0b7 (64-bit)

Issue:
When searching, I receive this error in the console and no results:
![image](https://user-images.githubusercontent.com/6042917/59037826-08e4af00-8840-11e9-8edc-1d63986de43d.png)

**Comment by waylan** [comment] 2019-06-10 18:59
This appears to be a duplicate of #1790. Note that the cause of the problem is a system configuration error and is not something we can address in MkDocs. Please follow the steps in #1790 to confirm and fix your system's configuration. Please follow up in that issue.

**Closed by waylan** 2019-06-10 18:59 UTC
