### ISSUE TITLE
Content not updated in browser when saved in .md file

### ISSUE THREAD

**Issue by btomasini** [mkdocs/mkdocs#1194] opened 2017-04-04 23:07 UTC
When running `mkdocs serve` and saving a change to the index.md, the change is not relected in the browser even when refreshing the page. I have to kill the mkdocs process and run it again.  I am editing the files in vim, with the following versions:

mkdocs, version 0.16.2

Ubuntu 16..04

The happens regardless of listing the pages in the config file or not.

What can I try to debug this?

**Comment by waylan** [comment] 2017-04-05 02:13
This is a duplicate of #1174 which fix was included in version 0.16.3 just released a few hours ago.

**Closed by waylan** 2017-04-05 02:13 UTC
