### ISSUE TITLE
README problem, or install permission problem

### ISSUE THREAD

**Issue by ppKrauss** [mkdocs/mkdocs#1188] opened 2017-04-03 12:04 UTC
```sh
Successfully built tornado MarkupSafe
Installing collected packages: singledispatch, certifi, backports-abc, tornado, livereload, MarkupSafe, Jinja2, click, mkdocs
Exception:
Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/user/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/user/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/user/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/user/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/user/.local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/user/.local/lib/python2.7/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] ... permission ...  '/usr/local/lib/python2.7/dist-packages/singledispatch_helpers.pyc'
```

After use `sudo pip install mkdocs`  and some warnings, 

```
The directory '/home/user/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/user/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
```

The installation run (?) fine:

```
Collecting mkdocs
  Downloading mkdocs-0.16.2-py2.py3-none-any.whl (1.2MB)
    100% |████████████████████████████████| 1.2MB 396kB/s 
Collecting tornado>=4.1 (from mkdocs)
Collecting livereload>=2.5.1 (from mkdocs)
  Downloading livereload-2.5.1-py2-none-any.whl
Requirement already satisfied: PyYAML>=3.10 in /usr/lib/python2.7/dist-packages (from mkdocs)
Collecting Jinja2>=2.7.1 (from mkdocs)
  Downloading Jinja2-2.9.5-py2.py3-none-any.whl (340kB)
    100% |████████████████████████████████| 348kB 1.1MB/s 
Requirement already satisfied: Markdown>=2.3.1 in /usr/lib/python2.7/dist-packages (from mkdocs)
Collecting click>=3.3 (from mkdocs)
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 1.0MB/s 
Collecting singledispatch (from tornado>=4.1->mkdocs)
  Downloading singledispatch-3.4.0.3-py2.py3-none-any.whl
Collecting certifi (from tornado>=4.1->mkdocs)
  Downloading certifi-2017.1.23-py2.py3-none-any.whl (382kB)
    100% |████████████████████████████████| 389kB 787kB/s 
Collecting backports-abc>=0.4 (from tornado>=4.1->mkdocs)
  Downloading backports_abc-0.5-py2.py3-none-any.whl
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from livereload>=2.5.1->mkdocs)
Collecting MarkupSafe>=0.23 (from Jinja2>=2.7.1->mkdocs)
Installing collected packages: singledispatch, certifi, backports-abc, tornado, livereload, MarkupSafe, Jinja2, click, mkdocs
Successfully installed Jinja2-2.9.5 MarkupSafe-1.0 backports-abc-0.5 certifi-2017.1.23 click-6.7 livereload-2.5.1 mkdocs-0.16.2 singledispatch-3.4.0.3 tornado-4.4.3
```

**Comment by waylan** [comment] 2017-04-03 13:12
It would appear you have an issue with your local system configuration. Note that the warnings state:

> If executing pip with sudo, you may want sudo's -H flag.

The [documentation][1] for the `sudo -H` flag states: 

> The -H (HOME) option sets the HOME environment variable to the homedir of the
> target user (root by default) as specified in passwd(5).  The default handling
> of the HOME environment variable depends on sudoers(5) settings.  By default,
> sudo will set HOME if env_reset or always_set_home are set, or if set_home is
> set and the -s option is specified on the command line.

I did some searching and found a [few][2] [similar][3] reports. The answer seems to always be: use `sudo -H`. Personally, I usually install into a virtual environment which avoids this sort of problem (don't even need `sudo`). There may be some local configuration you can do (perhaps set an environment variable) which would resolve it, but I'm not 100% clear what that would be.

In any event, this is not something we can address in the documentation. Not every user will need to use `-H` (in fact most won't). I've been using Linux for many years and have never seen this before. As the warning message suggests a reasonable workaround, I'm satisfied that the user is informed how to proceed.

[1]: http://www.unix.com/man-page/Linux/8/sudo/
[2]: https://github.com/pypa/virtualenv/issues/988
[3]: http://askubuntu.com/questions/744377/cache-pip-disabled-immediately-after-instalation-of-pip

**Comment by waylan** [comment] 2017-04-18 15:24
Closing this as there appears to be no actionable item.

**Closed by waylan** 2017-04-18 15:24 UTC

**Comment by choff5507** [comment] 2021-08-11 14:39
The error at that link you provided seems to be similar to what Im encountering. I have not tried running sudo pip because sudo is not found when I go to run it. When I run the container it's always a new instance and Ive checked my folder permissions in my directory as well and they're under my user so I am not sure what the issue is. I could have missed something as I am relatively new to Linux and Docker.
