### ISSUE TITLE
toc extension permalink id do not support utf8 first character

### ISSUE THREAD

**Issue by ngtrian** [mkdocs/mkdocs#1158] opened 2017-03-12 06:54 UTC
I using toc extension with mkdocs.

toc can not convert character  bellow to id:

> đ

**Comment by waylan** [comment] 2017-03-12 19:10
This needs to be handled upstream by the Python-Markdown project. As the same report has been made there waylan/Python-Markdown#555, I'm closing this.

**Closed by waylan** 2017-03-12 19:10 UTC

**Comment by waylan** [comment] 2017-03-12 19:19
Oh and this is technically a duplicate of #212 which contains a workaround to get a working solution for MkDocs.

**Comment by ngtrian** [comment] 2017-03-13 07:38
Thanks for support!
