### ISSUE TITLE
[WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by yc-zc** [mkdocs/mkdocs#1951] opened 2019-12-30 08:20 UTC
> We are going to need more information so that we can reproduce the error. What system are you on? What version of MkDocs are you using? Do you have any custom config settings? Which specific command did you run?

Windows 10 
MkDocs 1.0.4
https://github.com/yc-zc/web/blob/master/mkdocs.yml
mkdocs serve

_Originally posted by @yc-zc in https://github.com/mkdocs/mkdocs/issues/1260#issuecomment-569612567_

**Comment by yc-zc** [comment] 2019-12-30 08:26
I have checked the port 8000 isn't been used by another application, and I have manually set the port to another random port that isn't been used, but the error stays the same. 
This can be resolved by rebooting, but I hate rebooting...

**Comment by waylan** [comment] 2019-12-30 14:23
This is being closed as a duplicate of #1260

**Closed by waylan** 2019-12-30 14:23 UTC
