### ISSUE TITLE
mkdocs 404 on nav items

### ISSUE THREAD

**Issue by dangtd77** [mkdocs/mkdocs#1894] opened 2019-10-24 03:39 UTC
I'm using an issues referenced [here](https://github.com/mkdocs/mkdocs/issues/1875) after uninstalling python and reinstalling Version 3.5.3 and reinstalling mkdocs. 
```
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

still having the name problem

```
mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - index.md
  - management.md
  - tech.md
[I 191023 22:38:21 server:296] Serving on http://127.0.0.1:8000
```

_Originally posted by @dangtd77 in https://github.com/mkdocs/mkdocs/issues/1875#issuecomment-545717784_

**Comment by waylan** [comment] 2019-10-24 12:21
I’m closing this as a duplicate of #1894, which has been reopened. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed by waylan** 2019-10-24 12:21 UTC
