### ISSUE TITLE
Collapsable headings with RTD theme

### ISSUE THREAD

**Issue by evitalis** [mkdocs/mkdocs#1153] opened 2017-03-08 23:56 UTC
This could be a user error or limitation of the theme, but is it possible to collapse the sections when using the ReadTheDocs theme?

For instance my YAML looks like this:
```
pages:
- Home: 'index.md'
- Foo:
  - Bar:
    - 'Zed': 'Foo/Bar/Zed.md'
```
Admittedly I am using mkdocs slightly different than intended but I feel being able to collapse the headers might be helpful for someone and will keep things more tidy.

**Comment by waylan** [comment] 2017-03-09 01:53
This appears to be a duplicate of #588.

**Closed by waylan** 2017-03-09 01:53 UTC
