### ISSUE TITLE
New versions of pip don't install mkdocs v1.0.0+

### ISSUE THREAD

**Issue by James-Quigley** [mkdocs/mkdocs#1706] opened 2018-12-18 21:40 UTC
When installing mkdocs, pip version 8.1.2 will install mkdocs v1.0.4, but newer versions of pip like 18.1 can't find mkdocs v1+ and instead install mkdocs 0.17.5.

If I try to manually install a newer version via `pip install mkdocs==1.0` etc, I get 

```
sudo pip install mkdocs==1.0
Collecting mkdocs==1.0
  Could not find a version that satisfies the requirement mkdocs==1.0 (from versions: 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 0.11, 0.11.1, 0.12.0, 0.12.1, 0.12.2, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.17.5)
No matching distribution found for mkdocs==1.0
```

CentOS 7
Python 2.7.5
Pip 8.1.2 and 18.1

**Comment by algo99** [comment] 2018-12-18 21:44
See https://github.com/mkdocs/mkdocs/issues/1605

**Comment by waylan** [comment] 2018-12-18 21:47
MkDocs version 1.0 requires Python 2.7.9 however, you have Python 2.7.9. Apparently pip versions <= 8.1.2 didn't check that requirement. The newer versions of pip are correctly refusing to install the newer version of MkDocs as it will fail to run properly (in all supported ways) on your older Python version.

As noted by @algo99 this is a duplicate of #1605 and is being closed as such.

**Closed by waylan** 2018-12-18 21:47 UTC

**Comment by James-Quigley** [comment] 2018-12-18 21:53
I see. A little frustrating as I'm not sure how I would know that given that installation documentation didn't note that anywhere and change notes for v1.0.0 don't mention dropping support for python < 2.7.9.
