### ISSUE TITLE
How to change and make path clickable

### ISSUE THREAD

**Issue by Code-Egg** [mkdocs/mkdocs#1777] opened 2019-04-07 02:21 UTC
Hi

I am using mkdocs+read the doc theme, but can not find resource to help me make paths with hyperlink and change 'Docs' to other name. 

For example, this docs path (Ansible Docs Home» Ansible Tower Docs» — Ansible Tower User Guide ») are clickable which has hyperlink on it, but I dont see any method to make it works with mkdocs. Hope anyone can help.  
https://docs.ansible.com/ansible-tower/2.2.1/html/userguide/users.html

**Comment by waylan** [comment] 2019-04-07 23:03
I'm not sure I follow, but are you asking for the navigation section names to be links (clickable)? If so, then this would be a duplicate of #73. See also #1139 which contains a more recent discussion of the issue and points to a possible solution in [this comment](https://github.com/mkdocs/mkdocs/issues/1139#issuecomment-467443619).

Finally, note that the Ansible documentation is using a custom Sphinx theme which provides a custom implementation of the feature. This feature is not available in the standard Sphinx theme used by the readthedocs service. Likewise, you would need to use a custom MkDocs theme (as discussed in #1139) to get such a feature in MkDocs. However, unlike Sphinx, I am not aware of any MkDocs themes which currently offer such a feature.

**Closed** 2019-11-06 20:28 UTC
