### ISSUE TITLE
Left side of the default theme can not be rolled?

### ISSUE THREAD

**Issue by thinkxf** [mkdocs/mkdocs#635] opened 2015-06-16 03:52 UTC
Hi, I found that the left side of the default theme can not be rolled, which could cause the left of the list showing incomplete, and how to solve the problem?

**Comment by d0ugal** [comment] 2015-06-16 06:29
This is a duplicate of https://github.com/mkdocs/mkdocs/issues/204

**Closed by d0ugal** 2015-06-16 06:29 UTC
