### ISSUE TITLE
too many page links and too small a screen make funky* wrapping

### ISSUE THREAD

**Issue by gregglind** [mkdocs/mkdocs#1021] opened 2016-08-10 19:06 UTC
For themes with 'links on the top' (mkdocs), if there are 'too many', the 'prev, next, search' buttons flow to the next line, overflowing badly.  See screenshot.

<img width="1185" alt="screen shot 2016-08-10 at 2 04 25 pm" src="https://cloud.githubusercontent.com/assets/163983/17567043/6518f614-5f03-11e6-91b3-9b156a730878.png">

Workarounds:
1.  Use `readthedocs` theme (easy!)
2.  really dig into the css
3.  Use fewer pages?

**Note**: I mean funky in the bad way

**Comment by waylan** [comment] 2016-08-10 19:22
If you narrow the browser window, the header switches to 'mobile mode' and the menu is displayed differently (a hamburger menu). Perhaps we need something similar for a large number of top-level nav items.

In any event, do you need all of your pages to be at the top level? Could you [nest][1] them to reduce the number of top level nav items (like we do on the [MkDocs site][2])?

[1]: http://www.mkdocs.org/user-guide/writing-your-docs/#multilevel-documentation
[2]: http://www.mkdocs.org/

**Comment by gregglind** [comment] 2016-08-10 19:31
Nesting would work too, of course.  Another good workaround.

**Comment by waylan** [comment] 2018-08-23 18:33
Closing as a duplicate of #716.

**Closed by waylan** 2018-08-23 18:33 UTC
Labels: Needs design decision, Theme-mkdocs
