### ISSUE TITLE
mkdocs build generates/leaves several unnecessary files in site_dir

### ISSUE THREAD

**Issue by caspre24** [mkdocs/mkdocs#999] opened 2016-07-24 20:17 UTC
After running `mkdocs build`, files and folders like

+ `__pycache__`
+ `__init__.py`
+ `base.html`
+ `breadcrumbs.html`
+ `footer.html`
+ `sitemap.xml`
+ `toc.html`
+ `versions.html`

are generated and remain in the `site_dir`. These files/folders are not required for the site to be funktional and in some cases even contain `{% ... %}`-like placeholders.

Is there a way to prevent these files from being created or clean them up afterwards? Or are they needed in a use case that I can't see?

python 3.5.2 64 bit on Windows 10
mkdocs 0.15.3

**Comment by waylan** [comment] 2016-07-25 02:58
I'm closing this as a duplicate of #807. A fix was committed in ac2ff10a which will be available in the next release (0.16).

**Closed** 2016-07-25 02:58 UTC
