### ISSUE TITLE
Search broken in Internet Explorer when opening from disk

### ISSUE THREAD

**Issue by feppie64** [mkdocs/mkdocs#1454] opened 2018-04-04 11:50 UTC
Hi,

I would like to report that the search functionality is not working in Internet Explorer when opening the pages from disk, i.e. by using a link starting with file:///. The issue seems security policy related.

![afbeelding](https://user-images.githubusercontent.com/1690522/38305835-a6837d78-380e-11e8-98d6-9a8c3db92bf5.png)

This is the case in the current release, as well as in the master branch of this repository with the refactored search system.

So far, I have not been able to come up with a solution. Maybe someone else has an idea?

I'm not sure whether this is even supposed to be supported by Mkdocs, but I couldn't find anywhere that it shouldn't.

Thanks!

**Comment by waylan** [comment] 2018-04-04 12:50
This is a duplicate of #871.

**Closed by waylan** 2018-04-04 12:50 UTC
