### ISSUE TITLE
gitlab pages : unable to execute 'gcc': No such file or directory

### ISSUE THREAD

**Issue by hefistion** [mkdocs/mkdocs#2078] opened 2020-04-22 17:48 UTC
I tried to deploy mkdocs on gitlab pages, I forked this repository https://gitlab.com/pages/mkdocs, but I got this error,

I am newbie and would appreciate any help, thanks

`
Running with gitlab-runner 12.10.0-rc2 (6c8c540f)
  on docker-auto-scale 72989761
Preparing the "docker+machine" executor
00:11
Using Docker executor with image python:alpine ...
Pulling docker image python:alpine ...
Using docker image sha256:d5e5ad4a4fc0f4e009ed63f47b010c0f864ca8e0dcde132c37bb4c0aee7e4da2 for python:alpine ...
Preparing environment
00:04
Running on runner-72989761-project-18303487-concurrent-0 via runner-72989761-srm-1587574891-a75fdad5...
Getting source from Git repository
00:02
$ eval "$CI_PRE_CLONE_SCRIPT"
Fetching changes...
Initialized empty Git repository in /builds/hefistion/mkdocs/.git/
Created fresh repository.
From https://gitlab.com/hefistion/mkdocs
 * [new ref]         refs/pipelines/138786904 -> refs/pipelines/138786904
 * [new branch]      2-error-in-gitlab-ci-trying-to-install-the-mkdocs-library -> origin/2-error-in-gitlab-ci-trying-to-install-the-mkdocs-library
 * [new branch]      master                   -> origin/master
Checking out 31a61881 as master...
Skipping Git submodules setup
Restoring cache
00:01
Downloading artifacts
00:02
Running before_script and script
00:11
$ pip install mkdocs
Collecting mkdocs
  Downloading mkdocs-1.1-py2.py3-none-any.whl (6.4 MB)
Collecting PyYAML>=3.10
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
Collecting Markdown>=3.2.1
  Downloading Markdown-3.2.1-py2.py3-none-any.whl (88 kB)
Collecting lunr[languages]==0.5.6
  Downloading lunr-0.5.6-py2.py3-none-any.whl (36 kB)
Collecting click>=3.3
  Downloading click-7.1.1-py2.py3-none-any.whl (82 kB)
Collecting livereload>=2.5.1
  Downloading livereload-2.6.1-py2.py3-none-any.whl (23 kB)
Collecting tornado>=5.0
  Downloading tornado-6.0.4.tar.gz (496 kB)
Collecting Jinja2>=2.10.1
  Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Requirement already satisfied: setuptools>=36 in /usr/local/lib/python3.8/site-packages (from Markdown>=3.2.1->mkdocs) (46.1.1)
Collecting future>=0.16.0
  Downloading future-0.18.2.tar.gz (829 kB)
Collecting six>=1.11.0
  Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
Collecting nltk>=3.2.5; extra == "languages"
  Downloading nltk-3.5.zip (1.4 MB)
Collecting MarkupSafe>=0.23
  Downloading MarkupSafe-1.1.1.tar.gz (19 kB)
Collecting joblib
  Downloading joblib-0.14.1-py2.py3-none-any.whl (294 kB)
Collecting regex
  Downloading regex-2020.4.4.tar.gz (695 kB)
Collecting tqdm
  Downloading tqdm-4.45.0-py2.py3-none-any.whl (60 kB)
Building wheels for collected packages: PyYAML, tornado, future, nltk, MarkupSafe, regex
  Building wheel for PyYAML (setup.py): started
  Building wheel for PyYAML (setup.py): finished with status 'done'
  Created wheel for PyYAML: filename=PyYAML-5.3.1-cp38-cp38-linux_x86_64.whl size=44617 sha256=467db93403c5932284634ed0ca2cdaf0994632bd9b8ab34a28057e40721883c3
  Stored in directory: /root/.cache/pip/wheels/13/90/db/290ab3a34f2ef0b5a0f89235dc2d40fea83e77de84ed2dc05c
  Building wheel for tornado (setup.py): started
  Building wheel for tornado (setup.py): finished with status 'done'
  Created wheel for tornado: filename=tornado-6.0.4-cp38-cp38-linux_x86_64.whl size=415149 sha256=835b0fefc5b904727a99282ef2dccbd7b5ab10253c2545d43d401ecb27b39a9f
  Stored in directory: /root/.cache/pip/wheels/88/79/e5/598ba17e85eccf2626eab62e4ee8452895636cd542650d450d
  Building wheel for future (setup.py): started
  Building wheel for future (setup.py): finished with status 'done'
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=52e3f08caab0b38c760b3bdcd42c0036f9f777977315db82862c86742d6c3c33
  Stored in directory: /root/.cache/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4
  Building wheel for nltk (setup.py): started
  Building wheel for nltk (setup.py): finished with status 'done'
  Created wheel for nltk: filename=nltk-3.5-py3-none-any.whl size=1434673 sha256=7f24707f79743acda2b7d83bf844a77f62903ea4af5eb9555fe90657995555c4
  Stored in directory: /root/.cache/pip/wheels/ff/d5/7b/f1fb4e1e1603b2f01c2424dd60fbcc50c12ef918bafc44b155
  Building wheel for MarkupSafe (setup.py): started
  Building wheel for MarkupSafe (setup.py): finished with status 'done'
  Created wheel for MarkupSafe: filename=MarkupSafe-1.1.1-py3-none-any.whl size=12629 sha256=bd0cabf2adeebca122c96a909e42861e99af76d6892dcf5f704039df1bde947c
  Stored in directory: /root/.cache/pip/wheels/0c/61/d6/4db4f4c28254856e82305fdb1f752ed7f8482e54c384d8cb0e
  Building wheel for regex (setup.py): started
  Building wheel for regex (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vynjeh0a/regex/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vynjeh0a/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6kjniyl4
       cwd: /tmp/pip-install-vynjeh0a/regex/
  Complete output (17 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/regex
  copying regex_3/__init__.py -> build/lib.linux-x86_64-3.8/regex
  copying regex_3/regex.py -> build/lib.linux-x86_64-3.8/regex
  copying regex_3/_regex_core.py -> build/lib.linux-x86_64-3.8/regex
  copying regex_3/test_regex.py -> build/lib.linux-x86_64-3.8/regex
  running build_ext
  building 'regex._regex' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/regex_3
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.8 -c regex_3/_regex.c -o build/temp.linux-x86_64-3.8/regex_3/_regex.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for regex
  Running setup.py clean for regex
Successfully built PyYAML tornado future nltk MarkupSafe
Failed to build regex
Installing collected packages: PyYAML, Markdown, future, six, click, joblib, regex, tqdm, nltk, lunr, tornado, livereload, MarkupSafe, Jinja2, mkdocs
    Running setup.py install for regex: started
    Running setup.py install for regex: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vynjeh0a/regex/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vynjeh0a/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-et3u2ea0/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/regex
         cwd: /tmp/pip-install-vynjeh0a/regex/
    Complete output (17 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/regex
    copying regex_3/__init__.py -> build/lib.linux-x86_64-3.8/regex
    copying regex_3/regex.py -> build/lib.linux-x86_64-3.8/regex
    copying regex_3/_regex_core.py -> build/lib.linux-x86_64-3.8/regex
    copying regex_3/test_regex.py -> build/lib.linux-x86_64-3.8/regex
    running build_ext
    building 'regex._regex' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/regex_3
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.8 -c regex_3/_regex.c -o build/temp.linux-x86_64-3.8/regex_3/_regex.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vynjeh0a/regex/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vynjeh0a/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-et3u2ea0/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/regex Check the logs for full command output.
Running after_script
00:02
Uploading artifacts for failed job
00:01
ERROR: Job failed: exit code 1

`

**Comment by waylan** [comment] 2020-04-22 22:38
This is a duplicate of #2062 which was fixed in #2069 and will be available in the next release.

In the meantime, if you install nltk<3.5 before installing MkDocs, that should provide a workaround for you.

**Closed by waylan** 2020-04-22 22:38 UTC

**Comment by hefistion** [comment] 2020-04-24 14:46
Ok, thank you very much

**Comment by preeteshjain** [comment] 2020-04-27 07:09
@hefistion You can add `pip install nltk==3.4.5` to your Gitlab CI config file to prevent this error, while this gets fixed. Like so:

```yaml
image: python:alpine

before_script:
  - pip install nltk==3.4.5
  - pip install mkdocs
  - pip install mkdocs-material

pages:
  script:
  - mkdocs build
  - mv site public
  artifacts:
    paths:
    - public
  only:
  - master
```

**Comment by hefistion** [comment] 2020-04-27 21:28
@preeteshjain I have done it and it works perfect, thank you very much.
