### ISSUE TITLE
Search doesn't give priority to topics

### ISSUE THREAD

**Issue by bhathiya** [mkdocs/mkdocs#1916] opened 2019-12-04 14:36 UTC
Please search "Create API Product" in https://apim.docs.wso2.com/en/latest/

We have a doc[1] with the same title, but it doesn't come to the top. Is there anything to configure in the search plugin?

[1] https://apim.docs.wso2.com/en/latest/Learn/DesignAPI/CreateAPIProduct/create-api-product/

**Comment by waylan** [comment] 2019-12-04 15:03
The search engine we use is lunr.js. Documentation on manipulating the search priority is [here](https://lunrjs.com/guides/searching.html).

For a similar discussion see #1914. I am inclined to close this as a duplicate of that.

**Comment by bhathiya** [comment] 2019-12-04 15:08
Thanks. I'll have a look.

**Comment by bhathiya** [comment] 2019-12-05 05:25
I'm reopening this to get something clarified. In #1914, you have mentioned the below.
> every feature you are asking for is already available with no code changes.

I hope what that means is I can use `+`,`-`, `title:` etc. to fine-tune my search query, without any configuration changes. Am I correct? I'm asking because, I don't see it working in my case.

What I tried was `Create API +Product`.

**Comment by waylan** [comment] 2019-12-05 13:54
> I hope what that means is I can use `+`,`-`, `title:` etc. to fine-tune my search query, without any configuration changes. Am I correct? I'm asking because, I don't see it working in my case.

Yes, according to my understanding of lunr.js' documentation, this should just work out-of-the-box with no configuration changes. If it's not working, then that would be an upstream issue.

I do see that lunr.js is now up to version 2.3.8 while we are using 2.3.2. Although, the [changelog][2] doesn't seem to indicate that that should make a difference with this issue. Regardless, we probably should update ([mkdocs/contrib/search/templates/search/lunr.js][3] just needs to be updated to the latest version at [@olivernn/lunr.js][4]).

Also I should note that the "[fields][1]" in MkDocs' index are named `title` and `text`. We should probably document that somewhere.

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/contrib/search/templates/search/worker.js#L74-L75
[2]: https://github.com/olivernn/lunr.js/blob/master/CHANGELOG.md
[3]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/contrib/search/templates/search/lunr.js
[4]: https://github.com/olivernn/lunr.js/blob/master/lunr.js

**Comment by waylan** [comment] 2019-12-05 15:20
Looking at lunr.js' documentation, they provide two mechanisms for doing a search:

1. A [query][1] method which accepts a custom built [Query][2] instance.
2. A [search][3] method which accepts a [querystring][4]. Internally, that `querystring` is parsed by lunr.js and converted into a `Query` instance.

We are using option 2 (the `search` method). The point is, that parsing and interpreting the query string is all internal to lunr.js and outside of our control as it is implemented today. I'd rather not make it more complicated in the base implementation, but if others wanted to they could implement something else in a third party theme. For that matter, The `material` theme provides their own search implementation, so they may very well be using a different method. If you are using that theme, you might want to take the issue there.

[1]: https://lunrjs.com/docs/lunr.Index.html#query
[2]: https://lunrjs.com/docs/lunr.Query.html
[3]: https://lunrjs.com/docs/lunr.Index.html#search
[4]: https://lunrjs.com/docs/lunr.Index.html#~QueryString

**Comment by waylan** [comment] 2019-12-05 15:34
Looking back at the first comment, I see you are using the `material` theme. And looking at squidfunk/mkdocs-material#1362 it appears that they are building their own custom `Query` (option 1 in my previous comment). That being the case, that theme does not support lunr.js' `quearystring`. Therefore, this issue is completely an upstream issue with the theme. For that reason I am closing this.

**Closed by waylan** 2019-12-05 15:34 UTC
