### ISSUE TITLE
Tasks lists in pymdown-extensions break bullet points

### ISSUE THREAD

**Issue by nathancarter** [mkdocs/mkdocs#1445] opened 2018-03-26 20:35 UTC
To reproduce:

Create a new project, that is, an empty folder.  Place a `mkdocs.yml` in it, containing this:

```yaml
site_name: test
pages:
- Home: index.md
markdown_extensions:
- pymdownx.tasklist
```

Create a `docs/` subfolder and place in it a single`index.md` file with bullet points that start with task checkboxes, like so:

```markdown

 * [ ] The text on this line will be rendered, but the text on the
   second line will not.
 * [ ] You can get it to start working if you do any kind of
   special content.  For instance, *right here* it will start
   working because I used bold.  But using `preformatted` or some
   other type of content works, too.
 * Bullet points that don't start with a task checkbox are fine,
   like this one.

```

The result is as described in the text above; large portions of text are missing, not rendered in the output HTML.  Screenshot:

![screen shot 2018-03-26 at 4 28 13 pm](https://user-images.githubusercontent.com/1316622/37931393-773be39a-3113-11e8-8a47-61bb2f38109c.png)

This may be a problem with mkdocs or with pymdown-extensions.  I'm not sure, but I'm reporting it here and if you figure out that it belongs upstream, I/we can copy it over.

**Comment by facelessuser** [comment] 2018-03-26 20:47
This is a pymdown-extensions issue, and this probably should have been brought up there.  Can you please create the issue over there?  I believe the issue is simply that we are not using `re.DOTALL` in our post processing pattern search when applying the tasklist in post process.  Because we are not using `re.DOTALL`, the pattern doesn't capture line breaks when it is reconstructing the list item.

**Comment by nathancarter** [comment] 2018-03-26 20:49
My only question is how to construct the issue over there.  I don't use the feature outside of mkdocs, so I'm not sure how to do the minimal reproducible example.  (Well, without going and learning how, anyway.)

**Comment by waylan** [comment] 2018-03-26 23:05
Closing this an an upstream issue.

**Closed by waylan** 2018-03-26 23:05 UTC

**Comment by facelessuser** [comment] 2018-03-26 23:54
@nathancarter, FYI, I took care of the issue.  I imagine I'll probably tag a release tonight.

**Comment by nathancarter** [comment] 2018-03-27 14:00
Wow, that was fast!  Thanks!
