### ISSUE TITLE
LiveReload being picky about reloading

### ISSUE THREAD

**Issue by omento** [mkdocs/mkdocs#1190] opened 2017-04-03 22:51 UTC
This is a bit similar to #960, but without any errors. When saving a file after modifications, livereload will 98% of the time not update the page in question.

mkdocs 0.16.2
CentOS 7 (1611) up-to-date
Firefox 52.02 (self-installed and updated)
Python 2.7.5 (I do have 3.6 available)

Steps:  
* Activate MkDocs virtual environment for project  
* Navigate to root of project  
* `mkdocs serve` (also used `--livereload` and `--dirtyreload`)  
* Make a change or add content to a page  
* Watch browser reload page without showing any changes  

I may just be misunderstanding the scope of livereload, but I thought I had read the docs pretty thoroughly. It seems that if I make a style change, like bolding/italicizing existing text, or sometimes creating a link the page updates fine. But if I add content to the page it will not update with anything new even after self-reloading. For the past few days I've just been closing and rerunning the `serve` command every time I added or changed large portions of content.

Typical output:
```
(rsdocs) $ mkdocs serve
INFO    -  Building documentation... 
INFO    -  Cleaning site directory
[I 170403 18:47:05 server:283] Serving on http://127.0.0.1:8000
[I 170403 18:47:05 handlers:60] Start watching changes
[I 170403 18:47:05 handlers:62] Start detecting changes
[W 170403 18:47:12 web:1971] 404 GET /assets/images/favicon.png (127.0.0.1) 7.23ms
[I 170403 18:47:13 handlers:133] Browser Connected: http://localhost:8000/
INFO    -  Building documentation... 
[I 170403 18:48:08 handlers:93] Reload 1 waiters: /path/to/docs/index.md
[W 170403 18:48:09 web:1971] 404 GET /favicon.ico (127.0.0.1) 4.63ms
[I 170403 18:48:09 handlers:133] Browser Connected: http://localhost:8000/
[W 170403 18:48:09 web:1971] 404 GET /favicon.ico (127.0.0.1) 4.57ms
^C[I 170403 18:48:44 server:303] Shutting down...
```

**Comment by waylan** [comment] 2017-04-04 00:16
This is a duplicate of #1174, which will be available in the next release.

**Comment by facelessuser** [comment] 2017-04-04 00:53
I just ran into this issue over the weekend.  Hopefully we'll get a fix out soon-ish. It's a pretty annoying bug.

**Comment by omento** [comment] 2017-04-04 13:14
> This is a duplicate of #1174, which will be available in the next release.

Awesome, thank you for the notice! It seems I need to do a better job with my search keywords, that issue never showed up...

**Closed** 2017-04-04 13:16 UTC

**Comment by waylan** [comment] 2017-04-04 13:19
Annoyingly, GitHub's default is to search open issues only, which means any resolved (closed) issues don't show up. Unless I know that an issue is open, I'm always sure to search both open and closed issues.

**Comment by waylan** [comment] 2017-04-04 18:15
@facelessuser see #1192.

**Comment by facelessuser** [comment] 2017-04-04 20:56
@waylan, thanks for heads up!
