### ISSUE TITLE
Dropdown menu issue - mkdocs theme

### ISSUE THREAD

**Issue by tramponi** [mkdocs/mkdocs#1089] opened 2016-11-11 09:38 UTC
Hi,
it looks like there is an issue with the mkdocs theme (0.16 release):

When you start clicking different dropdown buttons, any previous dropdown button is not being immediately "released" ...

Here's an example from Mkdocs homepage

![mkdocs-theme](https://cloud.githubusercontent.com/assets/18346173/20210322/36e64bc2-a7f9-11e6-955f-6b0d6ab02fc5.png)

**Comment by waylan** [comment] 2016-11-11 17:44
Yeah, I noticed that recently as well. Not sure if it has always behaved that way or not.

**Comment by tramponi** [comment] 2016-11-14 08:51
Mmh..I'm not able to reproduce the bug with the 0.15.3 release. So it's probably a 0.16 thing

**Comment by d0ugal** [comment] 2016-11-15 21:09
Yeah, this is new.

**Comment by d0ugal** [comment] 2016-11-15 21:12
https://twitter.com/ZacheryW/status/798633493701935104

Based on that, it might be caused by a change made #406

**Comment by waylan** [comment] 2016-11-15 23:51
Just did a little debugging. When a "dropdown" menu item is clicked/selected, the classes `open` and `active` are assigned to it (`<li class="dropdown open active">`). However, when you click off the item, only the `open` class is removed and the `active` class remains (`<li class="dropdown active">`). If I manually remove the `active` class (`<li class="dropdown">`), the item returns to its normal state.

Of course, the `active` class is used to designate the currently viewed page. So if the current page is a subpage of a menu item, then the active class should stay. But if the current page is not a subpage of the menu item, then I would expect the `active` to not be used at all. In fact, having only the `open` class assigned to a menu item works just fine. I'm assuming the `active` class should not be added when a menu item is clicked. Haven't worked out where in the code that is happening though.

**Comment by waylan** [comment] 2016-11-16 00:06
And I just confirmed, in version 0.15.3 the `active` class did not get assigned to a "dropdown" when it was "opened".

**Comment by waylan** [comment] 2016-11-16 00:18
The offending code was added in 53aee80, which was the (partial) fix for #406. The problem is that it should only affect the TOC, but it operates on `$(".nav a")` which applies to both the TOC and the nav bar. The nav bar is `<ul class="nav navbar-nav">` whereas the TOC uses `<ul class="nav bs-sidenav">`.

**Closed** 2016-11-16 00:42 UTC
Labels: Bug
