### ISSUE TITLE
Repeated python errors for every command ran

### ISSUE THREAD

**Issue by jms1989** [mkdocs/mkdocs#800] opened 2016-01-17 17:03 UTC
I get this everytime I run a command with mkdocs but the program still runs. I have no idea how to fix it. This is on linux mint 17 and on a workspace created on C9.io. Both with python 2.7.6 and pip 1.5.4.

```
jms1989:~/workspace $ mkdocs
/usr/local/lib/python2.7/dist-packages/mkdocs/cli.py:86: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/local/lib/python2.7/dist-packages/mkdocs/cli.py:100: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/local/lib/python2.7/dist-packages/mkdocs/cli.py:125: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/local/lib/python2.7/dist-packages/mkdocs/cli.py:145: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/local/lib/python2.7/dist-packages/mkdocs/cli.py:176: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/local/lib/python2.7/dist-packages/mkdocs/cli.py:194: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
Usage: mkdocs [OPTIONS] COMMAND [ARGS]...

  MkDocs - Project documentation with Markdown.

Options:
  -V, --version  Show the version and exit.
  -q, --quiet    Silence warnings
  -v, --verbose  Enable verbose output
  -h, --help     Show this message and exit.

Commands:
  build      Build the MkDocs documentation
  gh-deploy  Deply your documentation to GitHub Pages
  json       Build the MkDocs documentation to JSON files...
  new        Create a new MkDocs project
  serve      Run the builtin development server
```

I should note that this is with version 0.14.0. I test the dev version 0.15.0-dev and the error doesn't appear.

**Comment by jms1989** [comment] 2016-01-17 17:13
I should note that this is with version 0.14.0. I test the dev version 0.15.0-dev and the error doesn't appear.

**Comment by d0ugal** [comment] 2016-01-17 17:56
Yup, this isn't an error just a warning you can safely ignore. This is a duplicate of many other issues 🙂

**Closed** 2016-01-17 17:56 UTC
