### ISSUE TITLE
Title in markdown file used for navigation -> Clarify markdown style

### ISSUE THREAD

**Issue by pixelbrackets** [mkdocs/mkdocs#1837] opened 2019-08-09 13:44 UTC
Hey,

then navigation will use the title given in a markdown file, if no title was given in the »nav« option. See https://github.com/mkdocs/mkdocs/issues/316

The title in the document needs to have this schema:

    # H1 Title

However markdown supports this schema as well:

    H1 Title
    ======

mkdocs only accepts the first schema. I would expect it to work with the second schema as well.

Idea 1: Parse the second schema as well.
Idea 2: Clarify the accepted markdown style in the [documentation](https://www.mkdocs.org/user-guide/configuration/#nav).

**Comment by waylan** [comment] 2019-08-09 13:51
This appears to be a duplicate of #1826. Regarding the desire to clarify the documentation, PRs are welcome.

**Comment by pixelbrackets** [comment] 2019-08-12 12:45
You are right, this is a duplicate of #1826 (wont fix). I'll send a PR to clarify the docs shortly.

Thanks for the fast response.

**Closed** 2019-08-13 13:08 UTC
