### ISSUE TITLE
Using HTML5 <video src='...'> truncates page content

### ISSUE THREAD

**Issue by connercowling** [mkdocs/mkdocs#1327] opened 2017-10-27 13:49 UTC
## Description

A variation of HTML5 video tag **causes any content following the video tag to not be rendered**. 

This works:

```
<video style="width:100%" controls>
  <source src="video.mp4" type="video/mp4">
Your browser does not support the video tag.
</video>
```

This does not:

```
<video style="width:100%" controls src="video.mp4" type="video/mp4"/>
```

### Expected behavior

For the video to be rendered AND the markdown content following the tag to be rendered. 

It would appear **both** methods of specifying the source file are valid according to spec (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video):

<img width="691" alt="screen shot 2017-10-27 at 8 34 25 am" src="https://user-images.githubusercontent.com/3486466/32106925-b1e38972-baf2-11e7-9139-40a6faef7a8d.png">

### Actual behavior

Video element renders in DOM, all content following the video tag in the .md file simply does not appear.

### Steps to reproduce the bug

1. Put an HTML5 video tag in .md file: `<video style="width:100%" controls src="local-video.mov"/>`
2. Include some markdown content after the video tag: `Blah blah`
3. `mkdocs serve`
4. View the page: you should see the video rendered but the following content is not (i.e. `Blah blah` will not render)

### Package versions

* Python: 3.5.4
* MkDocs: 0.16.3

### System information

* OS: macOS Sierra
* Browser: Chrome 61.0

**Comment by waylan** [comment] 2017-10-27 14:01
This appears to be an issue with the Markdown parser that MkDocs uses. Please report this upstream to [Python-Markdown](https://github.com/Python-Markdown/markdown).

**Comment by connercowling** [comment] 2017-10-27 15:20
@waylan I tested this out and Python-Markdown seems to work fine.

```
<!--video-source-element.md-->
<video style="width:70%" controls>
  <source src="local-video.mov">
  Your browser does not support the video tag.
</video>
```

```
<!--video-src-attribute.md-->
<video style="width:70%" controls src="local-video.mov"></video>
```

```
In [1]: import markdown

In [2]: with open("video-src-attribute.md", "rb") as f:
   ...:     src_att = f.read()
   ...:

In [3]: with open("video-source-element.md", "rb") as f:
    source_element = f.read()
   ...:

In [4]: with open("video-source-element.html", "wb") as f:
    f.write(markdown.markdown(source_element))
   ...:

In [5]: with open("video-src-attribute.html", "wb") as f:
    f.write(markdown.markdown(src_att))
```

Perhaps it's an issue with the Mkdocs dev server?

**Comment by waylan** [comment] 2017-10-27 16:56
But that doesn't match your original report. Notice the different way you closed the `video` tag: `/>` vs. `></video>`. I expect that the first (self-closing tag) would fail if passed directly to Python-Markdown and the second would work as desired in MkDocs. If I'm right, then this is a Python-Markdown issue.

I haven't checked, but is a self-closing video tag even valid HTML5? If not, then this may not be a bug, just a result of bad input. Invalid raw HTML in the input results in bad output. Markdown makes no attempts to fix your raw HTML mistakes (neither should it). Sometimes the bad output is more surprising than others, but the only fix is to fix the input. My point is that if this is a case of invalid HTML in the input, then its not a bug anywhere, but that discussion would still be a Python-Markdown discussion, not a MkDocs discussion.

As an aside, I also noticed that when using a self-closing tag, you failed to include a space before the closing slash. Like this:

```html
<video style="width:100%" controls src="video.mp4" type="video/mp4" />
                                                                   ^
```

Again, I don't recall if that is required in HTML5, but it certainly was in XHTML where self-closing tags were first introduced (IIRC). That could be another cause for your problem. Again, that would be a Python-Markdown issue.

**Comment by waylan** [comment] 2017-10-30 14:49
Okay, I looked at the HTML5 Spec and it is clear that the problem here is invalid raw HTML is being provided in the input. The original report showed this HTML:

```html
<video style="width:100%" controls src="video.mp4" type="video/mp4"/>
                                                                  ^^
```

Notice that the `video` tag is a self-closing tag here. However, the spec clearly [states][1] that regarding the `video` tag:

> ### Tag omission in text/html
> 
> Neither tag is omissible

For contrast, the [img][2] tag has this:

> ### Tag omission in text/html:
>
> No end tag.

And [elsewhere][3] that section of each element is explained as follows: 

> ### Tag omission in text/html
> 
> A non-normative description of whether, in the text/html syntax, the start and end tags can be omitted. This information is redundant with the normative requirements given in the optional tags section, and is provided in the element definitions only as a convenience.

Finally, the [Elements][4] section provides some more general information:

> Tags are used to delimit the start and end of elements in the markup. Raw text, escapable raw text, and normal elements have a start tag to indicate where they begin, and an end tag to indicate where they end. The start and end tags of certain normal elements can be omitted, as described below in the section on optional tags. Those that cannot be omitted must not be omitted. Void elements only have a start tag; end tags must not be specified for void elements. Foreign elements must either have a start tag and an end tag, or a start tag that is marked as self-closing, in which case they must not have an end tag.

From all of this, it is clear that a `video` tag cannot be a self-closing tag. If must have a **closing tag**, like this:

```html
<video style="width:100%" controls src="video.mp4" type="video/mp4"></video>
                                                                    ^^^^^^^^
```

And in fact, as was demonstrated in a separate comment above, when that HTML is used in the Markdown, no error occurs. Therefore, the bad output is a result of bad input, which is to be expected. Therefore, this issue is being closed as user error. If you disagree, please take the discussion to the Python-Markdown project.


[1]: https://www.w3.org/TR/html5/embedded-content-0.html#the-video-element
[2]: https://www.w3.org/TR/html5/embedded-content-0.html#the-img-element
[3]: https://www.w3.org/TR/html5/dom.html#element-dfn-tag-omission
[4]: https://www.w3.org/TR/html5/syntax.html#elements-0

**Closed by waylan** 2017-10-30 14:49 UTC

**Comment by connercowling** [comment] 2017-10-31 03:00
@waylan yes I originally overlooked the difference between the self-closing tag. Good catch.

It's probably good to make note that many systems *will* render the self-closing tag (e.g. Chrome, Jupyter Notebooks, MacDown, etc.) – regardless of the spec. This is part of what spurred the initial confusion.

**Comment by connercowling** [comment] 2017-10-31 03:05
There is a remaining issue: MkDocs will render the video for index.md, but not for any other page (as far as I can tell).

That is:

```
mkdocs.yml
docs/
  index.md
  other-page.md
```

With
```
...
pages:
  - "": "index.md"
  - "other page": "other-page.md"
```

Works

```
# index

<video style="width:100%" controls>
  <source src="local-video.mov" type="video/mp4">
Your browser does not support the video tag.
</video>
```

Doesn't work

```
# other-page

<video style="width:100%" controls>
  <source src="local-video.mov" type="video/mp4">
Your browser does not support the video tag.
</video>
```

**Comment by waylan** [comment] 2017-10-31 12:49
As a reminder, MkDocs adds a special processor for internal links which modifies the path to ensure they properly point at the correct target. However, that only works for links in Markdown format. There is no way to do that for raw HTML. Therefore, you need to use proper relative URLs within raw HTML. 

As MkDocs uses "pretty URLs" the URL for any page except index pages are rewritten from `page.md` to `page/index.html` (so you can point your browser at `page/`). However, media files do not get moved. Therefore, the relative URL to a media file would need to at least step back one directory. So in your `other-page` example, you would need `src="../local-video.mov"`.
