### ISSUE TITLE
Add use_directory_urls option to build command

### ISSUE THREAD

**Issue by memeplex** [mkdocs/mkdocs#1017] opened 2016-08-08 01:28 UTC
Since other config options affecting the generation of output (theme, site, etc) are also build cli options, why not add use_directory_urls to the cli? I may be useful if you build a local fs version of a site and also a hosted version (I do that).

I can write a PR fir this.

**Comment by waylan** [comment] 2016-08-08 01:41
Back before we used the `Click` lib for command line parsing, the build command (and serve, IIRC) accepted any arbitrary flag and passed it on to `build` as a keyword. Click doesn't really offer the ability to do that though. Therefore, we defined flags for the few config options that it made sense for users to override from the CLI with the idea that as we come across good use-cases we hadn't considered, we could add more. I'm not sure if I consider this a "good" use-case. Especially given that this is the first request I've seen for it (most such requests were made immediately after we made the change) and we get people asking questions regarding the `use_directory_url` setting all the time. I'll have to think on it, unless @d0ugal chimes in with an opinion.

**Comment by memeplex** [comment] 2016-08-08 01:45
I understand your concern. I see this option more associated to the generation process itself than to the site structure.

**Comment by memeplex** [comment] 2016-08-08 02:00
@waylan regarding click, what about this http://click.pocoo.org/5/advanced/#forwarding-unknown-options?

**Comment by waylan** [comment] 2016-08-08 03:08
> what about this http://click.pocoo.org/5/advanced/#forwarding-unknown-options?

Interesting. But are there really that many additional settings that could even be defined from the CLI? For instance, `pages` and `markdown_extensions` are complex data structures that could not be passed in without some sort of special definitions and preprocessing (if at all). The few settings which could actually work (probably only bool or string types) are mostly already available and the few left seem to lack "good" use-cases. In other words, I question the value of building in a new error-prone interface with no error checking. The result would be ugly/cryptic  error messages that would confuse the non-python-dev user. IMO, it was a huge step forward when we removed the ability to pass in arbitrary config options.

**Comment by waylan** [comment] 2018-08-16 19:43
Closing this as a duplicate of #1401. I realize this is older, but that one provides a clear explanation and use case, whereas this discussion got derailed.

**Closed by waylan** 2018-08-16 19:43 UTC
Labels: Enhancement
