### ISSUE TITLE
Code blocks wrongly highlighted

### ISSUE THREAD

**Issue by obestwalter** [mkdocs/mkdocs#902] opened 2016-04-17 10:49 UTC
A block like this:

    Obtaining file:///</path/to/your/clone>
    Installing collected packages: mau-mau
      Running setup.py develop for mau-mau
    Successfully installed mau-mau

should simply be rendered with `<pre></pre>` - like here in this issue. But instead it is somehow detected as some langauge and wrongly highlighted (in this case elixir) syntax . See for example: http://oliver.bestwalter.de/mau-mau/dev/getting-started/

Is this kind of automatic detection a bug or a feature? If it's a feature: Is there a way to switch it off? I don't see any highlighting settings in the [configuration docs](http://www.mkdocs.org/user-guide/configuration/).

**Comment by waylan** [comment] 2016-04-18 02:44
This is a duplicate of #467.

**Closed by waylan** 2016-04-18 02:44 UTC

**Comment by obestwalter** [comment] 2016-04-18 18:41
I read #467 and the surrounding discussions. They all revolve around giving users the ability to easier modify themes or even add a plugin API. What I describe here is a bug that already occurs in the default theme.

Steps to reproduce: with a fresh install of MkDocs and a new project add this line to the code clock in the autogenerated index.md (or add an additional code block - same result):

    from here to there: this should not be highlighted

The code block gets recognized as livescript and is wrongly highlighted.

![2016-04-18-202457_1916x1041_scrot](https://cloud.githubusercontent.com/assets/263007/14615031/1d46487c-05a4-11e6-8964-91b849b9afa8.png)

IMHO this should be fixed independently from what is proposed and discussed in #467 or other issues.

**Comment by d0ugal** [comment] 2016-04-18 18:44
> IMHO this should be fixed independently from what is proposed and discussed in #467 or other issues.

Fixed how?

**Comment by obestwalter** [comment] 2016-04-18 18:46
In the way that a verbatim block does not get wrongly highlighted as some random language in the default theme with the default settings?

**Comment by waylan** [comment] 2016-04-18 19:03
It sounds as if the "fix" you ask for would be a "fix" to the highlight.js library. In that case, the "bug"  (incorrectly identifying plain text blocks) should be reported upstream to that library. If you would like a "fix" at the MkDocs level, then that falls under #467. In other words, any changes to MkDocs to address this issue would be the changes discussed in #467. Even if we were to make the drastic change of having highlighting disabled by default for all code blocks,  the changes discussed in #467 would be how users would then enable/configure code highlighting.  In the unlikely event that such a change was made, it would only happen after a provision to enable/configure code highlighting was available.

My point is that unless I'm missing something obvious, any fix for this issue at the MkDocs level is directly connected with #467.

**Comment by obestwalter** [comment] 2016-04-18 21:40
Do I understand this correctly then that unless #467 is resolved there is no way to prevent verbatim text like [this](http://oliver.bestwalter.de/mau-mau/) (log output) being randomly highlighted with the default settings and any of the themes MkDocs ships with? Or is there something obvious that I (as a new user) am missing?

**Comment by waylan** [comment] 2016-04-18 22:08
Per my [comments][1] on #467 you may be able to use a Markdown extension to trick things into working the way you want. Outside of that, yes #467 is it.

[1]: https://github.com/mkdocs/mkdocs/issues/467#issuecomment-211391352

**Comment by obestwalter** [comment] 2016-04-18 22:22
o.k. thanks for the clarification.

**Comment by astorm** [comment] 2019-07-20 16:58
@obestwalter Hello from three plus years into the future!  Did you ever find a pragmatic fix for this at any (read the docs, mkdocs, or highlight.js) level?

**Comment by obestwalter** [comment] 2019-07-20 21:58
Using [material theme](https://squidfunk.github.io/mkdocs-material/) by  @squidfunk and explicitly declaring which highlighting you want in code blocks was basically what did the trick for me.

**Comment by astorm** [comment] 2019-07-20 22:30
Thank you @obestwalter! I wasn't aware of that theme and it looks pretty nice. 

Also for anyone coming along later I ended up dropping an `extra.css` file into the docs folder with rules like this

```
code.plaintext span.hljs-keyword,
code.plaintext span.hljs-symbol,
code.plaintext span.hljs-string
{
    font-weight:normal;
    color:black;
}
```

Not ideal, but it worked.  Annoying that highlight.js doesn't let you turn off its auto detection (or does it but MkDocs doesn't expose that?  ¯\_(ツ)_/¯)
