### ISSUE TITLE
Autogen title mismatch

### ISSUE THREAD

**Issue by zingdle** [mkdocs/mkdocs#1510] opened 2018-06-15 02:05 UTC
```
$ mkdocs --version
mkdocs, version 0.17.4
```

To reproduce the issue:
1. Start a new mkdocs project
2. In `docs/test.md`:
```
# Something Else
```
3.  mkdocs serve
4. When you at `http://127.0.0.1:8000`, the title is `Test`. When you at `http://127.0.0.1:8000/test`, the title is `Something Else`. I think the latter should be the correct one.

**Comment by waylan** [comment] 2018-06-17 00:11
This is a duplicate of #1347.

**Closed by waylan** 2018-06-17 00:11 UTC
