### ISSUE TITLE
Search stuck on Initializing search

### ISSUE THREAD

**Issue by lyz-code** [mkdocs/mkdocs#2869] opened 2022-06-20 15:19 UTC
Hi, suddenly the search functionality has stopped working. It's stuck in `Initializing search` and the browser's console log shows the next error:

```
TypeError: o is null                           search.85cb4492.min.js:46:2958
```

Relevant data:

* Mkdocs version: 1.3.0
* Mkdocs theme: mkdocs-material 8.3.6
* Hosted on: Github pages

# Steps to reproduce

* Visit https://lyz-code.github.io/blue-book/
* Click on the search bar and type `python`

Instead I'd expect the results to be shown as they were before

# Steps to reproduce locally

```bash
git clone https://github.com/lyz-code/blue-book
cd blue-book
virtualenv env
source env/bin/activate
pip install --user pdm
make install
make docs
```

* Visit http://localhost:8000/blue-book/
* Click on the search bar and type `python`

# Further information

Another friend's search bar is also broken, but the error is different:

```
TypeError: o.flatMap is not a function                   search.85cb4492.min.js:46:2967
```

You can see it following the same steps but on https://m0wer.github.io/memento/

Do you know what may be happening?

Thanks

**Comment by little-bear-creator** [comment] 2022-06-21 14:23
I have the same problem, I can't use the searchbar either and my configuration is as follow : 
- mkdocs_material-8.3.6
- mkdocs-1.3.0
- Hosted : Gitlab Pages 
- Builded with : private gitlab-runner 14.7 using Docker version 20.10.17 with Python 3.10.5 and pip 22.0.4

I hope those information can help resolving this issue, my website is private so I can't really share its link or open an issue. I've reproduced the same execution on my personnal computer and the search bar still doesn't work.

_If this is not the right place for my comment I will delete it, thanks_

**Comment by squidfunk** [comment] 2022-06-22 05:51
This is a problem with [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/), not MkDocs, which I just fixed in and squidfunk/mkdocs-material@e3ce3dbc2, and which is going to be released as part of 8.3.7 in a few minutes. Since this is the wrong place, this issue can be closed.

**Closed by squidfunk** 2022-06-22 05:51 UTC

**Comment by lyz-code** [comment] 2022-06-22 11:15
Thanks for the quick fix @squidfunk, it doesn't work for me though. I've updated mkdocs-material to 8.3.7 and now I get this console error:

```
index.ts:209 Uncaught (in promise) TypeError: Cannot read property 'reduce' of null
    at extractor (index.ts:209)
    at t.Builder.add (lunr.js:2478)
    at t.Builder.<anonymous> (index.ts:217)
    at t (lunr.js:53)
    at new U (index.ts:177)
    at index.ts:146
    at Generator.next (<anonymous>)
    at s (search.b97dbffb.min.js:1)
```

You can see it in https://lyz-code.github.io/blue-book/

Do you want me to open an issue in your repo? or we can continue here?

**Comment by squidfunk** [comment] 2022-06-22 15:11
Yes, please create an issue with a _minimal_ reproducible example.

**Comment by lyz-code** [comment] 2022-06-23 08:24
Thanks again for the quick fix, can't wait to test it with the next release

**Comment by squidfunk** [comment] 2022-06-24 23:05
8.3.8 is out, including the fix.
