### ISSUE TITLE
Order dependent anchor url(e.g. #_1, #_2) for non-English headers isn't useful

### ISSUE THREAD

**Issue by hozumi** [mkdocs/mkdocs#762] opened 2015-11-23 13:35 UTC
When I write documents in Japanese, mkdocs generate order dependent anchor url(e.g. #_1, #_2) pointing to non-English headers.
This makes references of the headers unuseful, because I must maintain reference links whenever order of headers are change.
GIthub's markdown seems to be able to handle non-English headers nicely.
https://gist.github.com/hozumi/45b8d5eaff88038079bb#テスト
As table of links to headers is one of reason I want to use mkdocs, I hope mkdocs can generate anchor url for non-English headers as Github's markdown.

**Comment by waylan** [comment] 2015-11-23 14:03
The anchors are not generated directly by MkDocs, they are generated by the [TOC][1] extension for Python-Markdown. You could create your own extension which generates anchors in whichever way you want. However, it is simpler than that. The TOC extension already includes support for passing it a ['slugify'][2] function which can return whatever format you want for your anchors. Just make sure your function is importable on your PYTHONPATH. Then, in your MkDocs config file, you just need to tell Python-Markdown about it:

```yaml
markdown_extensions:
    tox:
        slugify: !!python/object:import.path.to.func
```

Note that you will need to replace `import.path.to.func` with the actual import path. For example, if you would do `from foo.bar import slugify` (when importing in Python code) then it would be `!!python/object:foo.bar.slugify`.

[1]: https://pythonhosted.org/Markdown/extensions/toc.html
[2]: https://pythonhosted.org/Markdown/extensions/toc.html#usage

**Comment by hozumi** [comment] 2015-11-23 14:52
Hi waylan,
Thanks for helpful explanation.
I will try to write my slugify.
Although writing custom slugify solve this problem, I think that default slugify which behaves as Github's one will be prefereble for all users, because behavior of Github's seems not to break current default slugify for English headers.

**Comment by waylan** [comment] 2015-11-23 15:06
Whether MkDocs provides a different default `slugify` is outside my control. 

However, as the developer of Python-Markdown (and the TOC extension) I can tell you that the default TOC `slugify` will not be changing. There are potentially thousands of documents out there which are using the current behavior. If the default would change, there is the potential that many existing links all across the internet would suddenly be broken. For that reason, we will always keep the existing behavior as the default, but provide a means to override it to fit various other use cases.

**Comment by hozumi** [comment] 2015-11-23 16:01
> If the default would change, there is the potential that many existing links all across the internet would suddenly be broken.

I see.
I think non-English MkDocs users(including me) hope to change only the default behavior of MkDocs, not Python-Markdown.(The fact that MkDocs use Python-Markdown is just a implementation detail.)
A practical and easy way may be that MkDocs internally set up the default value of `markdown_extensions: tox: slugify: in mkdocs.yml` to be customed one.
Anyway, if changing the default slugify is difficult, it's ok.
I appreciate your help. Thank you!

**Comment by waylan** [comment] 2015-11-23 16:30
@hozumi I would suggest you take a look at #212. That provides MkDocs' position on the matter and also a link to [awesome slugify]( https://github.com/dimka665/awesome-slugify) and whether it makes sense to make that MkDocs' default.

Actually, this issue is probably a duplicate of #212.

**Comment by hozumi** [comment] 2015-11-23 17:25
> I would suggest you take a look at #212.
I will look at it later. Thanks.

Currently I'm writing a custom slugify, and got the following error.
`TypeError: slugify() missing 2 required positional arguments: 'value' and 'separator'`
stack trace and details: https://gist.github.com/hozumi/7669e5d8466a5013cd02

Is there something wrong my code?

**Comment by waylan** [comment] 2015-11-23 18:04
Oh, I'm sorry. It should be `!!python/name:myslugify.slugify` Note the use of "name" rather than "object". That was my mistake.

**Comment by hozumi** [comment] 2015-11-23 18:19
I've changed the value to `!!python/name:myslugify.slugify` , and got the another error.

```
% PYTHONPATH=. mkdocs build
ERROR   -  Config value: 'markdown_extensions'. Error: Invalid Markdown Extensions configuration 

Aborted with 1 Configuration Errors!
```

**Comment by waylan** [comment] 2015-11-23 18:23
Sorry, another typo in my example config: Replace "tox" with "toc".

**Comment by hozumi** [comment] 2015-11-23 18:50
I've replaced "tox" with "- toc" and slugify works as expected!
```
markdown_extensions:
   - toc:
        slugify: !!python/name:myslugify.slugify
```

Thank you!

**Comment by hozumi** [comment] 2015-11-23 18:58
For future readers, my implementation of slugify is here: https://gist.github.com/hozumi/855fa8d42aef15b88829

**Comment by waylan** [comment] 2016-03-31 20:11
I'm closing this as there is currently no actionable item here.

**Closed by waylan** 2016-03-31 20:11 UTC
