### ISSUE TITLE
Feature Request: Support GitLab Static Site Editor

### ISSUE THREAD

**Issue by chrispoupart** [mkdocs/mkdocs#2212] opened 2020-10-21 14:36 UTC
Currently, [GitLab only supports Middleman](https://docs.gitlab.com/ee/user/project/static_site_editor/) in their current implementation, however there is nothing that would prevent mkdocs from leveraging the functionality.

The GitLab Static Site Editor (SSE) gives the user a WYSIWYG editor by default (though the user can switch to Markdown/text), and returns the user to the webpage they were on once they have committed their changes. This makes a much nicer user experience, particularly for non-technical users.

## Requirements

Currently, the default value for `edit_uri` in mkdocs for GitLab is the same as the one for GitHub.  This would need to be changed as the path for the Static Site Editor in GitLab is different and takes the following format:

Current default: `edit/master/docs/`
New string to leverage GitLab SSE: `{repo_url}/-/sse/master%2Fdocs%2F{filename.md}/?return_url={site_url}/{page}`

You can see an example of the way it works with Middleman here:

https://chrispoupart.gitlab.io/static-site-editor-middleman/

**Comment by waylan** [comment] 2020-10-28 13:47
This is related to #1378. I would suggest adding a comment to that issue which defines GitLab's URL structure and then closing this issue. That way we won't forget about GitLab if/when we refactor how `edit_uri` works.

**Comment by oprypin** [comment] 2022-08-13 12:53
Duplicate of #1378 - will be handled there

**Closed by oprypin** 2022-08-13 12:53 UTC
Labels: Enhancement

**Comment by oprypin** [comment] 2022-08-13 13:14
Check out the new proposal https://github.com/mkdocs/mkdocs/issues/1378#issuecomment-1214158134
