### ISSUE TITLE
Use title.title() instead of title.capitalize() when auto generating navigation?

### ISSUE THREAD

**Issue by FISHMANPET** [mkdocs/mkdocs#2207] opened 2020-10-13 22:21 UTC
I've seen some reluctance to change anything with auto-generation, though I'm wondering if you'd be open to a small tweak:
In the section where folder names are turned into titles, it's using `.capitalize()` which only capitalizes the first letter.  There's also a `.title()` method that will capitalize every word.

https://github.com/mkdocs/mkdocs/blob/ff0b7260564e65b6547fd41753ec971e4237823b/mkdocs/utils/__init__.py#L335-L337

Under the current scheme, the folder `user-guide` would turn into `User guide` but if it used `.title()` it would turn the folder into `User Guide`.

It's already possible to "force" this behavior by including capitalization in the folder name `User-Guide` and it might be disruptive for the behavior to suddenly change, so it may not be worth making this change.  I searched to see any discussion of this specifically and couldn't find it, so I thought I'd propose it.  I'm guessing the odds of making this change are low, but I also wanted to put it out here just in case anyone else searches for it in the future, so they can see an answer one way or the other.

**Comment by waylan** [comment] 2020-10-28 13:37
This is a duplicate of #2086.

**Closed by waylan** 2020-10-28 13:37 UTC
