### ISSUE TITLE
Cross platform path handling problems.

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#439] opened 2015-04-09 06:37 UTC
There is some wonky path handling in MkDocs. We need to fix it to make it consistent and work reliably.

**Comment by d0ugal** [comment] 2015-04-09 12:35
After having some issues I wasn't able to reproduce this.

**Comment by d0ugal** [comment] 2015-04-09 15:57
Not able to reproduce.

**Comment by waylan** [comment] 2015-04-09 20:33
I think I might know why these types of errors keep getting reported but then can't be reproduced. I was reading through the code and noticed multiple instances in which a path is checked for `posixpath.sep` (ex: `if posixpath.sep in path` in `mkdocs.nav._generate_site_navigation` to determine nested pages--the issue reported here). The problem is that `posixpath.sep` returns the path separator for the specific system. However, if any config values use the separator for a different system, then this will fail when it should not. 

Note that the same config should work on multiple systems. For example, I create a project on Linux. However, a second individual working the same project uses Windows and a third uses OSX. Requiring that the config setting be changed/edited for each system is a non-starter. I expect that you could reproduce the reported bug by listing all pages in the config using Linux  separators (including nested pages) and then try to build on Windows (or use Windows separators and build on Linux). Of course, an auto-generated list of pages would not reproduce the problem as that list would always contain the correct separators for that system (I'm guessing the failed attempts to reproduce are using an auto-generated list of pages--if only a reporter could provide us with a failing project--none of them seem to be public).

I see two options:

1. Require that all paths in the config use a pre-chosen separator (regardless of system). Probably a forward slash (`"/"`) as that is also the separator used in the resulting urls. However, all auto-generated paths (ex.: list of pages generated from walking the doc_dir) will need to have their paths normalized to use that separator rather than the system separator. You would also need to create an alternate for `os.path.join` and friends that uses the hard-coded separator. And finally,  you should normalize back to the system default just before each read. Although Python usually does the right thing without that last step, its better to be sure.

2. Allow either type of path separator in the config and normalize all paths to the system default at run time. Essentially, this means calling `os.path.normpath` on every path in the config. I realize that some config values ('site_dir' and 'docs_dir') are validated in `mkdocs.config.validate.config` (`os.path.abspath` calls `os.path.normpath` internally), but not all paths. For example, each list of paths (pages, extra_css, extra_javascript, ...) would need to be looped through so that every path could be normalized. 

Personally, I would think option 2 makes the most sense.

**Comment by d0ugal** [comment] 2015-04-09 20:45
(I'm actually fairly sure the issue is something to do with live reload in this case and when I switched branches, something went wrong. When I done a clean install of mkdocs it worked fine.)

However, I've been coming to a similar conclusion, the path handling has been slowly getting better for end users, but messier in the code as it was never really fixed at the root of the problem. I also agree that option two is the best.

I don't think normpath does everything that we need however, I looked into this. From the Python docs:

    Normalize a pathname by collapsing redundant separators and up-
    level references so that A//B, A/B/, A/./B and A/foo/../B all
    become A/B. This string manipulation may change the meaning of a
    path that contains symbolic links. On Windows, it converts
    forward slashes to backward slashes. To normalize case, use
    normcase().

So, given that slashes are only converted on Windows, then a windows config wont work on Linux etc.

**Comment by d0ugal** [comment] 2015-04-09 20:46
Updated and reopened the issue as this is something I really need to work on in general.

**Comment by d0ugal** [comment] 2015-04-09 20:46
I'm fairly sure #306 is related too.

**Comment by d0ugal** [comment] 2015-04-09 21:47
I've just tried experimenting a bit. Things get a bit confusing. Take for example `extra_css`. This is automatically determined based on CSS files found in the `docs_dir`. We then use this in two places:

- Inserting into HTML
- When copying the CSS files from the `docs_dir` to the `site_dir`

The first always needs forward slashes and the second needs to match the current OS. So, if we use something like normpath on the files in the config, do we then explicitly convert them back for one of the above?

**Comment by waylan** [comment] 2015-04-10 02:28
To be clear, I haven't done a complete audit of the code (or anything near to one), but I am certain that the code in its current state fails in some edge cases. Finding those is the hard part. However, I expect that defining and implementing a policy would allow you to skip that part. My inclination is to make it an internal policy that every path MUST be normalized to the system and every path added to a template context MUST be normalized to a URL.  I expect the second part can be accomplished with:

```python
def path_to_url(path):
    """Convert a system path to a URL."""
    if os.sep == '/':
        return path
    else:
        return path.replace(os.sep, '/')
```

As for the first part, I would suggest documenting that if users want their projects to work cross-platform then they need to use forward slashes in all their paths in their config files (Linux and OSX users will be anyway). As paths with forward slashes can always be normalized properly to any system, the users don't even need to be aware of the internal policy. 

And for those Windows users who ignore the documentation and don't use forward slashes in their config, it will still work for them as long as they stay on Windows. When and if they venture onto other systems, their failure to follow the documentation would be user error and resolved by following that piece of documentation.

**Closed** 2015-04-13 22:30 UTC
Labels: Bug

**Comment by abrlake** [comment] 2025-11-12 22:18
On Windows, Python treats backslashes as escape characters (`\t`, `\n`, etc.), 
so copying a path directly from Explorer can cause weird results like tabs showing up.  

You can either use a raw string like `r"D:\testfolder"` or normalize the path automatically.

If you want a one-liner that also cleans `../` and expands `~` for cross-platform use, 
you can try this tiny utility I wrote called [ipathy](https://pypi.org/project/ipathy/):

```python
from ipathy import ipathy
print(ipathy("D:\\testfolder"))
# → D:/testfolder
