### ISSUE TITLE
MKDocs won't deploy anymore on gitlab pages

### ISSUE THREAD

**Issue by florianmonfort** [mkdocs/mkdocs#1535] opened 2018-07-06 05:26 UTC
Hi all,

Since a few commits on gitlab pages where we've installed MKDocs it won't build anymore.

The curious thing is we made no change to any config file, only one file for a markdown page was changed and there is nothing wrong with it, only the content changed.

So we have no idea what's going on or what the error really means, are you guys able to pin point what we may have done wrong?

![image](https://user-images.githubusercontent.com/1446429/42361278-33feb1e0-8120-11e8-95f7-84d7a3bff879.png)

**Comment by Viatorus** [comment] 2018-07-06 08:12
Here is a log:
https://gitlab.com/snippets/1730494

Same issue for me since version 0.17.4. :(

**Comment by waylan** [comment] 2018-07-06 12:48
This is another duplicate of #1518.

**Closed by waylan** 2018-07-06 12:48 UTC

**Comment by waylan** [comment] 2018-07-06 14:41
Version 0.17.5 is now available with the fix in #1536.

**Comment by florianmonfort** [comment] 2018-07-09 02:18
Thank you guys for your help! It worked!
