### ISSUE TITLE
A old problem has re-occured

### ISSUE THREAD

**Issue by forestbat** [mkdocs/mkdocs#2877] opened 2022-07-01 18:03 UTC
I want to generate docs on readthedocs，however it crashed and tell me：

```
Traceback (most recent call last):
  File "/home/docs/.asdf/installs/python/3.9.13/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/docs/.asdf/installs/python/3.9.13/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/waterdoc/envs/latest/lib/python3.9/site-packages/mkdocs/__main__.py", line 14, in <module>
    from mkdocs import config
  File "/home/docs/checkouts/readthedocs.org/user_builds/waterdoc/envs/latest/lib/python3.9/site-packages/mkdocs/config/__init__.py", line 2, in <module>
    from mkdocs.config.defaults import DEFAULT_SCHEMA
  File "/home/docs/checkouts/readthedocs.org/user_builds/waterdoc/envs/latest/lib/python3.9/site-packages/mkdocs/config/defaults.py", line 4, in <module>
    from mkdocs.config import config_options
  File "/home/docs/checkouts/readthedocs.org/user_builds/waterdoc/envs/latest/lib/python3.9/site-packages/mkdocs/config/config_options.py", line 8, in <module>
    from mkdocs import utils, theme, plugins
  File "/home/docs/checkouts/readthedocs.org/user_builds/waterdoc/envs/latest/lib/python3.9/site-packages/mkdocs/theme.py", line 9, in <module>
    from mkdocs.utils import filters
  File "/home/docs/checkouts/readthedocs.org/user_builds/waterdoc/envs/latest/lib/python3.9/site-packages/mkdocs/utils/filters.py", line 11, in <module>
    @jinja2.contextfilter
AttributeError: module 'jinja2' has no attribute 'contextfilter'
```

I saw [this issue](https://github.com/mkdocs/mkdocs/issues/2799) and change mkdocs-material to 8.2.7 in my requirement.txt，however it still crashed like this，how to solve it？

**Comment by oprypin** [comment] 2022-07-01 19:09
Duplicate of #2799

**Closed by oprypin** 2022-07-01 19:09 UTC
