### ISSUE TITLE
Relative paths in sub-directory - shouldn't they get converted to absolute on build?

### ISSUE THREAD

**Issue by ivanz** [mkdocs/mkdocs#653] opened 2015-06-25 11:03 UTC
Given the following directory and file structure:

```
│   index.md
│
└───Section
    │   section.md
    │
    ├───files
    │       test.zip
    │
    └───images
            image.jpg
```

I expect that in `section.md` when I use: 

`![Image alt text](images/image.jpg)`

It will generate: `/Section/images/image.jpg`

However instead it generates: `../../images/image.jpg`

I would expect to see `../../images/image.jpg` generated only if I were doing `![ (/images/image.jpg)`

**Comment by d0ugal** [comment] 2015-06-25 11:25
Yeah, that is annoying. I've been meaning to look into this.

**Comment by waylan** [comment] 2015-06-25 12:40
I suspect this is a duplicate of #192. 

Also see [my comment][1] for an explanation of why all internal paths **must** be relative.

[1]: https://github.com/mkdocs/mkdocs/issues/192#issuecomment-75322787

**Comment by ivanz** [comment] 2015-06-25 12:53
Well my issue is that I want me and my team to be able to use an editor such as MarkdownPad for editing documentation and for this we want to use relative paths in markdown, so that we get to get preview of the images/diagrams in the editor (otherwise it wouldn't know what the root "/" is if absolute paths are used)

The changes in pull request #654 fix this for me but break one test. :(

**Comment by d0ugal** [comment] 2016-01-15 09:37
Closing in favour of #192.

**Closed by d0ugal** 2016-01-15 09:37 UTC
Labels: Bug
