### ISSUE TITLE
changing a file.md is not reflected on livereload output (mkdocs does not rebuild?)

### ISSUE THREAD

**Issue by angeloneacsu** [mkdocs/mkdocs#1176] opened 2017-03-21 23:00 UTC
I try to modify some documentation file (ex agenda.md) 
After saving the file, livereload is triggered (or F5-refresh on browser), but the output remains the same. I have to restart the "mkdocs serve" process (in my case restarting a fresh docker container) for the output to be reflected correctly.
It worked ok until 2 or 3 days ago

Personaly I use a docker image built by me as follow:

---- Dockerfile ----
FROM alpine:latest
RUN apk update
RUN apk add python curl
RUN curl -L https://bootstrap.pypa.io/get-pip.py | python -
RUN pip install -U pip
RUN pip install -U mkdocs
RUN pip install -U mkdocs-material
RUN pip install -U mkdocs-cinder
RUN pip install -U mkdocs-bootstrap
RUN pip install -U pymdown-extensions

VOLUME /server
WORKDIR /server
EXPOSE 8001

CMD ["mkdocs", "serve", "--dev-addr=0.0.0.0:8001"]

---- Building Docker image ----
docker build -t mymkdocs .

---- Running Container ----
docker run -it --rm -v $PWD/server:/server -p 8001:8001 mymkdocs

---- My /server dir ----
docs  mkdocs.yml

---- My mkdocs.yml ----
site_name: My Documents
theme: 'material'
markdown_extensions:
  - toc(permalink=true)
  - admonition
  - meta
pages:
    - Home: index.md
    - Agenda: agenda.md

**Comment by waylan** [comment] 2017-03-21 23:26
This is a duplicate of #1174 which will be available in the next release.

**Closed by waylan** 2017-03-21 23:26 UTC
