### ISSUE TITLE
Custom file sort order

### ISSUE THREAD

**Issue by csm10495** [mkdocs/mkdocs#1210] opened 2017-04-14 00:29 UTC
I have a bunch of pages in a folder named like so: 1.md, 2.md... 1000.md. They seem to be sorting alphabetically as opposed to numerically. In the dropdown the pages come up with 100.md before 2'md. Is there a hook I can use to manually change the sort order, without changing the actual raw makedocs code? Thanks!

**Comment by waylan** [comment] 2017-04-14 01:21
This is a duplicate of #714.

**Closed by waylan** 2017-04-14 01:21 UTC
