### ISSUE TITLE
Configuration strict option not checking broken links

### ISSUE THREAD

**Issue by timorjim** [mkdocs/mkdocs#738] opened 2015-10-13 12:32 UTC
I was testing mkdocs earlier this year and was using "strict: true" in my mkdocs.yml. If I recall correctly, it was working then and building would break if there was a broken link in the .md.

However I am now using v0.14.0 and this config option seems to have no effect on the build - I get no warnings or errors when building regardless of the value of strict.

**Comment by d0ugal** [comment] 2016-02-22 09:38
Sorry, this one got lost somewhere along the way. This feature is working for me. We would need debug help - have you tried the most recent version? do you get any errors? what python version and OS are you running?

I'll close this now as it is so old and seems to be working, but happy for a new issue to be opened or I'll reopen this one.

**Comment by nguillaumin** [comment] 2016-08-03 17:00
I think I'm seeing a similar issue. I'm getting a warning, but the build is not halted as the doco says it should.

I'm using MkDocs 0.15.3, Python 3.5.2. My YML file is:

```yaml
site_name: Documentation
theme_dir: 'fb_theme'
copyright: 'Copyright © 2016'
strict: true
extra:
# REDACTED
```

When I run `mkdocs serve`:

```
INFO    -  Building documentation... 
DEBUG   -  Loading configuration file: REDACTED/mkdocs.yml 
DEBUG   -  Config value: 'site_author' = None 
DEBUG   -  Config value: 'site_description' = None 
DEBUG   -  Config value: 'include_nav' = True 
DEBUG   -  Config value: 'site_url' = None 
DEBUG   -  Config value: 'google_analytics' = None 
DEBUG   -  Config value: 'include_next_prev' = True 
DEBUG   -  Config value: 'mdx_configs' = {} 
DEBUG   -  Config value: 'site_dir' = 'REDACTED/site' 
DEBUG   -  Config value: 'mkdocs_templates' = '/usr/lib/python3.5/site-packages/mkdocs/templates' 
DEBUG   -  Config value: 'theme_dir' = ['REDACTED/fb_theme', '/usr/lib/python3.5/site-packages/mkdocs/assets/search'] 
DEBUG   -  Config value: 'use_directory_urls' = True 
DEBUG   -  Config value: 'repo_url' = None 
DEBUG   -  Config value: 'strict' = False 
DEBUG   -  Config value: 'pages' = ['index.md', {

[...] (too many pages)

DEBUG   -  Config value: 'markdown_extensions' = ['meta', 'toc', 'tables', 'fenced_code'] 
DEBUG   -  Config value: 'extra_templates' = [] 
DEBUG   -  Config value: 'config_file_path' = 'REDACTED/mkdocs.yml' 
DEBUG   -  Config value: 'theme' = 'mkdocs' 
DEBUG   -  Config value: 'dev_addr' = '127.0.0.1:8000' 
DEBUG   -  Config value: 'repo_name' = None 
DEBUG   -  Config value: 'site_favicon' = None 
DEBUG   -  Config value: 'extra_css' = [] 
DEBUG   -  Config value: 'site_name' = 'Documentation' 
DEBUG   -  Config value: 'docs_dir' = 'REDACTED/docs' 
DEBUG   -  Config value: 'extra_javascript' = [] 
DEBUG   -  Config value: 'remote_branch' = 'gh-pages' 
DEBUG   -  Config value: 'copyright' = 'Copyright © 2016' 
DEBUG   -  Config value: 'remote_name' = 'origin' 
DEBUG   -  Config value: 'extra' = redacted
INFO    -  Cleaning site directory 
DEBUG   -  Copying static assets from theme: /usr/lib/python3.5/site-packages/mkdocs/assets/search 
DEBUG   -  Copying static assets from theme: REDACTED/fb_theme 
DEBUG   -  Copying static assets from the docs dir. 
DEBUG   -  Building markdown pages. 
DEBUG   -  Building template: 404.html 
DEBUG   -  Building template: search.html 
DEBUG   -  Search is enabled but the theme doesn't contain a search.html file. Assuming the theme implements search within a modal. 
DEBUG   -  Building template: sitemap.xml 
DEBUG   -  Building extra_templates page 
DEBUG   -  Building page index.md 
WARNING -  The page "index.md" contained a hyperlink to "Something.md" which is not listed in the "pages" configuration. 
DEBUG   -  Building page administer/administer-introduction.md 
DEBUG   -  Building page administer/diagnostics/download-support-package.md 
DEBUG   -  Building page administer/diagnostics/system-diagnostic.md 
...
```

I get the warning, but the build continues.

**Comment by nguillaumin** [comment] 2016-08-03 18:03
Hm, it works with `mkdocs build` though, so I guess this is expected for `serve` to not halt the build? If that's the case please disregard my comment.

**Comment by nguillaumin** [comment] 2016-08-03 18:25
Erm... ok so, actually, it doesn't work :wink: 
* Setting `strict: true` in `mkdocs.yml` does NOT halt the build on broken links
* Using `mkdocs build -s` does

**Comment by waylan** [comment] 2016-08-03 19:03
> * Setting `strict: true` in `mkdocs.yml` does NOT halt the build on broken links
> * Using `mkdocs build -s` does

@nguillaumin thanks for the clear report. I can confirm that I get the same behavior and am reopening this issue. 

BTW, I also noticed that this only applies to `*.md` internal links. For example, when testing this, I noticed that the `index.md` file in MkDocs documentation contains links to both `user-guide/deploying-your-docs/` and `user-guide/deploying-your-docs.md` (which in itself, is a separate issue in need to fixing -- see mivok/markdownlint#137). The former does not raise a warning and the later does when the links are altered to be inaccurate (when testing I removed the final dash: `user-guide/deploying-yourdocs/` and `user-guide/deploying-yourdocs.md`).

**Comment by waylan** [comment] 2016-08-03 19:52
Ahh, when the `--strict` flag is not included, then is evaluates to `False` and is passed in by the CLI overriding the value in the config file. Of course, when if the flag is included, it evaluated to `True` and no problem occurs. So we need to not pass the `script` value to the config from the CLI if the flag is not `True`. Not sure if Click has a way to do that or if we need to special case it in the code

**Closed** 2016-08-04 19:02 UTC
Labels: Bug

**Comment by nguillaumin** [comment] 2016-08-04 21:37
Thanks! :trophy:

**Comment by fkromer** [comment] 2016-11-27 12:01
Does the link checking also work for external links?

I inserted a broken external link into the docs. I have set the config value `strict: True` in *mkdocs.yml* and run `mkdocs build` or `mkdocs serve` but the build does not break and also not warn or error about the link. I also tried `mkdocs build -s` and `mkdocs build --strict` (mkdocs 0.16.0) with the same result...

**Comment by waylan** [comment] 2016-11-27 21:41
@fkromer no, checking external links is beyond the scope of our validator. Perhaps that could be addressed as a Plugin when we implement the API (see #206).

**Comment by fkromer** [comment] 2016-11-27 21:51
@waylan a plugin API would be great!

**Comment by davidhrbac** [comment] 2017-02-03 12:32
@fkromer you can check external links with https://github.com/dkhamsing/awesome_bot like this:

```bash
find . -name '*.md' -exec grep -l http {} + | xargs awesome_bot -t 10 --allow-dupe --allow-redirect
```

**Comment by fkromer** [comment] 2017-02-03 13:07
@davidhrbac Thanks for that hint :+1:

**Comment by jaxxzer** [comment] 2019-02-11 21:04
I found https://github.com/magicmatatjahu/milv to be much better than awesome_bot. Here, it finds three broken internal links/anchors, where awesome_bot does not:
```
$ awesome_bot docs/application-information.md
> Checking links in docs/application-information.md
Links to check: 4
  1. http://www.ardusub.com
  2. http://www.ardsub.com
  3. https://discuss.bluerobotics.com
  4. https://github.com/bluerobotics/ping-viewer/issues
Checking URLs: ?→✓✓

Issues :-(
> Links
  1. [L17] 302 http://www.ardusub.com  → https://www.ardusub.com/
  2. [L18]  http://www.ardsub.com Failed to open TCP connection to www.ardsub.com:80 (getaddrinfo: Name or service not known)
> Dupes
  None ✓

Wrote results to ab-results-docs-application-information.md.json
Wrote filtered results to ab-results-docs-application-information.md-filtered.json
Wrote markdown table results to ab-results-docs-application-information.md-markdown-table.json
$ go/bin/milv -v docs/application-information.md
----- docs/application-information.md - status: false
- #application-software-information - status: true
- #device-model-and-firmware-information - status: true
- #header-buttons - status: true
- #aplication-log - status: false, message: The specified header doesn't exist in file
- #log-categories - status: true
- http://www.ardusub.com - status: true
- http://www.ardsub.com - status: false, message: Get http://www.ardsub.com: dial tcp: lookup www.ardsub.com on 127.0.1.1:53: no such host
- /replay-data - status: false, message: The specified file doesn't exist
- replyay-data - status: false, message: The specified file doesn't exist
- images/icons/lock.png - status: true
- images/icons/chat.png - status: true
- images/icons/report.png - status: true
- images/icons/settings.png - status: true

#################################################
#                     SUMMARY                   #
#################################################

+---------------------------------+-----------------------+--------------------------------+
|              FILE               |         LINK          |          DESCRIPTION           |
+---------------------------------+-----------------------+--------------------------------+
| docs/application-information.md | #aplication-log       | The specified header doesn't   |
|                                 |                       | exist in file                  |
+---------------------------------+-----------------------+--------------------------------+
| docs/application-information.md | http://www.ardsub.com | Get http://www.ardsub.com:     |
|                                 |                       | dial tcp: lookup               |
|                                 |                       | www.ardsub.com on              |
|                                 |                       | 127.0.1.1:53: no such host     |
+---------------------------------+-----------------------+--------------------------------+
| docs/application-information.md | /replay-data          | The specified file doesn't     |
|                                 |                       | exist                          |
+                                 +-----------------------+                                +
|                                 | replyay-data          |                                |
|                                 |                       |                                |
+---------------------------------+-----------------------+--------------------------------+
```
