### ISSUE TITLE
Unicode problem using gh-deploy

### ISSUE THREAD

**Issue by venusbb** [mkdocs/mkdocs#1297] opened 2017-09-29 08:51 UTC
Hi, I am trying to use gh-deploy with a fresh new installation and project of gh-deploy. However, I get the following errors: I am using mac. I have tried to install mkdocs using python 2 and 3 neither solve the problem. The project I deploy is just the fresh project created by using `mkdocs new`

  File "/usr/local/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mkdocs/__main__.py", line 213, in gh_deploy_command
    gh_deploy.gh_deploy(cfg, message=message, force=force)
  File "/usr/local/lib/python2.7/site-packages/mkdocs/commands/gh_deploy.py", line 54, in gh_deploy
    if not _is_cwd_git_repo():
  File "/usr/local/lib/python2.7/site-packages/mkdocs/commands/gh_deploy.py", line 16, in _is_cwd_git_repo
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 391, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 55: ordinal not in range(128)

**Comment by waylan** [comment] 2017-09-29 13:04
I’m not sure from the error message alone, but are you perhaps using any non-ASCII characters in your file names? Or anywhere else that is not the file contents?

**Comment by venusbb** [comment] 2017-09-29 13:06
No, I just used the default one. 
`mkdocs build` runs fine. It is just the gh-deploy that gives me error.

**Comment by waylan** [comment] 2017-09-29 13:27
Is the project publicly available so we could take a look at it?  Some non-ASCII text is causing the error and without knowing where it is it tough to fix.

**Comment by venusbb** [comment] 2017-09-29 13:28
Sure. It is here:-
https://github.com/alphagov/notifications-manuals

**Comment by waylan** [comment] 2017-10-31 15:07
Sorry for the delay. Finally got a chance to look at this. I can't seem to reproduce your error with your project. However, looking at the error you posted, it appears that the error occurs when we call out to a subprocess to determine if the current working directory (CWD) is in a git repo. My assumption is that the problem is due to some issue with how you local system is configured (perhaps part of the path to CWD uses Unicode chars). I'm curious what you get if you run the sub-command directly. From the same directory where you would run `mkdocs`, run this command `git rev-parse --is-inside-work-tree`. What's the result?

**Comment by waylan** [comment] 2017-10-31 17:07
I created this little test script to try to reproduce the error (saved as `in_repo.py` within a git repo's working tree:

```python
import subprocess

def f(cmd):
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    proc.communicate()
    return proc.wait() == 0

if __name__ == '__main__':
    print "Using Bytes..."
    print str(f([b'git', b'rev-parse', b'--is-inside-work-tree']))
    print "\nUsing Unicode..."
    print str(f([u'git', u'rev-parse', u'--is-inside-work-tree']))
```

The output I get on multiple systems is:

```sh
$ python in_repo.py
Using Bytes...
True

Using Unicode...
True
```

Running it outside of a git repo's working tree results in:

```sh
$ python in_repo.py
Using Bytes...
False

Using Unicode...
False
```

As you can see, no errors. I don't know any other way to test for this based upon the error being generated.

**Comment by waylan** [comment] 2018-02-06 20:16
Closing this as the problem cannot be reproduced. I assume the problem rests with a nonstandard configuration of the users local system.

**Closed by waylan** 2018-02-06 20:16 UTC
Labels: Needs confirmation, Needs information

**Comment by rjseymour66** [comment] 2019-02-24 15:47
I successfully deployed to github pages a week ago, no issues. I made some minor revisions to the docs today and received the following errors when entering `mkdocs gh-deploy`: 

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/mkdocs", line 10, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mkdocs/__main__.py", line 187, in gh_deploy_command
    gh_deploy.gh_deploy(cfg, message=message, force=force, ignore_version=ignore_version)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mkdocs/commands/gh_deploy.py", line 82, in gh_deploy
    if not _is_cwd_git_repo():
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mkdocs/commands/gh_deploy.py", line 18, in _is_cwd_git_repo
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1: ordinal not in range(128)`

I have not made any changes to my computer, to python, to anything. I started a new mkdocs project to test if I accidentally hit a wrong key, and I could not deploy to gh pages with that project. I received the same errors.

What can I do? I am not a developer, so I have no idea how to fix this error and have not done anything to cause it. Please help!
