### ISSUE TITLE
1.5.0 build issue

### ISSUE THREAD

**Issue by julienlavergne** [mkdocs/mkdocs#3310] opened 2023-07-27 03:52 UTC
I believe there is something wrong in latest version. Looks like the new syntax for extra_javascript is causing build error.

```
Traceback (most recent call last):
  File "/opt/tools/python/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/tools/python-3.11.4/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tools/python-3.11.4/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/tools/python-3.11.4/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tools/python-3.11.4/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tools/python-3.11.4/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tools/python-3.11.4/lib/python3.11/site-packages/mkdocs/__main__.py", line 286, in build_command
    build.build(cfg, dirty=not clean)
  File "/opt/tools/python-3.11.4/lib/python3.11/site-packages/mkdocs/commands/build.py", line 277, in build
    config = config.plugins.on_config(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tools/python-3.11.4/lib/python3.11/site-packages/mkdocs/plugins.py", line 527, in on_config
    return self.run_event('config', config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tools/python-3.11.4/lib/python3.11/site-packages/mkdocs/plugins.py", line 507, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tools/python-3.11.4/lib/python3.11/site-packages/mermaid2/plugin.py", line 196, in on_config
    if self.extra_mermaid_lib:
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tools/python-3.11.4/lib/python3.11/site-packages/mermaid2/plugin.py", line 102, in extra_mermaid_lib
    if  libname(lib) == 'mermaid':
        ^^^^^^^^^^^^
  File "/opt/tools/python-3.11.4/lib/python3.11/site-packages/mermaid2/util.py", line 29, in libname
    basename = os.path.basename(lib)
               ^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 142, in basename
TypeError: expected str, bytes or os.PathLike object, not ExtraScriptValue
```

in our mkdocs.yml

```
extra_javascript:
  - javascripts/mermaid.min.js
```

**Comment by julienlavergne** [comment] 2023-07-27 07:22
Closing, it is a plugin issue

**Comment by oprypin** [comment] 2023-07-27 07:42
Well it *is* caused by the 1.5.0 release. 
But yes, either the plugin gets updated or I do a small patch in MkDocs to try to avoid this problem

**Comment by ultrabug** [comment] 2023-07-27 11:57
Looks like `mermaid2` plugin expects a return value type that changed indeed... From a quick guess it looks like it would be harder to fix on mkdocs since this would incur lowering our new typing expectations.

Dunno about mermaid2 plugin, but I sure hope they're active and will adapt their code for a better support.

**Comment by facelessuser** [comment] 2023-07-27 13:04
It seems all they really need to do is check call `os.path.basename(lib.path)` when they have a `ExtraScriptValue` return. I assume all the new scripts are returned wrapped this way, but worse case, you would have to check the type.

**Comment by pawamoy** [comment] 2023-07-27 13:37
Tagging @fralau as I believe he maintains the mermaid2 plugin.

**Comment by fralau** [comment] 2023-07-27 15:37
Yes, this is fixed in the github repository. Deployment on pypi will come later.

**Closed** 2023-07-27 22:18 UTC

**Comment by oprypin** [comment] 2023-07-27 22:45
Indeed I did a small patch in MkDocs to avoid this problem, so feel free to just upgrade to MkDocs 1.5.1

**Comment by fralau** [comment] 2023-07-28 07:20
@oprypin I like it even better like that 😄.

**Comment by courtland** [comment] 2023-07-28 16:05
@oprypin thank you for the quick fix. I am now having an [issue](https://github.com/markmap/mkdocs-markmap/issues/49) with the `mkdocs-markmap` plugin. Is there any similar workaround that could be applied to mkdocs until the plugin maintainer can fix it?

**Comment by oprypin** [comment] 2023-07-28 17:11
@courtland Unfortunately that case doesn't have such a workaround. Sorry about the breakage

**Comment by courtland** [comment] 2023-07-31 15:39
> 

Thanks for checking anyways!
