### ISSUE TITLE
readthedocs gives no search results using `mkdocs serve`

### ISSUE THREAD

**Issue by Austinreedthomas** [mkdocs/mkdocs#2373] opened 2021-04-19 16:49 UTC
Using mkdocs version 1.1.2 and Python 3.7 running on a Windows box.  Our repo includes a README for providing mkdocs utilization for users. Our README is included in the mkdocs.yml file and when I try to use the 'readthedocs' search capability, it displays no results for a search query of `mkdocs` and hangs displaying "Searching..." forever.

**Comment by waylan** [comment] 2021-04-19 18:26
I'm not seeing this issue. You seem to be suggesting that the issue is unique to your README file. Does that mean it works fine for other pages? Can you provide more information about your README? Is the page properly being included in the built site? Where is the page located in relation to your `docs_dir`?

**Comment by Austinreedthomas** [comment] 2021-04-19 18:43
No I was just  giving an example of "the search should return something because mkdocs is referenced in the README" sorta thing. The README is properly included in the build site but no search queries of any kind of return
![Capture](https://user-images.githubusercontent.com/13165482/115286917-e34bb080-a10c-11eb-83d3-c44214645848.PNG)
.

**Comment by waylan** [comment] 2021-04-19 18:46
Again, I am not able to replicate the alleged behavior. In other words, search is working just fine for me. You're going to need to provide enough detail for us to replicate the issue.

**Comment by Austinreedthomas** [comment] 2021-04-19 18:49
Running Windows 10 using mkdocs v1.1.2, Python 3.7 and readthedocs theme. Running `mkdocs serve` locally from a gitbash terminal, navigating in a web browser (Edge) to 127.0.0.1:8000 and attempting to search for anything. The search just outputs "Searching..." (See above screenshot) and never returns results.

**Comment by Austinreedthomas** [comment] 2021-04-19 18:49
I'm not sure what other info I can provide to describe the situation?

**Comment by waylan** [comment] 2021-04-19 19:19
With all of those same parameters I can search just fine in a local instance of MkDocs' own documentation. I even made sure to checkout a copy of version 1.1.2 rather than the current development code. The one difference is that I have Python 3.8 installed on my Windows machine, although I don't see how that would make a difference here. 

Do you by chance have any other plugins enabled? As explained in the [documentation][1]:

> If the plugins config setting is defined in the `mkdocs.yml` config file, then any defaults (such as `search`) are ignored and you need to explicitly re-enable the defaults if you would like to continue using them:
> 
> ```yaml
> plugins:
>     - search
>     - your_other_plugin
> ```

If that is not it, then we may need to see a copy of your config file.

[1]: https://www.mkdocs.org/user-guide/configuration/#plugins

**Comment by waylan** [comment] 2021-04-19 23:12
In the future please refrain from posting screenshots of text files. Instead please post the actual text in a codeblock.

I don't see any reason why there would be a problem there. Although, I do find it very strange that you have so many non-page files listed in your nav. 

You specifically mention that search fails for terms which are only in the README. What about search for terms on any of the other pages?

**Comment by waylan** [comment] 2021-04-20 13:18
Which browser are you using. Are there any errors reported in the browser's dev tools?

**Comment by Austinreedthomas** [comment] 2021-04-20 15:19
Browsing using Edge. I think you're onto something. I'm getting these errors in the browser's console: 
![Capture](https://user-images.githubusercontent.com/13165482/115421803-86f29a80-a1b9-11eb-94e6-27d40ba65b64.PNG)

**Comment by waylan** [comment] 2021-04-20 15:36
This is a duplicate of #1790. Instructions are included there to fix the Windows configuration.

Sorry, I should have thought of this sooner. But is has been so long since I've encountered the issue myself that I completely forgot about it.

**Closed by waylan** 2021-04-20 15:37 UTC
Labels: Needs information
