### ISSUE TITLE
Run search only for query having 3 and more characters

### ISSUE THREAD

**Issue by davidhrbac** [mkdocs/mkdocs#1127] opened 2017-01-20 14:22 UTC
We have quite a large search_index.json - 2.2MB. The search is very slow. How can we limit the search to start only for queries having 3 and more characters?

**Comment by waylan** [comment] 2017-01-20 14:32
Is search slow all the time or only the first time after a new page is loaded?

If it is the former, then this is a duplicate of #859. If the latter, then this will likely be addressed by that issue anyway as I intend to do a complete refactor of search allowing users to customize the features available in the underlying library. The holdup is that search will be moved to a Plugin and we need to finish the Plugin API first (see #206). Either way, I'll leave this open to remind me to possibly include this as one of the config options.

**Comment by davidhrbac** [comment] 2017-01-20 16:47
@waylan the first is definitely slow. Anyway there's no point to let JS search the large base for single or two characters. It might return very large set (hundreds, even more). Thanks.

**Closed** 2018-03-06 00:42 UTC
Labels: Enhancement, Plugin
