### ISSUE TITLE
Possibility to justify text?

### ISSUE THREAD

**Issue by Falkor** [mkdocs/mkdocs#1355] opened 2017-11-23 23:08 UTC
Hi, 

Sorry for the naive question yet I could find the way to configure `mkdocs.yml` to always render a justified text alignment. 

I'm running Mkdocs 0.17.2.

**Comment by waylan** [comment] 2017-11-28 19:05
Presentation (layout, style, etc) is controlled by the theme. Specifically, text justification would be controlled by CSS rules defined in a theme (probably with the [text-align][2] and [text-justify][4] properties).  See the documentation on [theme customization][1] for how to override CSS defined in a  theme.

As this is not a bug report, I'm closing this. In the future please ask support questions on our [mailing list][3].

[1]: http://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme
[2]: https://css-tricks.com/almanac/properties/t/text-align/
[3]: https://groups.google.com/forum/#!forum/mkdocs
[4]: https://css-tricks.com/almanac/properties/t/text-justify/

**Closed by waylan** 2017-11-28 19:05 UTC
