### ISSUE TITLE
Getting unicode_literals __future__ import Errors

### ISSUE THREAD

**Issue by CrashyBang** [mkdocs/mkdocs#750] opened 2015-11-14 04:28 UTC
Running:
OS: Ubuntu 14.04 (64bit)
Python: 2.7.6
Mkdocs: 0.14.0

Receiving the following error whenever I run a command does not matter it is `--help` or `serve` etc... it still throws the error:

```bash
/usr/local/lib/python2.7/dist-packages/mkdocs/cli.py:86: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/local/lib/python2.7/dist-packages/mkdocs/cli.py:100: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/local/lib/python2.7/dist-packages/mkdocs/cli.py:125: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/local/lib/python2.7/dist-packages/mkdocs/cli.py:145: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/local/lib/python2.7/dist-packages/mkdocs/cli.py:176: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/local/lib/python2.7/dist-packages/mkdocs/cli.py:194: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
```

**Comment by waylan** [comment] 2015-11-14 04:39
First of all, that is a "warning" not an "error". The program should still run. The cause of the warning has already been addressed in #708 and will be available in the next release. In the meantime, you can ignore the warning. The issue which the warning addresses does not affect MkDocs. For more information see the discussion in #703.

**Closed** 2015-11-14 07:30 UTC
