### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'current_page' is undefined

### ISSUE THREAD

**Issue by IMTaqi** [mkdocs/mkdocs#266] opened 2014-12-03 07:09 UTC
I am using your mkdocs theme in my mkdcos project, and when i run this it shows following error: 

jinja2.exceptions.UndefinedError: 'current_page' is undefined.

I think code for this is in toc.html file in mkdocs theme.

**Comment by peter1000** [comment] 2015-03-12 12:50
**jinja2.exceptions.UndefinedError: 'meta' is undefined**

Copying themes `bootstrap` to project folder named: `mybootstrap`

only .yml entry

```
site_name: The website
theme_dir: 'mybootstrap'
```
ERROR

```
$ mkdocs serve
Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 9, in <module>
    load_entry_point('mkdocs==0.11.1', 'console_scripts', 'mkdocs')()
  File "/usr/lib/python3.4/site-packages/mkdocs-0.11.1-py3.4.egg/mkdocs/main.py", line 74, in run_main
    main(cmd, args=sys.argv[2:], options=dict(opts))
  File "/usr/lib/python3.4/site-packages/mkdocs-0.11.1-py3.4.egg/mkdocs/main.py", line 46, in main
    serve(config, options=options)
  File "/usr/lib/python3.4/site-packages/mkdocs-0.11.1-py3.4.egg/mkdocs/serve.py", line 85, in serve
    build(config, live_server=True)
  File "/usr/lib/python3.4/site-packages/mkdocs-0.11.1-py3.4.egg/mkdocs/build.py", line 223, in build
    build_pages(config)
  File "/usr/lib/python3.4/site-packages/mkdocs-0.11.1-py3.4.egg/mkdocs/build.py", line 155, in build_pages
    build_404(config, env, site_navigation)
  File "/usr/lib/python3.4/site-packages/mkdocs-0.11.1-py3.4.egg/mkdocs/build.py", line 142, in build_404
    output_content = template.render(global_context)
  File "/usr/lib/python3.4/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.4/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.4/site-packages/jinja2/_compat.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.4/site-packages/mkdocs-0.11.1-py3.4.egg/mkdocs/themes/mkdocs/404.html", line 1, in <module>
    {% extends "base.html" %}
  File "mybootstrap/base.html", line 48, in <module>
    <div class="col-md-9" role="main">{% include "content.html" %}</div>
  File "mybootstrap/content.html", line 1, in <module>
    {% if meta.source %}
  File "/usr/lib/python3.4/site-packages/jinja2/environment.py", line 397, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'meta' is undefined

```
Patch: https://github.com/tomchristie/mkdocs/pull/244 seems not to help for this case

**Comment by d0ugal** [comment] 2015-03-17 11:27
@peter1000 Can you report that as a new issue? Seems to be a different problem.

**Comment by peter1000** [comment] 2015-03-17 13:40
Done

**Comment by d0ugal** [comment] 2015-04-02 20:34
I believe this is now fixed in the latest master, please let me know if it isn't.

**Closed by d0ugal** 2015-04-02 20:34 UTC
Labels: Bug

**Comment by gsouf** [comment] 2016-03-26 11:45
Getting the issue with  0.15.3 (the one I grabbed from pip)  and @manuelbua workarround (``theme: ""``) does not work: 

```
INFO    -  Building documentation... 
ERROR   -  Config value: 'theme'. Error: Unrecognised theme ''. The available installed themesare:  

Aborted with 1 Configuration Errors!
```

**Comment by waylan** [comment] 2016-03-27 01:40
@gsouf I would suggest you open a new issue. The related code is completely different today than when this issue was opened. The discussion here is no longer relevant in any way. In your new issue, be sure to include the minimal steps to reproduce the error.
