### ISSUE TITLE
Wrapped Theme Headers Obscure Underlying Pages

### ISSUE THREAD

**Issue by ProfYaffle** [mkdocs/mkdocs#557] opened 2015-05-25 10:38 UTC
Compare these two - if you have too many words in your top-level menu, the whole text wraps and obscures the top of the page beneath. This is on 0.13.0-dev, all themes except readthedocs, although it was apparent on 0.12.0 as well:

Short text:

![nowrap](https://cloud.githubusercontent.com/assets/6093716/7795989/6edbdc18-02d2-11e5-9d08-45cb149f9253.png)

Long text:

![wrap](https://cloud.githubusercontent.com/assets/6093716/7795994/76629ecc-02d2-11e5-9dc8-94c468f5049f.png)

**Comment by d0ugal** [comment] 2015-05-25 10:40
Duplicate of https://github.com/mkdocs/mkdocs/issues/210

**Closed by d0ugal** 2015-05-25 10:40 UTC
