### ISSUE TITLE
ReadTheDocs theme - Current page not indented in TOC

### ISSUE THREAD

**Issue by tpluscode** [mkdocs/mkdocs#1071] opened 2016-10-12 12:11 UTC
I'm using version 0.15.3.

In the Read the Docs theme the TOC entries for currently opened sub-page aren't indented. The `li.toctree-l1.current a` link has an invalid CSS property

```
{
   padding-left: 1.618em -4px;
}
```

I think that padding should be equal to other pages on the same level. For me it is `padding: 0.4045em 2.427em`.

Same goes for the internal links (`li.toctree-l1.current li.toctree-l3 a`) which aren't indented enough.

See below, where **Answers** is a subpage of **Links**:
![not indented enough](http://i.imgur.com/Q7jsgy0.png)

**Comment by waylan** [comment] 2016-10-13 13:05
This appears to be a duplicate of #888, which fix will be available in the next release (0.16).

**Comment by tpluscode** [comment] 2016-10-14 10:31
I see. I'd like to keep this open until 0.16 is live.

Also, I think there's a related problem with selecting top-level page. The page title (`li.toctree-l1.current a`) gets moved to the right. The `padding: 0.4045em 2.427em;` style seems redundant.

**Comment by waylan** [comment] 2016-10-14 12:50
> Also, I think there's a related problem with selecting top-level page. The page title (`li.toctree-l1.current a`) gets moved to the right. The padding: `0.4045em 2.427em;` style seems redundant.

Please feel free to submit a pull request.

**Comment by waylan** [comment] 2016-10-14 13:25
> I'd like to keep this open until 0.16 is live.

The issue is fixed, so it gets closed.

I considered keeping it open for the other issue you raised, but as per [this comment][1] I'm closing it as a duplicate of #588.

[1]: https://github.com/mkdocs/mkdocs/issues/1073#issuecomment-253797443

**Closed by waylan** 2016-10-14 13:25 UTC
