### ISSUE TITLE
Reloading does not affect the changes after changing the docs.

### ISSUE THREAD

**Issue by tonytomov** [mkdocs/mkdocs#1178] opened 2017-03-23 10:05 UTC
Using the last version (0.16.2) reloading does not change the content when new changes are committed to the doc file.

To reproduce:

- Start the mkdocs ( mkdocs serve)
- Open a file, make changes to it. Save the changes.

In the command line we see the reload, but the content is not changed in the browser.
In the previous version this work as expected - i.e the changes are displayed in the browser.

Regards

**Comment by waylan** [comment] 2017-03-23 12:35
This is the third duplicate of #1174, which fix will be avaialbe in the next release.

**Closed** 2017-03-23 12:36 UTC
