### ISSUE TITLE
unstyled <table> w/ RTD theme, due to lacking class=docutils

### ISSUE THREAD

**Issue by prof-milki** [mkdocs/mkdocs#2273] opened 2020-12-28 17:23 UTC
Bug report should probably go to wherever the mkdocs markdown plugin lives.

Anyway, it seems generated markdown `<table>`s generally come without `class="docutils"` attribute, thus remain unaffected by the 100KB readthedocs theme stylesheet.

**Comment by waylan** [comment] 2020-12-28 18:15
Actually, the rules should be redefined in [mkdocs/themes/readthedocs/css/theme_extra.css][1] with the appropriate identifiers. We have a number of such rules for code blocks. Presumably we need to add a few for tables. 

Actually, the last two rules in that file are for tables. However, they don't really point to the tables as they should. For example, the first includes a reference to the `.docutils` class, which wouldn't exist. And the second doesn't restrict itself to tables within the body of the page (as a descendant of `.rst-content`).

[1] https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/readthedocs/css/theme_extra.css

**Comment by prof-milki** [comment] 2020-12-28 20:27
Yep, the theme overrides don't seem to cover tables. And .rst-content by itself don't trigger the default RTD selectors:

    .wy-table, .rst-content table.docutils, .rst-content table.field-list  {…}
    .wy-table-odd td, .wy-table-striped tr:nth-child(2n-1) td, .rst-content table.docutils:not(.field-list) tr:nth-child(2n-1) td  {…}

So, short of duplicating the RTD styles without the sphinx classes, tables will look fairly dull.

**Comment by waylan** [comment] 2020-12-28 20:48
Markdown will only ever generate tables comparable to docutils' `table.docutils`. Therefore, we can ignore `.wy-table` and `table.field-list` and only need to redefine rules for `table.docutils`, but without the `.docutils`. Of course, a patch is welcome.

**Comment by prof-milki** [comment] 2020-12-28 22:06
Come to think of it, might be as simple as:

    sed -i 's/table\.docutils/table/g' ./site/css/theme.css 

Doesn't really fix all occurences. There's a load of `:not(.docutils)`s remaining, but seemingly for `<dl>`s.  
But otherwise works for me.

I'd think that patching the markdown plugin might be the better approach still.

**Comment by waylan** [comment] 2020-12-28 23:14
Changing Markdown's output from a theme would not be possible. The need is very theme specific (for example, the MKDocs theme is not based on a Sphinx theme). And themes can only provide templates and media. They have no way to provide code which alters how MkDocs works. Therefore, to do as you propose would require both enabling the theme and a custom markdown extension. Clearly the better approach is to just customize the theme.

**Comment by zerocrates** [comment] 2021-04-06 21:12
I noticed this as a regression: in older versions the "docutils" class is there, it seems? Is this just an effect of a change made at the markdown processing layer that needs to be accounted for in the theme, or what?

**Comment by zerocrates** [comment] 2021-04-06 21:18
Oh no, I see what it was: 294b788eb6c4971fdb6bf15c50bebcc4b3a4e9de had previously just used JS to add those classes to make the CSS work, and that got tossed out when updating to the new upstream JS.

**Comment by waylan** [comment] 2021-04-08 00:24
This is a duplicate of #2028, which has just been fixed in #2356.

**Closed** 2021-04-08 00:25 UTC
Labels: Bug, Theme-readthedocs
