### ISSUE TITLE
Rogue control characters break search in mkdocs theme

### ISSUE THREAD

**Issue by squidfunk** [mkdocs/mkdocs#1937] opened 2019-12-18 20:02 UTC
I'm just refactoring the search of the Material theme and switched to using `index.search` instead of `index.query` when I ran into an issue. If I pass any of the control characters lunr understands, i.e. `+-:^~` outside of the context it understands, the index will throw an error.

This can be reproduced by opening the console on [mkdocs.org](https://mkdocs.org) and typing `title:` or `title~`

Result:

<img width="766" alt="Bildschirmfoto 2019-12-18 um 20 54 22" src="https://user-images.githubusercontent.com/932156/71119026-7b641d80-21d9-11ea-9811-17a9d11997f1.png">

If you're interested in a fix, I think I catched all cases [here](https://github.com/squidfunk/mkdocs-material/blob/60330fd18d6ebee96fb9ea9affbdcb4cffc2b884/src/assets/javascripts/modules/search/_/index.ts#L192-L194)

**Comment by waylan** [comment] 2019-12-18 22:46
Interesting. I hadn't notice that before. But then I don't think I ever tested using those characters. In fact, if you don't have the console open, you don't notice. AFAICT, they don't interfere with valid search results. In other words the problem is invisible to the end user.

In any event, this seems more like an upstream issue to me. Lunr should be accounting for these query strings and handling them by returning empty search results without raising an errors Or perhaps Lunr should be returning a unique error indicating that there are no search results as the query string is incomplete. Either way, we could then handle the case simply by providing for an empty result (or treating the unique error as an empty result) without the need to modify the search query.

**Comment by squidfunk** [comment] 2019-12-19 08:09
This was just meant as an FYI. I don't mind if you close it unresolved, if you don't regard it as an error.

**Comment by waylan** [comment] 2019-12-19 18:48
I wanted to search Lunr for any existing issues on the matter and only found olivernn/lunr.js#274, which is an older issue before most of the current characters had any special meaning. It would seem that at the time MkDocs would have needed to catch the error to avoid a crash. However, today Lunr simply outputs the error to the console and continues unaffected.

While the situation is different today than it was then, I find the position of the Lunr devs to be interesting. Basically their position is that as users of their lib, we should handle the errors. However, nowhere do they suggest that we should be altering the search string to avoid raising the errors to begin with. And I agree with that approach.

So, if you want to avoid the error being output to the console, catch it and then return an empty search result. But don't alter the users input. Personally, I like the error being output to the console as it is a quick and easy way to see why no search results are being returned, while also remaining invisible to the average user.

Given the above, I'm closing this.

**Closed by waylan** 2019-12-19 18:48 UTC
