### ISSUE TITLE
Exclude unreferenced files from output

### ISSUE THREAD

**Issue by wilhelmer** [mkdocs/mkdocs#1721] opened 2019-01-11 12:55 UTC
* Request 1: Add an option to control whether **md** files that aren't included in the "nav" configuration should be excluded from output. (Currently, an info message for unreferenced files is displayed at build time, but the files are still included in the output directory.)
* Request 2: Add an option to control whether **image** files that aren't referenced in any md file should be excluded from output. (Currently, all image files in the source dir are copied to the output dir, regardless of whether they are referenced or not.)

**Comment by wilhelmer** [comment] 2019-01-22 07:16
Edited for better clarity.

**Comment by froschdesign** [comment] 2019-01-22 08:18
@wilhelmer 
I think this issue is a duplicate of #1665

**Comment by waylan** [comment] 2019-01-22 14:42
"Request 1" is definitely a duplicate of #1665. However, one *might* argue that "Request 2" is not a duplicate. Currently MkDocs does not tract which images are actually referenced within pages. In fact, IIRC, all non-page files (including images) are copied before any pages are processed. It would be a significant change to the build process to even make "Request 2" possible. Probably significant enough to require a 2.0 release, which would be a long time off.

Regardless, there are legitimate reasons to expect that there could be images (or other files) in the `docs_dir` that are not linked from page content, but are linked from page templates and should be included in the output. For example, if  a `favicon.ico` is included in `docs_dir` is will replace any `favicon.ico` from the theme, although it is never linked from page content. A theme might use the same strategy to allow a user to supply a logo image file (say `logo.png`). This change would cause that to fail. Therefore, I consider this to be an unreasonable request. If you don't want a file to end up in the output, then don't put it in the `docs_dir`. 

I understand the frustration some users have with #1665 as, prior to version 1.0, MkDocs used to have the requested behavior. But images (and other non-page files) have always worked the way they do now.  I'm closing this as a **duplicate** for "Request 1" and as **wontfix** for "Request 2."

**Closed by waylan** 2019-01-22 14:42 UTC

**Comment by waylan** [comment] 2019-01-22 15:00
If you really want to exclude image files, then you can create a plugin which uses the `on_files` event to remove unwanted files from the files collection. I keep expecting someone to create such a general purpose plugin, but have yet to see one.

**Comment by JonasDoesThings** [comment] 2023-02-26 19:54
I have created a plugin for solving request 2 due to my own demand.
You can find it here: https://github.com/JonasDoesThings/mkdocs-exclude-unused-files

It works for me, happy to get some feedback / improvements if anyone else shares this problem.
