### ISSUE TITLE
gh-deploy

### ISSUE THREAD

**Issue by rlove** [mkdocs/mkdocs#1077] opened 2016-10-19 18:52 UTC
It would be nice if the gh-deploy deployment functionality could be changed to have optional subdirectory

````
mkdocs gh-deploy --clean --dir REPO_DIR
`````
The primary goal is to have multiple sets of documentation hosted under gh-pages.

| Directory | Purpose |
| ---------- | --------- |
| /current   | Latest commit Documentation |
| /release/v1.0.0.1 | Version 1.0.0.1 Documentation  |
| /release/vX.X.X.X | Version X.X.X.X Documentation |

So I would be able to call it like this to deploy to the `/release/vX.X.X.X` directory

````
mkdocs gh-deploy --clean --dir /release/vX.X.X.X
`````

**Comment by waylan** [comment] 2016-10-19 19:04
This is a duplicate of #193. Or at the very least, an alternate proposed solution.

**Closed by waylan** 2016-10-19 19:04 UTC
