### ISSUE TITLE
font-size in RDT theme is different in p and li

### ISSUE THREAD

**Issue by pquentin** [mkdocs/mkdocs#801] opened 2016-01-18 13:57 UTC
This works properly on readthedocs.org and is a CSS bug that can be understood with the following rules:

```
html { font-size: 100% }
body { font-size: 90% } /* only on mkdocs RTD theme */
p { font-size: 16px }
```

Since `li` is not inside `p`, it's not `16px` but `90%`. Since the default font size on (most?) browsers happens to be `16px`, `90%` of `16px` is smaller than the `16px` of `p`. On readthedocs.org, there's not `font-size` on `body`, so `font-size: 100%` from `html` is applied, which is `16px` on (most?) browsers, and all text uses the same `16px` size.

Is the CSS from mkdocs entirely different from readthedocs or is it just because mkdocs 0.14.0 is not in sync with RTD's CSS?

**Comment by marcelstoer** [comment] 2016-01-22 22:38
This is something I had to fix in my own `css/extra.css` as well. Based on other issues with the MkDocs RTD theme I'm beginning to understand it was reverse engineered at one point in time and not kept in sync. So, if you rely on it you'll probably have to continue adding statements to your custom CSS for months to come.

**Comment by waylan** [comment] 2016-01-22 23:00
This appears to me to be a duplicate of #588.

**Comment by d0ugal** [comment] 2016-01-28 10:59
I think this is probably a general bug, and may have been incorrect since the theme was originally ported. So, while #588 might fix it, that is probably a much bigger task than correcting this specific thing.

**Comment by d0ugal** [comment] 2016-01-28 10:59
(Meaning that I would be happy to see a fix come in just for this)

**Closed** 2016-02-02 14:22 UTC
Labels: Bug
