### ISSUE TITLE
Unclosed div warning

### ISSUE THREAD

**Issue by chenmoneygithub** [mkdocs/mkdocs#3884] opened 2024-12-15 02:13 UTC
Hi team,

I am seeing a few warnings similar to below:

```
[WARNING] Div at /tmp/tmpno_7m2er line 3 column 1 unclosed at /tmp/tmpno_7m2er line 19 column 1, closing implicitly.
```

I have made a smal produce. Here is my file structure:
<img width="256" alt="image" src="https://github.com/user-attachments/assets/9081ed35-483f-43cc-b091-8fcc856bfc36" />

content of mkdocs.yml:

```
site_name: Test Site

nav:
  - Home: index.md
  - API Reference:
      - gsm8k: api/gsm8k.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
  - mkdocs-jupyter:
      ignore_h1_titles: True
      files:
        - "tutorials/**/*.ipynb"

theme:
  name: material

```

gsm8k.md:

```
# Gsm8K API Reference

::: dspy.primitives
    handler: python
    options:
        docstring_section_style: google
```

Ran `mkdocs build -v`, and copied the relevant log:

```
INFO    -  Building documentation to directory: /Users/chen.qian/Documents/mlflow_team/dspy/doc-test/site
DEBUG   -  Looking for translations for locale 'en'
DEBUG   -  No translations found here: '/Users/chen.qian/miniconda3/envs/dspy/lib/python3.12/site-packages/mkdocs/templates/locales'
DEBUG   -  No translations found here: '/Users/chen.qian/miniconda3/envs/dspy/lib/python3.12/site-packages/material/templates/locales'
DEBUG   -  Running `files` event from plugin 'mkdocs-jupyter'
[WARNING] Div at /tmp/tmplsb3m13s line 3 column 1 unclosed at /tmp/tmplsb3m13s line 9 column 1, closing implicitly.
DEBUG   -  Reading markdown pages.
DEBUG   -  Reading: api/gsm8k.md
DEBUG   -  Running `pre_page` event from plugin 'mkdocs-jupyter'
[WARNING] Div at /tmp/tmppa5ofwcg line 3 column 1 unclosed at /tmp/tmppa5ofwcg line 9 column 1, closing implicitly.
DEBUG   -  Running `page_markdown` event from plugin 'autorefs'
DEBUG   -  mkdocstrings: Matched '::: dspy.primitives'
DEBUG   -  mkdocstrings: Using handler 'python'
DEBUG   -  mkdocstrings: Collecting data
DEBUG   -  griffe: Searching path(s) for dspy
```

Could someone help take a look? thanks!

**Comment by pawamoy** [comment] 2024-12-15 12:55
The warnings logs do not respect MkDocs' format so I assume they come from the jupyter plugin and not mkdocstrings or MkDocs itself. Check your notebooks for unclosed docs 🤷

**Comment by pawamoy** [comment] 2024-12-15 12:57
In any case I don't think that qualifies as an issue so I'll close this (still can't convert to discussion from the GitHub mobile app).

**Closed** 2024-12-15 12:57 UTC

**Comment by chenmoneygithub** [comment] 2024-12-15 20:24
@pawamoy Thanks for taking a look! The weird part is my reproduce doesn't have any notebook file, the only doc is `gsm8k.md`. So I have two questions:

- [probably unrelated to your squad] Why does `mkdocs-jupyter` cause unclosed div when there is no notebook files in the doc directory? 
- Is `mkdocs-jupyter` the recommended practice for converting notebooks for sites built by mkdocs?

**Comment by pawamoy** [comment] 2024-12-15 21:00
> The weird part is my reproduce doesn't have any notebook file

Right, I might have judged too quick. Could you share the code source that you inject with `::: dspy.primitives`?

**Comment by chenmoneygithub** [comment] 2024-12-15 21:11
`dspy.primitives` contains many things, so I simplified the reproduce a bit more and updated the issue description. It is now generating doc for `dspy.datasets.dataset.Dataset`, the code of which can be found [here](https://github.com/stanfordnlp/dspy/blob/main/dspy/datasets/dataset.py).

**Comment by pawamoy** [comment] 2024-12-15 23:48
Thank you! I'll take a proper look tomorrow 🙂

**Comment by pawamoy** [comment] 2024-12-16 11:25
I cannot reproduce the issue you describe with the given example.

**Comment by chenmoneygithub** [comment] 2024-12-16 19:34
Hmmm odd, I might be messing up my conda environment, could you share your package version? Mine is:

```
(dspy) *[ahh-dspy-docs][~/Documents/mlflow_team/dspy/docs]$ pip list | grep mkdocs
mkdocs                                   1.6.1
mkdocs-autorefs                          1.2.0
mkdocs-gen-files                         0.5.0
mkdocs-get-deps                          0.2.0
mkdocs-jupyter                           0.25.1
mkdocs-material                          9.5.44
mkdocs-material-extensions               1.3.1
mkdocs-redirects                         1.2.2
mkdocstrings                             0.27.0
mkdocstrings-python                      1.12.2
```

**Comment by pawamoy** [comment] 2024-12-16 23:07
I recreated my venv with these versions, and still cannot reproduce unfortunately.

**Comment by chenmoneygithub** [comment] 2024-12-16 23:55
😧.... looks like something is wrong with my local setup. Thanks a lot for helping! @pawamoy

**Comment by pawamoy** [comment] 2024-12-17 10:36
You're welcome ☺️

**Comment by arturomoncadatorres** [comment] 2025-05-28 15:14
If you ended up here trying to find a solution, it seems this is not an `mkdocs` issue, but actually an `mkdocs-jupyter` one. Take a look [here](https://github.com/danielfrg/mkdocs-jupyter/issues/231#issuecomment-2668606917) for a (hacky) solution.
