### ISSUE TITLE
Wildcards or Regex in mkdocs.yml

### ISSUE THREAD

**Issue by Backfighter** [mkdocs/mkdocs#1255] opened 2017-07-14 12:51 UTC
This is a feature request. It would be nice if one could use wildcards or regex in the mkdocs.yml to include several files in a section without manually adding them by hand.
Lets say we have a configuration like this:
```
site_name: Awesome project
pages:
- Home: 'index.md'
- A growing list of reports:
  - 'reports/2017-04-06-report'
  - 'reports/2017-04-08-report'
  - 'reports/2017-04-14-report'
  - 'reports/2017-04-18-report'
  - 'reports/2017-04-20-report
```
With wildcards it could be easily rewritten to this:
```
site_name: Awesome project
pages:
- Home: 'index.md'
- A growing list of reports:
  - 'reports/*'
```
This would mean, that the mkdocs.yml wouldn't need to be changed on every new report.

**Comment by waylan** [comment] 2017-07-14 14:33
I'm closing this as a duplicate of #699. I realize the title of that issue seems to not be a request for the exact same feature, but this feature is one of the proposed solutions.

**Closed by waylan** 2017-07-14 14:33 UTC
