### ISSUE TITLE
Consider providing an OCI image distribution

### ISSUE THREAD

**Issue by ascopes** [mkdocs/mkdocs#3275] opened 2023-06-27 07:55 UTC
I have started using mkdocs this week to deal with creating GitHub pages for the documentation for a Terraform provider I am building, and I found it really easy to configure and get working first time.

I was wondering if it may be worth including a simple Dockerfile in this project and releasing it to DockerHub, quay.io, or public.ecr.aws. This would be useful for projects that do not use Python in their CI pipelines so that they can avoid having to manually set it up.

Suppose the following Dockerfile (I haven't used hatchling before so I have omitted creating a wheel for it first to install from)...

```dockerfile
FROM       python:3.11-alpine AS build
COPY       . /src
WORKDIR    /src
RUN        python3 -m venv .venv/ && .venv/bin/pip install .

FROM       python:3.11-alpine AS final
COPY       --from=build /src/.venv /venv
ENTRYPOINT ["/venv/bin/mkdocs"]
CMD        ["--help"]
```

...this would allow users to invoke mkdocs from CI without needing to install Python first, by running something like the following:

```shell
docker run \
    --rm \
    -u "$(id -u "${USER}")" \
    -v "$(pwd):/src" \
    -w /src \
    mkdocs/mkdocs:9.9.99 \
    build
```

...which would download and install the image, and then proceed to run mkdocs inside the container to produce the desired site.

This would be useful for projects that may be run in multiple environments and not have a quick standard way of installing Python (e.g. from in a Makefile where it may be run on GitHub actions or on an OS that may not have a consistent version of Python available).

**Comment by pawamoy** [comment] 2023-06-29 09:47
See previous discussion at https://github.com/mkdocs/mkdocs/issues/2136.

An example without an official MkDocs image:

```bash
docker run \
    --rm \
    -u "$(id -u "${USER}")" \
    -v "$(pwd):/src" \
    -w /src \
    python:3.11 \
    sh /src/docs/install-deps-and-build.sh
```

...where `src/docs/install-deps-and-build.sh` is:

```bash
#!/usr/bin/env bash
pip install mkdocs mkdocs-material  # and other plugins, etc.
mkdocs build
```

**Comment by oprypin** [comment] 2023-06-29 19:51
Duplicate of https://github.com/mkdocs/mkdocs/issues/2136

**Closed by oprypin** 2023-06-29 19:51 UTC
