### ISSUE TITLE
Error on while Serve on windows 

### ISSUE THREAD

**Issue by salmanfarisvp** [mkdocs/mkdocs#1911] opened 2019-11-26 00:50 UTC
Error while serve a doc on windows 10 

```
PS C:\Users\Faris\Desktop\experiments> mkdocs new doc
INFO    -  Creating project directory: doc
INFO    -  Writing config file: doc\mkdocs.yml
INFO    -  Writing initial docs: doc\docs\index.md
PS C:\Users\Faris\Desktop\experiments> cd .\doc\
PS C:\Users\Faris\Desktop\experiments\doc> mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
[I 191126 06:18:41 server:296] Serving on http://127.0.0.1:8000
Traceback (most recent call last):
  File "c:\users\faris\appdata\local\programs\python\python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\faris\appdata\local\programs\python\python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Faris\AppData\Local\Programs\Python\Python38-32\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "c:\users\faris\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\faris\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\faris\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\faris\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\faris\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\faris\appdata\local\programs\python\python38-32\lib\site-packages\mkdocs\__main__.py", line 128, in serve_command
    serve.serve(
  File "c:\users\faris\appdata\local\programs\python\python38-32\lib\site-packages\mkdocs\commands\serve.py", line 124, in serve
    _livereload(host, port, config, builder, site_dir)
  File "c:\users\faris\appdata\local\programs\python\python38-32\lib\site-packages\mkdocs\commands\serve.py", line 58, in _livereload
    server.serve(root=site_dir, host=host, port=port, restart_delay=0)
  File "c:\users\faris\appdata\local\programs\python\python38-32\lib\site-packages\livereload\server.py", line 298, in serve
    self.application(
  File "c:\users\faris\appdata\local\programs\python\python38-32\lib\site-packages\livereload\server.py", line 253, in application
    app.listen(port, address=host)
  File "c:\users\faris\appdata\local\programs\python\python38-32\lib\site-packages\tornado\web.py", line 2112, in listen
    server.listen(port, address)
  File "c:\users\faris\appdata\local\programs\python\python38-32\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "c:\users\faris\appdata\local\programs\python\python38-32\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "c:\users\faris\appdata\local\programs\python\python38-32\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "c:\users\faris\appdata\local\programs\python\python38-32\lib\site-packages\tornado\platform\asyncio.py", line 99, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "c:\users\faris\appdata\local\programs\python\python38-32\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
```

**Comment by waylan** [comment] 2019-11-26 13:35
This is a duplicate of #1885.

**Closed by waylan** 2019-11-26 13:35 UTC

**Comment by salmanfarisvp** [comment] 2019-12-10 05:57
FYI: The Problem with Python verison 3.8 after downgrade to 3.7 is working without any problem .
