### ISSUE TITLE
Baselevel not working

### ISSUE THREAD

**Issue by diazgilberto** [mkdocs/mkdocs#1658] opened 2018-10-13 17:05 UTC
I'm trying the tool to make it my default to write documentation. Inside the `mkdocs.yml` I included the following...

```
markdown_extensions:
    - toc:
        baselevel: 2
```

with the expectation to bypass `<h1>` tags in the `[TOC]`. However I still see `<h1>` in the `[TOC]`.

- Is it the `mkdocs.yml` the place to include this settings?
- Does the tool has the `toc` extension installed already or I need to install it? if not... what is the command to install the tool? `pip install ...`?

- VERSIONS

Mac Sierra 10.12.6

```
pip list


Click      7.0
Jinja2     2.10
livereload 2.5.2
Markdown   3.0.1
MarkupSafe 1.0
mkdocs     1.0.4
pip        18.1
PyYAML     3.13
setuptools 39.0.1
six        1.11.0
tornado    5.1.1
```

**Comment by waylan** [comment] 2018-10-13 18:03
> with the expectation to bypass `<h1>` tags in the `[TOC]`.

That is not the purpose or function of the `baselevel` setting. It does not remove any items from the TOC, but instead changes the level designation of the headers in the body of the document. In other words, an `<h1>` would be changed to an `<h2>` and an `<h2>` would be changed to an `<h3>`, and so on. However, all headers would still exist and all headers would still be listed in the TOC.

If this is a request to support a feature to exclude the top level from the TOC, then this is a duplicate of #1086.

**Closed** 2018-10-13 18:07 UTC

**Comment by Scotchester** [comment] 2019-01-08 21:19
@waylan You're right that that is not the purpose of `baselevel`, but it's not a dupe of #1086, which appears to want to limit lower-level headings (i.e., headings with higher numerical values) from appearing in a TOC.

I think we should either reopen this as a feature request to be able to skip H1s in TOCs (this is particularly problematic for us when using the ReadTheDocs theme – not sure if that sidebar TOC is connected to the `[TOC]` tag or not), or I can create a new issue if you prefer.

**Comment by waylan** [comment] 2019-01-08 21:32
If the request is to "skip lelves of the TOC" then the request is denied. We will not be implementing such a feature. That can be addressed by a theme with no code changes to MkDocs. For an existing theme, theme customization should be able to override the behavior.

**Comment by Scotchester** [comment] 2019-01-08 22:11
In case an example would be useful... it is not helpful, in our case, for the H1, "Writing JavaScript Unit Tests" to appear either in an on-page `[TOC]`

![screen shot 2019-01-08 at 16 43 57](https://user-images.githubusercontent.com/1044670/50860807-db650980-1364-11e9-8dbe-c4b317c467b6.png)

or in the side nav

![screen shot 2019-01-08 at 16 46 48](https://user-images.githubusercontent.com/1044670/50860873-0b141180-1365-11e9-87be-f67be6f4f6de.png)

Now, I see that in the latest unreleased RTD theme update, [some code exists that looks like it intends to fix the sidebar issue](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/readthedocs/nav.html#L10-L11). That's great! I look forward to that. But I don't think there's a template that can be overridden for the in-body `[TOC]` usage, is there? So I still think an "exclude H1s from generated TOC lists" would be helpful, regardless of what theme one is using.

**Comment by waylan** [comment] 2019-01-08 22:16
> Now, I see that in the latest unreleased RTD theme update, [some code exists that looks like it intends to fix the sidebar issue][1]. That's great! 

Yes, that will be available in the next release (in other words, any other changes will not be available any earlier than that change). And that is the only way we will support the requested feature. If you are using a third party theme which does not offer a way to support that, then you should file a bug with that theme.

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/readthedocs/nav.html#L10-L11

**Comment by dkadrios** [comment] 2020-07-13 22:57
Came here looking for the same (exclude H1 from TOC).  Found you can accomplish the same thing with toc_depth
```
markdown_extensions:
  - toc:
      toc_depth: "2-4"
```

HTH
