### ISSUE TITLE
Some symbols from the markdown aren't encoded correctly

### ISSUE THREAD

**Issue by AncientSwordRage** [mkdocs/mkdocs#352] opened 2015-02-21 13:02 UTC
I am trying to use the £ symbol in my markdown, and it's being displayed as 'Â£' which to me implies my utf-8 markdown is being served as non-utf-8 enconding.

Is this a known issue? I'm serving it via powershell on windows. Or is this a problem with how windows works?

**Comment by d0ugal** [comment] 2015-03-07 19:44
I suspect this is an issue related to Windows encoding. I know we have some users that use unicode characters (i.e. full chinese, I think, pages). Is your project somewhere I can access to confirm this?

**Comment by IgorZh** [comment] 2015-04-05 06:31
I have same problem with russian characters in github wiki.
[sample page](https://github.com/IgorZh/AngularFirstApp/wiki)
system: Windows 7, Python 3.4.3

**Comment by waylan** [comment] 2015-04-07 22:58
Those of you experiencing this problem, can you verify whether #428 fixes the issue for you?

**Comment by IgorZh** [comment] 2015-04-08 05:28
Can you give me some instruction, how to check, because I am no fimilar with python.
I download last source code. Run `python setup.py install` . Then in my project folder run `mkdocs build`. This not help.

**Comment by d0ugal** [comment] 2015-04-08 06:40
@IgorZh Did you checkout @waylan's `encoding` branch? You can also install it with :

    pip install -Ihttps://github.com/waylan/mkdocs/archive/encoding.zip

**Comment by d0ugal** [comment] 2015-04-08 18:23
This should be fixed by #428 - happy to reopen if somebody can confirm this is still an issue.

**Closed by d0ugal** 2015-04-08 18:23 UTC
Labels: Bug

**Comment by tkirill** [comment] 2015-05-28 12:57
This is still an issue but this is a bug in livereload.  I reproduced it with Python 3.4.3 on Windows 8.1:

* mkdocs form master
* livereload 2.3.2
* run `mkdocs serve`
* Euro sign "€" displays as "в‚¬"

There is no issue if I run `mkdocs serve --no-livereload`.  Also, there is no issue if I use livereload from master.  Seems like switching to Tornado static file handler (lepture/python-livereload@1c67c02) fixed the issue.

**Comment by d0ugal** [comment] 2015-05-28 13:02
Yup, so as you found out, this will be fixed with the 2.4 release. https://github.com/lepture/python-livereload/issues/105

**Comment by sugatoray** [comment] 2021-10-05 08:26
I came here searching for how to include icons (fontawesome, octicon, etc.) along side the sections/titles in the nav-bar. It turns out that with `mkdocs-material` you can do this, but you need to use a small dirty trick. I documented the process [here](https://github.com/squidfunk/mkdocs-material/issues/2318#issuecomment-934173785).

If you happen to stop by here and you are also looking for a way to use icons in your nav-item-titles, I hope you find this useful.
