### ISSUE TITLE
Renaming a file in Live reload mode causes 502 error

### ISSUE THREAD

**Issue by visuman** [mkdocs/mkdocs#2556] opened 2021-08-30 09:30 UTC
I have Mkdocs running on a development server that is run using the command `mkdocs serve --livereload`.
Many a time the process goes down with a similar error:

```
ERROR    -  File not found: note.md
ERROR    -  Error reading page 'note.md': [Errno 2] No such file or directory: '/home/centos/mkdocs/docs/note.md'
[Errno 2] No such file or directory: '/home/centos/mkdocs/docs/note.md'
```

This is happening when there is a reload happening and a file is renamed around the same time.

Is there a way to avoid this issue?

**Comment by oprypin** [comment] 2021-08-30 20:17
I couldn't get it to happen even once. How are you managing to get this error with what seems to be high consistency (per your description)? Can you give exact steps or even a script to make the error happen?

**Comment by tomchristie** [comment] 2024-04-10 19:14
Closing as not reproduced.

**Closed by tomchristie** 2024-04-10 19:14 UTC
