### ISSUE TITLE
Local docs: broken search and missing images

### ISSUE THREAD

**Issue by fredrikaverpil** [mkdocs/mkdocs#1644] opened 2018-09-28 14:55 UTC
I build my documentation using mkdocs and copy it into an application which I distribute. The idea is to have users of this application be able to read the docs offline so to speak.

From within my application, users can choose to "open the documentation", which will take them to the local path of the root index.html. From certain parts of the application, users can click a "help" icon and this will take them directly to the appropriate and local HTML page.

I've noticed a couple of problems with this:

- **Firefox**, 62.0.2 (64-bit)
  - Search only works on root index.html and if navigating away from this starting page. But if you open a different HTML page up directly, search is broken from the get go.
  - Also, if you open a non-root index.html page, navigational images are broken.
- **Chrome**, 69.0.3497.100 (Official Build) (64-bit)
  - Search does not work when viewing local pages like this

I've attempted to show this in a screencast: https://drive.google.com/open?id=1NhT9MXu4lO03Rw8Vv8a3rvY8GK7YTUDX

This is all on Python 3.7 64-bit (Windows 10) with mkdocs 1.0.4 and mkdocs-material 3.0.4.

**Comment by waylan** [comment] 2018-09-28 15:15
This is a known limitation which is directly connected to the security features of the browser. In other words, the only workaround is to disable the browsers' security features. Of course, we do not recommend doing so and therefore do not support search from the `file://` scheme. If you want search to work, then you need to have a server running.

If you are building your documents to be used in a  local file setting, then our recommendation is to disable the search plugin so that the search box is not included on pages and you do not create a false expectation for your users.

**Comment by waylan** [comment] 2018-09-28 15:19
Closing this as a duplicate of #871.

**Closed by waylan** 2018-09-28 15:19 UTC

**Comment by fredrikaverpil** [comment] 2018-10-01 06:42
Thanks @waylan
