### ISSUE TITLE
Add ancestors to search index in order to allow category-contextual searches

### ISSUE THREAD

**Issue by memeplex** [mkdocs/mkdocs#1003] opened 2016-07-27 21:28 UTC
Currently if there is no category info embedded in a page title or subtitles it's not possible to search it as part of a category. Also, searches can not be restricted to categories or subcategories. I think this could be easily implemented by just adding cat:value tokens while constructing the search index for a page. For example, if the page has x, y as ancestors, cat:x, cat:y and cat:x/y could be the additional tokens. What do you think? I can submit a PR if you're interested.

**Comment by memeplex** [comment] 2016-07-27 21:52
Or maybe just adding x and y (i.e. the ancestors) will be easier to search and combine (just "x y" instead of, say, "cat:x/y") given the search and semantics, at the low price of some ambiguity in referring content vs category.

**Comment by waylan** [comment] 2016-07-28 03:20
This appears to be a duplicate of #931.

**Closed** 2017-10-24 19:58 UTC
Labels: Enhancement
