### ISSUE TITLE
Theme is not deployed to github with gh-deploy

### ISSUE THREAD

**Issue by afaucogney** [mkdocs/mkdocs#2255] opened 2020-12-18 18:38 UTC
I run successfully `mkdocs build`, `mkdocs serve`, the data with the theme are available in github.

However, when I `mkdocs gh-deploy`, the site is deployed, but without any theme.
I tested with 2 different themes

Here is the original issue : https://github.com/squidfunk/mkdocs-material/issues/2104

gh-pages: https://afaucogney.github.io/flipper-ktp/
mkdocs config: https://github.com/afaucogney/flipper-ktp/blob/master/mkdocs.yml
github action: https://github.com/afaucogney/flipper-ktp/actions/runs/428782492/workflow

**Comment by waylan** [comment] 2020-12-18 19:34
What do you mean "without a theme"? Do you mean the theme specific files (CSS, JS, etc) are not uploaded or something else?

I looked at your site and I do not see any obvious issues. If course, I'm not familiar with the theme you are using and I don't know what you are expecting so that makes it difficult. I checked the borrower console and saw no errors (except for a missing favicon). I also checked out the `gh-deploy` branch of your repo and it appears that all of the files are present.

To ensure this is is not specific to a theme, I would suggest trying one of the built-in themes. If it occurs there, then we will be able to see the issue as we know what to expect.

You also might want to include the `--verbose` flag in your `gh-deploy` command. That will list a lot more details about what happens during the build.

**Comment by facelessuser** [comment] 2020-12-18 20:27
As I use Material, whatever the issue is, I don't think it is specifically related to Material as I am able to deploy with gh-deploy with no issues. I've done so as recently as last week.

With that said, gh-deploy works fine from my local system without anything extra, but I do remember there being some issue just pushing it from an action, and doing some research, I currently do this: https://github.com/facelessuser/soupsieve/blob/master/.github/workflows/deploy.yml#L30.

Maybe you will find something here useful as this currently works for me.

**Comment by afaucogney** [comment] 2020-12-19 10:45
@waylan  @facelessuser  thanks for your help.

I tried with the mkdocs theme, and it does goes in the same way. No theme. When I say " no theme", I means there is no customisation, no tabbar.... like this:

![Capture d’écran 2020-12-19 à 11 38 15](https://user-images.githubusercontent.com/6554201/102687404-20e80d80-41ef-11eb-9fe8-a29ec54a4a1c.png)

My issue is the same that I use `gh-deploy` or gh actions.

with `mkdocs serve` for

mkdocs theme:

![Capture d’écran 2020-12-19 à 11 38 24](https://user-images.githubusercontent.com/6554201/102687434-57be2380-41ef-11eb-9ef2-b8f3507b37bc.png)

and material theme :

![Capture d’écran 2020-12-19 à 11 38 54](https://user-images.githubusercontent.com/6554201/102687438-5db40480-41ef-11eb-89d9-62c2a2a71105.png)

Here is the log with `--verbose`

```
C02CC88ZMD6M:FlipperKtp afaucogney$ mkdocs gh-deploy --verbose
DEBUG   -  Loading configuration file: /Users/afaucogney/Documents/archi/git/FlipperKtp/mkdocs.yml 
DEBUG   -  Loaded theme configuration for 'material' from '/usr/local/lib/python3.9/site-packages/material/mkdocs_theme.yml': {'language': 'en', 'direction': None, 'features': [], 'palette': {'primary': None, 'accent': None}, 'font': {'text': 'Roboto', 'code': 'Roboto Mono'}, 'icon': None, 'favicon': 'assets/images/favicon.png', 'include_search_page': False, 'search_index_only': True, 'static_templates': ['404.html']} 
DEBUG   -  Config value: 'config_file_path' = '/Users/afaucogney/Documents/archi/git/FlipperKtp/mkdocs.yml' 
DEBUG   -  Config value: 'site_name' = 'Flipper Ktp' 
DEBUG   -  Config value: 'nav' = [{'Overview': 'index.md'}] 
DEBUG   -  Config value: 'pages' = None 
DEBUG   -  Config value: 'site_url' = 'https://afaucogney.github.io/flipper-ktp/' 
DEBUG   -  Config value: 'site_description' = None 
DEBUG   -  Config value: 'site_author' = None 
DEBUG   -  Config value: 'theme' = Theme(name='material', dirs=['/usr/local/lib/python3.9/site-packages/material', '/usr/local/lib/python3.9/site-packages/mkdocs/templates'], static_templates=['sitemap.xml', '404.html'], language='en', direction=None, features=[], palette={'primary': None, 'accent': None}, font={'text': 'Roboto', 'code': 'Roboto Mono'}, icon=None, favicon='assets/images/favicon.png', include_search_page=False, search_index_only=True) 
DEBUG   -  Config value: 'docs_dir' = '/Users/afaucogney/Documents/archi/git/FlipperKtp/docs' 
DEBUG   -  Config value: 'site_dir' = '/Users/afaucogney/Documents/archi/git/FlipperKtp/site' 
DEBUG   -  Config value: 'copyright' = None 
DEBUG   -  Config value: 'google_analytics' = None 
DEBUG   -  Config value: 'dev_addr' = Address(host='127.0.0.1', port=8000) 
DEBUG   -  Config value: 'use_directory_urls' = True 
DEBUG   -  Config value: 'repo_url' = '' 
DEBUG   -  Config value: 'repo_name' = '' 
DEBUG   -  Config value: 'edit_uri' = '' 
DEBUG   -  Config value: 'extra_css' = [] 
DEBUG   -  Config value: 'extra_javascript' = [] 
DEBUG   -  Config value: 'extra_templates' = [] 
DEBUG   -  Config value: 'markdown_extensions' = ['toc', 'tables', 'fenced_code'] 
DEBUG   -  Config value: 'mdx_configs' = {} 
DEBUG   -  Config value: 'strict' = False 
DEBUG   -  Config value: 'remote_branch' = 'gh-pages' 
DEBUG   -  Config value: 'remote_name' = 'origin' 
DEBUG   -  Config value: 'extra' = {} 
DEBUG   -  Config value: 'plugins' = PluginCollection([('search', <mkdocs.contrib.search.SearchPlugin object at 0x110c7da60>)]) 
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /Users/afaucogney/Documents/archi/git/FlipperKtp/site 
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - changelog.md
  - dev-env.md
  - faq.md
  - fundamentals-how-flipper-ktp-works.md
  - fundamentals-how-flipper-works.md
  - fundamentals-how-ktp-works.md
  - fundamentals.md
  - getting_started.md
  - how_to_help.md
  - recipes.md
  - releasing.md
  - support.md
  - api/flipper-ktp/index.md
  - api/flipper-ktp/alltypes/index.md
  - api/flipper-ktp/fr.afaucogney.mobile.flipper/index.md
  - api/flipper-ktp/fr.afaucogney.mobile.flipper/-build-config/index.md
  - api/flipper-ktp/fr.afaucogney.mobile.flipper/-build-config/-b-u-i-l-d_-t-y-p-e.md
  - api/flipper-ktp/fr.afaucogney.mobile.flipper/-build-config/-d-e-b-u-g.md
  - api/flipper-ktp/fr.afaucogney.mobile.flipper/-build-config/-init-.md
  - api/flipper-ktp/fr.afaucogney.mobile.flipper/-build-config/-l-i-b-r-a-r-y_-p-a-c-k-a-g-e_-n-a-m-e.md
  - api/flipper-ktp/fr.afaucogney.mobile.flipper/-ktp-flipper-plugin/index.md
  - api/flipper-ktp/fr.afaucogney.mobile.flipper/-ktp-flipper-plugin/-init-.md
  - api/flipper-ktp/fr.afaucogney.mobile.flipper/-ktp-flipper-plugin/get-id.md
  - api/flipper-ktp/fr.afaucogney.mobile.flipper/-ktp-flipper-plugin/on-connect.md
  - api/flipper-ktp/fr.afaucogney.mobile.flipper/-ktp-flipper-plugin/on-disconnect.md
  - api/flipper-ktp/fr.afaucogney.mobile.flipper/-ktp-flipper-plugin/run-in-background.md 
DEBUG   -  Reading markdown pages. 
DEBUG   -  Reading: index.md 
DEBUG   -  Reading: changelog.md 
DEBUG   -  Reading: dev-env.md 
DEBUG   -  Reading: faq.md 
DEBUG   -  Reading: fundamentals-how-flipper-ktp-works.md 
DEBUG   -  Reading: fundamentals-how-flipper-works.md 
DEBUG   -  Reading: fundamentals-how-ktp-works.md 
DEBUG   -  Reading: fundamentals.md 
DEBUG   -  Reading: getting_started.md 
DEBUG   -  Reading: how_to_help.md 
DEBUG   -  Reading: recipes.md 
DEBUG   -  Reading: releasing.md 
DEBUG   -  Reading: support.md 
DEBUG   -  Reading: api/flipper-ktp/index.md 
DEBUG   -  Reading: api/flipper-ktp/alltypes/index.md 
DEBUG   -  Reading: api/flipper-ktp/fr.afaucogney.mobile.flipper/index.md 
DEBUG   -  Reading: api/flipper-ktp/fr.afaucogney.mobile.flipper/-build-config/index.md 
DEBUG   -  Reading: api/flipper-ktp/fr.afaucogney.mobile.flipper/-build-config/-b-u-i-l-d_-t-y-p-e.md 
DEBUG   -  Reading: api/flipper-ktp/fr.afaucogney.mobile.flipper/-build-config/-d-e-b-u-g.md 
DEBUG   -  Reading: api/flipper-ktp/fr.afaucogney.mobile.flipper/-build-config/-init-.md 
DEBUG   -  Reading: api/flipper-ktp/fr.afaucogney.mobile.flipper/-build-config/-l-i-b-r-a-r-y_-p-a-c-k-a-g-e_-n-a-m-e.md 
DEBUG   -  Reading: api/flipper-ktp/fr.afaucogney.mobile.flipper/-ktp-flipper-plugin/index.md 
DEBUG   -  Reading: api/flipper-ktp/fr.afaucogney.mobile.flipper/-ktp-flipper-plugin/-init-.md 
DEBUG   -  Reading: api/flipper-ktp/fr.afaucogney.mobile.flipper/-ktp-flipper-plugin/get-id.md 
DEBUG   -  Reading: api/flipper-ktp/fr.afaucogney.mobile.flipper/-ktp-flipper-plugin/on-connect.md 
DEBUG   -  Reading: api/flipper-ktp/fr.afaucogney.mobile.flipper/-ktp-flipper-plugin/on-disconnect.md 
DEBUG   -  Reading: api/flipper-ktp/fr.afaucogney.mobile.flipper/-ktp-flipper-plugin/run-in-background.md 
DEBUG   -  Copying static assets. 
DEBUG   -  Copying media file: 'api/flipper-ktp/package-list' 
DEBUG   -  Copying media file: 'images/Dolphin-Automatic-Toothpick-Holder.gif' 
DEBUG   -  Copying media file: 'images/logo.jpg' 
DEBUG   -  Copying media file: 'images/screenshot-0.1.png' 
DEBUG   -  Copying media file: 'theme/main.html' 
DEBUG   -  Copying media file: 'assets/images/favicon.png' 
DEBUG   -  Copying media file: 'assets/javascripts/bundle.f81dfb4d.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/bundle.f81dfb4d.min.js.map' 
DEBUG   -  Copying media file: 'assets/javascripts/lunr/min/lunr.ar.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/lunr/min/lunr.da.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/lunr/min/lunr.de.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/lunr/min/lunr.du.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/lunr/min/lunr.es.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/lunr/min/lunr.fi.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/lunr/min/lunr.fr.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/lunr/min/lunr.hu.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/lunr/min/lunr.it.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/lunr/min/lunr.ja.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/lunr/min/lunr.jp.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/lunr/min/lunr.multi.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/lunr/min/lunr.nl.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/lunr/min/lunr.no.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/lunr/min/lunr.pt.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/lunr/min/lunr.ro.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/lunr/min/lunr.ru.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/lunr/min/lunr.stemmer.support.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/lunr/min/lunr.sv.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/lunr/min/lunr.tr.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/lunr/min/lunr.vi.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/lunr/tinyseg.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/vendor.0ac82a11.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/vendor.0ac82a11.min.js.map' 
DEBUG   -  Copying media file: 'assets/javascripts/worker/search.4ac00218.min.js' 
DEBUG   -  Copying media file: 'assets/javascripts/worker/search.4ac00218.min.js.map' 
DEBUG   -  Copying media file: 'assets/stylesheets/main.19753c6b.min.css' 
DEBUG   -  Copying media file: 'assets/stylesheets/main.19753c6b.min.css.map' 
DEBUG   -  Copying media file: 'assets/stylesheets/palette.196e0c26.min.css' 
DEBUG   -  Copying media file: 'assets/stylesheets/palette.196e0c26.min.css.map' 
DEBUG   -  Building theme template: sitemap.xml 
DEBUG   -  Gzipping template: sitemap.xml 
DEBUG   -  Building theme template: 404.html 
DEBUG   -  Building markdown pages. 
DEBUG   -  Building page index.md 
DEBUG   -  Building page changelog.md 
DEBUG   -  Building page dev-env.md 
DEBUG   -  Building page faq.md 
DEBUG   -  Building page fundamentals-how-flipper-ktp-works.md 
DEBUG   -  Building page fundamentals-how-flipper-works.md 
DEBUG   -  Building page fundamentals-how-ktp-works.md 
DEBUG   -  Building page fundamentals.md 
DEBUG   -  Building page getting_started.md 
DEBUG   -  Building page how_to_help.md 
DEBUG   -  Building page recipes.md 
DEBUG   -  Building page releasing.md 
DEBUG   -  Building page support.md 
DEBUG   -  Building page api/flipper-ktp/index.md 
DEBUG   -  Building page api/flipper-ktp/alltypes/index.md 
DEBUG   -  Building page api/flipper-ktp/fr.afaucogney.mobile.flipper/index.md 
DEBUG   -  Building page api/flipper-ktp/fr.afaucogney.mobile.flipper/-build-config/index.md 
DEBUG   -  Building page api/flipper-ktp/fr.afaucogney.mobile.flipper/-build-config/-b-u-i-l-d_-t-y-p-e.md 
DEBUG   -  Building page api/flipper-ktp/fr.afaucogney.mobile.flipper/-build-config/-d-e-b-u-g.md 
DEBUG   -  Building page api/flipper-ktp/fr.afaucogney.mobile.flipper/-build-config/-init-.md 
DEBUG   -  Building page api/flipper-ktp/fr.afaucogney.mobile.flipper/-build-config/-l-i-b-r-a-r-y_-p-a-c-k-a-g-e_-n-a-m-e.md 
DEBUG   -  Building page api/flipper-ktp/fr.afaucogney.mobile.flipper/-ktp-flipper-plugin/index.md 
DEBUG   -  Building page api/flipper-ktp/fr.afaucogney.mobile.flipper/-ktp-flipper-plugin/-init-.md 
DEBUG   -  Building page api/flipper-ktp/fr.afaucogney.mobile.flipper/-ktp-flipper-plugin/get-id.md 
DEBUG   -  Building page api/flipper-ktp/fr.afaucogney.mobile.flipper/-ktp-flipper-plugin/on-connect.md 
DEBUG   -  Building page api/flipper-ktp/fr.afaucogney.mobile.flipper/-ktp-flipper-plugin/on-disconnect.md 
DEBUG   -  Building page api/flipper-ktp/fr.afaucogney.mobile.flipper/-ktp-flipper-plugin/run-in-background.md 
INFO    -  Documentation built in 0.37 seconds 
INFO    -  Copying '/Users/afaucogney/Documents/archi/git/FlipperKtp/site' to 'gh-pages' branch and pushing to GitHub. 
INFO    -  Your documentation should shortly be available at: https://afaucogney.github.io/flipper-ktp/ 
```

BTW, Is there any setup in github to allow a specific theme in pages ?

**Comment by waylan** [comment] 2020-12-19 22:34
Looking through the log, I don't see any problems. All of the relevant files were copied to `site`. All the deploy script does after a regular build is commit everything in `site` to the `gh-pages` branch and push the branch to GitHub. Is that log from your local machine (where everything works) or from the GH workflow (where things are apparently broken)?

Also, could you diff `index.html` on your server with a copy from a local build (using the same theme)? I'd like to see if there are any differences at all.

**Comment by waylan** [comment] 2020-12-21 19:13
We just merged in #2257. I wonder if that resolves this issue. If you want to test it, you can get the latest by installing directly from git with:

```
pip install -U git+https://https://github.com/mkdocs/mkdocs.git#egg=mkdocs
```

**Comment by afaucogney** [comment] 2020-12-22 11:42
Hello,

  There are a bunch of difference, but I have no idea if this is normal or not. Attached you will find a zip with both html and dependencies folders.

FYI : I just use local deployment

[Archive.zip](https://github.com/mkdocs/mkdocs/files/5729601/Archive.zip)

I'm going to try with the latest snapshot

**Comment by afaucogney** [comment] 2020-12-22 11:50
I'm running into issue with your command:
```
Collecting mkdocs
  Cloning https://https://github.com/mkdocs/mkdocs.git to /private/var/folders/hl/fj_qqv4x4fl0nm3sz678c3f8ym03_b/T/pip-install-u1sia0go/mkdocs
ERROR: Command errored out with exit status 128: git clone -q https://https://github.com/mkdocs/mkdocs.git /private/var/folders/hl/fj_qqv4x4fl0nm3sz678c3f8ym03_b/T/pip-install-u1sia0go/mkdocs Check the logs for full command output.

```
Any idea ?

Will wait first feedback about the files provided.

**Comment by waylan** [comment] 2020-12-22 19:24
> There are a bunch of difference, but I have no idea if this is normal or not. 

There should be no differences. If there are, then something weird is going on. I'll take a look when I get some time to see if I can figure out what.

> I'm running into issue with your command:

Sorry. I had`https://` twice in there. It should be:

```
pip install -U git+https://github.com/mkdocs/mkdocs.git#egg=mkdocs
```

**Comment by afaucogney** [comment] 2020-12-26 17:58
@waylan sorry, I could have find this issue (double http) by myself .... 
Just tryied to install it localy and deployed to gh, but nothing changed ! No theme, or at least the theme is not the same in local as in gh.

**Comment by waylan** [comment] 2020-12-28 15:51
I can't replicate your problem. I forked your repo to [waylan/flipper-ktp][1]. Then, without making any changes, I made a local clone and deployed:

```bash
git clone https://github.com/waylan/flipper-ktp.git
cd flipper-ktp/
mkdocs gh-deploy --theme mkdocs --force
```

I did override the theme with the `--theme` flag as I don't have `rtd-dropdown` installed. However, everything worked as expected. You can see the working site at <http://waylan.limberg.name/flipper-ktp/>.

I tried both the most recent release of MkDocs (1.1.2) and the current HEAD with no discernible difference.

My assumption is that your either have an issue with the theme you are using or something is weird about your local system configuration and/or GitHub account.

[1]: https://github.com/waylan/flipper-ktp

**Comment by waylan** [comment] 2021-04-07 17:40
This is being closed due to the inability to reproduce the reported problem. If more information if provided we can reopen it at that time.

**Closed by waylan** 2021-04-07 17:40 UTC
Labels: Needs information

**Comment by flywire** [comment] 2021-09-12 23:30
> I run successfully `mkdocs build`

Creating the `site` folder before `mkdocs gh-deploy` could be part of the issue - #2569

**Comment by stefnestor** [comment] 2021-09-18 02:39
I've been banging my head against this same ballpark for a bit, @afaucogney. I just got to a working [code](https://github.com/stefnestor/mkdocs) > [website](https://stefnestor.github.io/mkdocs/).

### Steps

AFAICT here's why

1. From [here](https://github.com/marketplace/actions/deploy-mkdocs#building-with-github_token) you know you have to enable Repo > Settings > Pages & set it to `gh-pages/root`
2. Setup basic [mkdocs.yml](https://github.com/stefnestor/mkdocs/blob/f1e247f7e5afcf19c77d9360b82686639f3a01fc/mkdocs.yml)
3. Setup basic [docs/index.md](https://github.com/stefnestor/mkdocs/blob/f1e247f7e5afcf19c77d9360b82686639f3a01fc/docs/index.md)
4. Setup basic [.github/workflows/docs.yml](https://github.com/stefnestor/mkdocs/blob/f1e247f7e5afcf19c77d9360b82686639f3a01fc/.github/workflows/docs.yml)

Basically what y'all have been talking about.

### The Difference

What was biting me was updates to the `.github/workflow/docs.yml` & `mkdocs.yml` wouldn't get picked up until the `docs/index.md` was changed 😞. 

So after ☝️ steps, I added a random space to my `docs.index.md` & pushed and now have a [published site w/correct theme](https://stefnestor.github.io/mkdocs/). I'd sworn I'd tested that flow before, but apparently not OR this didn't work until after setting `theme:readthedocs` and then setting back to `theme:material`. 

<details><summary>screenshots</summary>

For future search discoverability (because will expire or are private):

![image](https://user-images.githubusercontent.com/26751266/133869321-adb17408-ed6e-4da3-ac93-cc44914d7cba.png)

![image](https://user-images.githubusercontent.com/26751266/133869338-79dcd8bf-ae94-47b5-a5fc-0fa328ab7057.png)

![image](https://user-images.githubusercontent.com/26751266/133869372-e4dccba7-008f-432b-8582-e180357f218a.png)

</details>

### Thanks!

A thanks to @waylan & @afaucogney for leaving both code & websites up for my A-B testing to recognize it's more of a race condition or cache issue than a literal code write/setup issue & @Andre601 for his snippet [here](https://github.com/mkdocs/mkdocs/discussions/2569#discussioncomment-1310350) that @flywire linked for us 🙏🏼 ☺️
