### ISSUE TITLE
About  navigation bar

### ISSUE THREAD

**Issue by ashidamana** [mkdocs/mkdocs#1229] opened 2017-05-25 04:16 UTC
#### When adding pages,if I dont't want to add it to the navigation bar but just adding pages,What should I do then?

**Comment by bfxy** [comment] 2017-05-25 11:04
The feature is in development, but you can use [this](https://github.com/mkdocs/mkdocs/issues/699#issuecomment-157691209) or another workaround suggested in that thread.

**Comment by waylan** [comment] 2017-05-25 12:45
This is a duplicate of #699.

**Closed by waylan** 2017-05-25 12:45 UTC
