### ISSUE TITLE
Japanese search does not work (Excluding mkdocs-material)

### ISSUE THREAD

**Issue by fu-sen** [mkdocs/mkdocs#2333] opened 2021-03-22 01:47 UTC
Search does not work when currently using MkDocs in Japanese:
![スクリーンショット 2021-03-22 10 16 28](https://user-images.githubusercontent.com/5434159/111929386-8c48c080-8af9-11eb-9f91-c0573b622c85.jpg)
![スクリーンショット 2021-03-22 10 16 34](https://user-images.githubusercontent.com/5434159/111929394-8fdc4780-8af9-11eb-94d4-ecfa4e72b851.jpg)

This is related to [lunr-language](https://github.com/MihaiValentin/lunr-languages), but this issue seems to be a problem with MkDocs implementing lunr.
Therefore, it was reported here.

___

The lunr-language README does not mention the Japanese implementation, but please note that the demo has a separate Japanese language.
https://github.com/MihaiValentin/lunr-languages/tree/master/demos

For example [demo-browser-ja.html](https://github.com/MihaiValentin/lunr-languages/blob/master/demos/demo-browser-ja.html):
```
<head>
    <title></title>
    <meta charset="UTF-8">
    <script src="../test/lunr/lunr-0.7.0.min.js"></script>
    <!--<script src="../test/lunr/lunr-2.0.0-alpha.5.js"></script>-->
    <script src="../lunr.stemmer.support.js" charset="UTF-8"></script>
    <script src="../tinyseg.js" charset="UTF-8"></script>
    <script src="../lunr.ja.js" charset="UTF-8"></script>
</head>
```

This file structure is not considered by MkDocs:
https://github.com/mkdocs/mkdocs/tree/master/mkdocs/contrib/search

This Pull request tried to accommodate this:
https://github.com/mkdocs/mkdocs/pull/2178

___

This issue is not applicable only to **mkdocs-material**. **mkdocs-material** implements lunr on its own.
https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/javascripts/integrations/search/worker/main/index.ts:
```
async function setupSearchLanguages(
  config: SearchIndexConfig
): Promise<void> {
  let base = "../lunr"

  /* Detect `iframe-worker` and fix base URL */
  if (typeof parent !== "undefined" && "IFrameWorker" in parent) {
    const worker = document.querySelector<HTMLScriptElement>("script[src]")!
    const [path] = worker.src.split("/worker")

    /* Prefix base with path */
    base = base.replace("..", path)
  }

  /* Add scripts for languages */
  const scripts = []
  for (const lang of config.lang) {
    if (lang === "ja") scripts.push(`${base}/tinyseg.js`)
    if (lang !== "en") scripts.push(`${base}/min/lunr.${lang}.min.js`)
  }

  /* Add multi-language support */
  if (config.lang.length > 1)
    scripts.push(`${base}/min/lunr.multi.min.js`)

  /* Load scripts synchronously */
  if (scripts.length)
    await importScripts(
      `${base}/min/lunr.stemmer.support.min.js`,
      ...scripts
    )
}
```

Please note that **mkdocs-material** is different when you hear information related to MkDocs Japanese.
Currently, many Japanese MkDocs sites consider this search and **mkdocs-material** is selected.

This is likely to be the same in Chinese. In the future, Korean will also be included here.

**Comment by waylan** [comment] 2021-03-22 14:14
I am closing this as a duplicate of #2178. I realize the fix there currently does not address all of the issues, but that fix is incomplete. When that fix is completed, then it should address all of the issues raised here.

**Closed by waylan** 2021-03-22 14:14 UTC
