### ISSUE TITLE
Collapsable ReadTheDocs Theme

### ISSUE THREAD

**Issue by DirtyCajunRice** [mkdocs/mkdocs#1254] opened 2017-07-13 19:29 UTC
ReadTheDocs theme does not act like docs.readthedocs.io
I would like the expandable/collapsable navigation on the left bar. 
Is this possible?

**Comment by waylan** [comment] 2017-07-13 23:00
I'm closing this as a duplicate of #588.

**Closed by waylan** 2017-07-13 23:00 UTC
