### ISSUE TITLE
"Bad path" error when using external URLs in extra_javascript

### ISSUE THREAD

**Issue by EdyJ** [mkdocs/mkdocs#1346] opened 2017-11-12 23:37 UTC
Including an external URL in the extra_javascript list causes a "Bad path" error while building the sitemap file.

mkdocs version 0.17.1, Windows

The extra_javascript line in mkdocs.yml is:

    extra_javascript: [ 'http://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML', 'js/mathjaxhelper.js', 'js/fabric.custom.min.js', 'js/texturecanvas.js', 'js/imagegallery.js', 'js/clickview.js' ]

Final lines in the verbose output:

```
DEBUG   -  Config value: 'copyright' = None
DEBUG   -  Config value: 'strict' = True
DEBUG   -  Config value: 'docs_dir' = 'D:\\Coding\\vehicle-physics-docs\\docs'
DEBUG   -  Config value: 'extra_javascript' = ['http:\\\\cdnjs.cloudflare.com\\ajax\\libs\\mathjax\\2.7.1\\mathjax.js?config=tex-ams_html', 'js\\mathjaxhelper.js', 'js\\fabric.custom.min.js', 'js\\texturecanvas.js', 'js\\imagegallery.js', 'js\\clickview.js']
INFO    -  Cleaning site directory
DEBUG   -  Copying static assets from c:\python34\lib\sitepackages\mkdocs\contrib\legacy_search\templates
DEBUG   -  Copying static assets from the docs dir.
DEBUG   -  Building template: sitemap.xml

Bad path: http:\\cdnjs.cloudflare.com\ajax\libs\mathjax\2.7.1\mathjax.js?config=tex-ams_html
```

Just removing the "https://" part from the extra_javascript entry solves the error and the site builds correctly, but obviously the URL doesn't work.

Let me know if you need any other information.
Thanks!

**Comment by waylan** [comment] 2017-11-12 23:54
This is a duplicate of #1336. The fix will be available in the next release (0.17.2).

**Closed by waylan** 2017-11-12 23:54 UTC
