### ISSUE TITLE
[RFC] add pages without adding them to the main menu

### ISSUE THREAD

**Issue by gsouf** [mkdocs/mkdocs#873] opened 2016-03-24 07:48 UTC
Hi,
Correct me if I'm wrong, but currently there is now way to add a page to the doc without adding it to the main menu (``pages`` configuration). 
While it is good to keep things stable it is really annoying for instance when we want to add pages that will only be accessible from some other page, or from footer links. 
As an example in my project I have many side pages that don't need to be accessible from the main menu and I'm forced to put them all in the menu, making the menu harder to navigate.

What do you think about an additional config to put pages that wont be in the menu?

**Comment by waylan** [comment] 2016-03-24 12:46
This is  a duplicate of #699.

**Closed by waylan** 2016-03-24 12:46 UTC
