### ISSUE TITLE
Error on accessing page.meta.foo

### ISSUE THREAD

**Issue by lakonis** [mkdocs/mkdocs#2341] opened 2021-03-26 14:43 UTC
Hello,
I am trying to add a few additional `<meta>` from the `main.html` template through custom_theme. I succeeded to do so, but I cannot use `page.meta` correctly. 

`{{ page.meta }}` returns no error and it lists all pairs "key-value" as `'key' : 'value'`, but when calling `{{ page.meta.foo }}`, I get this error on build or serve: 
```bash
  File "~/.local/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "~/.local/lib/python3.8/site-packages/livereload/handlers.py", line 69, in poll_tasks
    filepath, delay = cls.watcher.examine()
  File "~/.local/lib/python3.8/site-packages/livereload/watcher.py", line 119, in examine
    func()
  File "~/.local/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 136, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "~/.local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 285, in build
    _build_theme_template(template, env, files, config, nav)
  File "~/.local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 108, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "~/.local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 87, in _build_template
    output = template.render(context)
  File "~/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "~/.local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "~/.local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "~/.local/lib/python3.8/site-packages/mkdocs/themes/readthedocs/search.html", line 1, in top-level template code
    {% extends "main.html" %}
  File "~/githn/HUMANUM/documentation/custom_theme/main.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "~/.local/lib/python3.8/site-packages/mkdocs/themes/readthedocs/base.html", line 5, in top-level template code
    {%- block site_meta %}
  File "~/githn/HUMANUM/documentation/custom_theme/main.html", line 26, in block "site_meta"
    <!-- une tentative {{ page.meta.description }} -->
  File "~/.local/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'None' has no attribute 'meta'
```
What do I do wrong ?
Thank you !

**Comment by waylan** [comment] 2021-03-26 15:06
Based on these two lines of your traceback:

```
  File "~/.local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 285, in build
    _build_theme_template(template, env, files, config, nav)
  File "~/.local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 108, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
```

I'm assuming that the current template being rendered is not for a page (probably a static template). As it is not a page, it does not have the `page` variable defined. Notice that the error suggests that `page` is `None`, which collaborates by assumption. To avoid the error, you need to wrap the call to `page` in an `if` statement:

```django
{% if page %}{{ page.meta.description }}{% endif %}
```

That way, the `description` will be included for "pages", but will be blank for static templates and other non-page documents.

**Comment by waylan** [comment] 2021-03-26 15:18
I am converting this to a discussion, as it is a support request, not a bug report or feature request.

**Closed** 2021-03-26 15:19 UTC
