### ISSUE TITLE
readthedocs mobile view not showing menu button

### ISSUE THREAD

**Issue by shravantc** [mkdocs/mkdocs#553] opened 2015-05-25 05:39 UTC
The mobile view does not show a index drop down(or the menu button) on top left corner.

![screenshot from 2015-05-25 11 12 48](https://cloud.githubusercontent.com/assets/10970993/7792363/fdf5b83c-02ce-11e5-933c-7d370856b72e.png)

Found the same issue in the mkdocs.readthedocs.org
![screenshot from 2015-05-25 11 13 30](https://cloud.githubusercontent.com/assets/10970993/7792369/16d07482-02cf-11e5-86da-ab1f95e978c9.png)

**Comment by shravantc** [comment] 2015-05-25 05:41
Attached is a image with active menu button in mobile view
![screenshot from 2015-05-25 11 11 01](https://cloud.githubusercontent.com/assets/10970993/7792351/bf8e6c42-02ce-11e5-9ae7-e710683d1ac4.png)

**Comment by shravantc** [comment] 2015-05-25 05:44
The menu button is visible in projects using sphinx-rst.
![screenshot from 2015-05-25 11 14 20](https://cloud.githubusercontent.com/assets/10970993/7792380/345fb6ca-02cf-11e5-8f47-170b4ec89876.png)

**Comment by d0ugal** [comment] 2015-05-25 08:16
Okay, so I think this is a duplicate of #348 but I'll leave this open until I can verify. This issue is that readthedocs are on an old version of MkDocs.

**Comment by d0ugal** [comment] 2015-05-25 08:18
Actually, thinking about it more we should track this issue for updates as this is specific to a fixed bug rather than the problem described here: https://github.com/mkdocs/mkdocs/issues/554

**Closed** 2015-05-25 08:21 UTC
Labels: Bug

**Comment by shravantc** [comment] 2015-05-25 08:43
Thanks @d0ugal , watch added . will look forward for the update :)
