### ISSUE TITLE
MkDocs can't build from another directory

### ISSUE THREAD

**Issue by jimporter** [mkdocs/mkdocs#676] opened 2015-07-01 03:44 UTC
I'm working on supporting out-of-tree builds for my project, and would like my build files to contain recipes for generating the documentation. However, paths in the `mkdocs.yml` file are evaluated relative to the current working directory, not relative to `mkdocs.yml`'s directory. Is there a reason for this, or is it just an oversight? If it is just an oversight, I'd be happy to write the patch.

(This also has the nice side effect that `site_dir` is automatically ignored by version control, since it's already inside of your build dir.)

**Comment by d0ugal** [comment] 2015-07-01 06:43
This is a duplicate of #543. Which was closed, but as I am not totally convinced, I've reopened it for us to discuss there.

**Closed by d0ugal** 2015-07-01 06:43 UTC
