### ISSUE TITLE
[Feature Request] Add support for GitHub wiki documentation

### ISSUE THREAD

**Issue by jamesrhea** [mkdocs/mkdocs#1437] opened 2018-03-14 17:22 UTC
[Docs for the RetroPie project](https://retropie.org.uk/docs/) use MkDocs and pull in content from their repository wiki. The "edit page" button (pencil icon) link on their docs site did not work because it directed to incorrect URLs. The RetroPie team implemented a workaround by creating a php script that redirects to the correct page. But it would be nice if mkdocs could support this use case out of the box.

The available configuration options (specifically, `repo_url` and `edit_uri`) do not currently support wiki URLs.

For example, the default "edit page" link on this page https://retropie.org.uk/docs/ went to https://github.com/RetroPie/RetroPie-Setup/edit/master/docs/index.md, but the correct URL should have been https://github.com/RetroPie/RetroPie-Setup/wiki/Home/_edit

For additional context and exploratory troubleshooting, see the now-closed issue at RetoPie-Docs: https://github.com/RetroPie/RetroPie-Docs/issues/1

**Comment by jamesrhea** [comment] 2018-03-14 17:40
Is this JavaScript snippet able to provide the requested functionality?

https://github.com/mkdocs/mkdocs/wiki/MkDocs-Recipes#associate-github-page-with-current-mkdoc-page

**Comment by waylan** [comment] 2018-03-14 19:34
Thanks for the request. However, I'm closing this as a duplicate of #1378. While that issue is about BitBucket, its clear that the solution offered there should also address the more general use case and result in a solution here. I've made reference to this issue form there, so it shouldn't get forgotten.

As an aside, it should be noted that Bitbucket has never truly had working edit links. The "edit link" simply points to the document as it is hosted on Bitbucket. The user still needs to click the "edit" button on the Bitbucket site to actually edit the document (for the reasons explained in #1378). You can currently get the same behavior with the GitHub wiki (the `/_edit` sting would be missing from the end). In other words, set your `edit_uri` to `wiki/`. It may not be ideal, but it is a stop-gap until a better implementation can be developed.

**Closed** 2018-03-14 19:34 UTC

**Comment by flywire** [comment] 2020-12-13 10:27
Can someone confirm this comment in a closed issue is seen to save me opening a new issue?

I'd like to render GitHub wiki pages and MkDocs works fine with two exceptions:
1. The first GitHub wiki pages are at the wiki root level which generates:

    `ERROR   -  Config value: 'docs_dir'. Error: The 'docs_dir' should not be the parent directory of the config file. Use a child directory instead so that the 'docs_dir' is a sibling of the config file.`

   `https://github.com/[user]/[repo].wiki/*.md`

1. The first GitHub wiki page is `home.md` but MkDocs requires an `index.md`

I'd appreciate a workaround to edit the wiki locally in windows to avoid both these issues. Despite many issue comments I'm not clear on the best way to handle the issue.

-----

**mkdocs.yml**

```
site_name: GitHubWiki

edit_uri: ''

docs_dir: ''

nav:
    - Home: index.md
    # - Home: home.md  # what I actually want
```

**Comment by waylan** [comment] 2020-12-13 14:14
@flywire there is no way to work around those two issues and we have no plans to provide one.

**Comment by flywire** [comment] 2020-12-14 21:37
I appreciate the reply so now I'm interested in a personal fork for this use case. Can you explain what the design issue is with allowing docs in the root folder, renaming index.md to home.md, and where the code is? (Obviously a browser is looking for index.html.)

-----

I expect my workaround would cause git to go crazy:
* move everything to a docs directory except `mkdocs.yml` (and `.*` files if any) then `rename .\docs\home.md .\docs\index.md`
* move directory back again and rename `index.md` before syncing wiki repo

-----

I thought there might have been a way to alias the directory and/or filename without changing MkDocs.

**Comment by waylan** [comment] 2020-12-16 13:45
> Can you explain what the design issue is with allowing docs in the root folder

MkDocs will copy everything in the `docs_dir` to the built site. Of course, it should never copy the config file and the only way to avoid that is to not allow the config file to be in the `docs_dir`. To allow this would require a fundamental change in how MkDocs works. While it may be possible to make that change, then MkDocs would be a different product which we are not interested in making.

We already allow `readme.md` to be converted to `index.html`. Adding a third option `home.md` just adds more complexity. And the only reason to add support for that would be to explicitly support GitHub's wiki, which would mean we would need to support everything else about GitHub's wiki, which we are not interested in doing. Again, that would be a different product that what we are interested in providing.

**Comment by flywire** [comment] 2020-12-19 04:13
With respect @waylan, very trivial tweeks are required and your response expresses personal disinterest with no technical constraints. Regardless, it is useful advice.

This works for a GitHub wiki:

`docs_dir: ''` - insert [return](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/config/config_options.py#L370) to disable a function that does nothing except raise a ValidationError for an empty `docs_dir`
`mkdocs.yml` - add to [list](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/structure/files.py#L218) so it isn't copied - not required if [Allow config file with dot prefix: .mkdocs.yml](https://github.com/mkdocs/mkdocs/issues/2164) accepted

As you say `readme.md` is already allowed as an alternate `index.html` file, unfortunately each use is hardcoded rather than being contained in a constant. So:

`Home.md` - add to [list](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/structure/files.py#L141) and update [sort_files compare](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/structure/files.py#L250-L252)

Equivalent relevant messages are returned as with `readme.md`:
```
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - Home.md
WARNING -  A relative path to 'index.html' is included in the 'nav' configuration, which is not found in the documentation files
```

Sample mkdocs.yml

```yml
site_name: testwiki

docs_dir: ''

use_directory_urls: false

nav:
    - Home: index.html
    - dummy.md
 ```

**Comment by flywire** [comment] 2020-12-29 07:06
https://github.com/flywire/mkdocs

> **Note:** This is a tweaked version of MkDocs so you must choose which version to run.
>
> A python virtual environment is suggested for your wiki project - see https://github.com/flywire/mkdocs/wiki/Development

**Comment by waylan** [comment] 2020-12-29 20:41
Generally we would expect any changes in behavior to be implemented in a third-party plugin and/or theme rather than by distributing a modified copy of MkDocs. While the license does allow distributing a modified copy, that could confuse users if there is no easy way to distinguish between them (such as changing the name of the package and/or using a different versioning scheme). After all we can't provide support for your fork. If users think they are using MkDocs and come here for support but we can't replicate the issue, then they will be lost.

To be clear, I'm not demanding anything outside of what the license requires. However, I am suggesting you consider how a fork with the same name could be confusing to users.

**Comment by flywire** [comment] 2020-12-29 23:14
Thanks for your guidance and I fully agree. I expected this to be clear by highlighting the incompatibility with Mkdocs and managing it through a virtual environment. (I need to run MkDocs and this fork too. )

Given:
- no way to work around issues, including as a plugin I assume
- the minor tweaks make this a different product but it needs the full MkDocs environment (including documentation) to work

Where would the code be to rename it to `MkDocsW` without changing basic commands like `MkDocs serve`? (Worst case just change displayed name.)

**Comment by MichelZ** [comment] 2022-05-23 07:31
I have created a plugin now for GitHub Wiki that changes the link to the correct format... For those needing GitHub Wiki support, give it a try?
https://pypi.org/project/mkdocs-github-wiki-edit-url/

**Comment by oprypin** [comment] 2022-08-13 13:13
Check out a new proposal https://github.com/mkdocs/mkdocs/issues/1378#issuecomment-1214158134
