### ISSUE TITLE
mkdocs  throws warning on unicode

### ISSUE THREAD

**Issue by anandchida** [mkdocs/mkdocs#771] opened 2015-12-10 14:55 UTC
Fedora 23 x86_64
$ python --version
Python 2.7.10

mkdocs, version 0.14.0

Any mkdocs command throws the following warning

$ mkdocs new project_name
/usr/lib/python2.7/site-packages/mkdocs/cli.py:86: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/lib/python2.7/site-packages/mkdocs/cli.py:100: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/lib/python2.7/site-packages/mkdocs/cli.py:125: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/lib/python2.7/site-packages/mkdocs/cli.py:145: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/lib/python2.7/site-packages/mkdocs/cli.py:176: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/lib/python2.7/site-packages/mkdocs/cli.py:194: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
INFO    -  Creating project directory: private 
INFO    -  Writing config file: private/mkdocs.yml 
INFO    -  Writing initial docs: private/docs/index.md

**Comment by waylan** [comment] 2015-12-10 14:59
This is another duplicate of #703. As explained elsewhere, this is not actually a concern with the way MkDocs uses it and therefore the warning will be turned off in the next release.

**Comment by d0ugal** [comment] 2015-12-10 16:30
and fast becoming the no. 1 reason to find time to make a release :)

**Closed by d0ugal** 2015-12-10 16:30 UTC

**Comment by waylan** [comment] 2015-12-10 16:35
Ahh, I see you got my hint. ;-)

**Comment by d0ugal** [comment] 2015-12-10 17:02
I am tempted to release a 0.14.1 to fix just this as that should require no support, I am more concerned about releasing a 0.15 based on master as I have very little time to support any issues that come from it.

**Comment by waylan** [comment] 2015-12-10 19:21
A 0.14.1 release might make a lot of sense. However, my recollection is that there has been a number of changes since 0.14.0 and I have seen people asking for a release for many of those fixes. I expect most would prefer a 0.15 release, but only you know what time you can give to the project.
