### ISSUE TITLE
Outdated discussion group link

### ISSUE THREAD

**Issue by manosbatsis** [mkdocs/mkdocs#1889] opened 2019-10-19 01:10 UTC
[mkdocs.org](https://www.mkdocs.org/#getting-help) points to a google group that doesn't seem to exist, you might want to remove the link:

```
This group either doesn't exist, or you don't have permission to access it. 
If you're sure this group exists, contact the Owner of the group and ask them to give you access.
```
The only reason i tried the group was to thank you for your work. I've tried a bunch of project doc generators over the years and long story short MKDocs feels so much better. Cheers!

**Comment by waylan** [comment] 2019-10-20 22:00
I just checked and the group works fine. And that link takes me right to it. Not sure what the problem could be.

**Comment by manosbatsis** [comment] 2019-10-20 22:21
Just went through "Getting help" and the issue persists. Not sure if it's google's or mine or whatnot. Feel free to close the issue if you have no use for it.

![mkdocs-issue](https://user-images.githubusercontent.com/3016927/67167310-09ba4f80-f3a1-11e9-9187-2a7d803806cc.png)

**Comment by trel** [comment] 2019-10-20 22:55
I see the same error.

**Comment by facelessuser** [comment] 2019-10-21 00:21
I get the same error. Maybe it is a permissions thing?

**Comment by waylan** [comment] 2019-10-21 01:27
So I don't have admin access to the group and I'm not sure how it's set up. But I'm assuming the issue is described in the second half of the error message: you don't have permission. I thought anyone could join the group. At least that's what I remember when I joined way back when. Perhaps Google made some changes?

@d0ugal or @tomchristie can one of you look into this?

**Comment by d0ugal** [comment] 2019-10-21 06:16
I think @tomchristie set this up, so he should be able to help.

**Comment by tomchristie** [comment] 2019-10-21 11:39
No idea why it was in that state, but looks like it had become "only visible to members of the group". I've changed that to "everyone on the internet", and the issue looks resolved to me now.

Once someone's confirmed here let's close this off.

**Comment by petervk2** [comment] 2019-10-21 11:52
Yup, that looks better, thanks!

**Comment by waylan** [comment] 2019-10-21 12:50
Based on @petervk2 feedback, I'm closing this as resolved. Thanks to everyone who offered input.

**Closed by waylan** 2019-10-21 12:50 UTC
