### ISSUE TITLE
readthedocs long side nav does not scroll to focus

### ISSUE THREAD

**Issue by gurnard123** [mkdocs/mkdocs#1101] opened 2016-11-24 10:33 UTC
With a long side nav, many pages
Click an element that is below the bottom of the browser.
The whole screen is refreshed and the side nav returns to the top.
So the current page is not visible in the side nav.

Should the current page not be scrolled to in the side nav, or why is the whole page loaded when clicking the side nav.

The attached image expected.png is what I would expect to get (or with the search box on top)
The attached image actual.png is what I get, which leaves the user lost to be honest.
**Expected**
![expected](https://cloud.githubusercontent.com/assets/8625592/20595291/a7e29458-b239-11e6-98b2-74faf38a6892.png)

**Actual**
![actual](https://cloud.githubusercontent.com/assets/8625592/20595301/b02edb62-b239-11e6-80fc-0796693d26e0.png)

**Comment by waylan** [comment] 2016-11-24 16:42
What does the Sphinx theme (of the same name) do here? I expect this is part of #588.

**Comment by gurnard123** [comment] 2016-11-25 07:10
Thanks for the reply. Where can I get the Sphinx theme?  I see in #588 there is a link to a modified ReadTheDocs theme that is no longer maintained which puts me off a bit. But what that offers would solve my issues.  Or do you have a link to the Sphinx theme I cannot find it anywhere.

**Comment by waylan** [comment] 2016-11-25 15:17
Our `readthedocs` theme is a clone of the Sphinx theme of the same name. The Sphinx theme is the default theme used by the ReadTheDocs service and can be found [@snide/sphinx_rtd_theme][1]. It won't work for MkDocs though (as it is a theme for Sphinx -- a MkDocs competitor of sorts). However, the point of #588 is to update our clone to the current feature-set of that theme. Likely much (most?) of the CSS and JavaScript changes could be copied over as-is. The problem is the time it would take to tweak everything for the slightly different HTML. The biggest problem is that Sphinx uses RestructuredText while MkDocs uses Markdown and the HTML generated is structurally different as per the specs of each markup language. A few other differences exist in the templates due to different feature-sets between MkDocs and Sphinx. Everyone wants the work to be done, but no one seems to have the time to do it.

In any event, I am closing this as a duplicate of #588.

[1]: https://github.com/snide/sphinx_rtd_theme

**Closed by waylan** 2016-11-25 15:17 UTC
