### ISSUE TITLE
Anchor links don't scroll the page when opened in a new tab

### ISSUE THREAD

**Issue by ansman** [mkdocs/mkdocs#3409] opened 2023-10-01 03:07 UTC
Previously, mkdocs would support opening a page that includes a an anchor link. But now the user just remains on the top of the page.

Here is an example: https://auto-dagger.ansman.se/0.10.0/usage/auto-bind/#generics

Clicking anchor links still work as expected.

You can see the `mkdocs.yml` file I'm using here: https://github.com/ansman/auto-dagger/blob/cd7ae64c27aaeaf780331aa190495f3db12d8d01/src/doc/mkdocs.yml

**Comment by pawamoy** [comment] 2023-10-01 09:23
IIUC, "scroll to anchor" is a browser feature, and MkDocs plays no part in that. Have you tried with different browsers? Which one is not scrolling to the anchor?

**Comment by ansman** [comment] 2023-10-01 14:33
It is a browser feature but there are lots of ways to break it (rendering content dynamically, interference from JS to mention a few).

Neither Safari on iOS/macOS nor Chrome on iOS works.

It works fine to click the link in the sidebar but clicking the link from the description just leads to the top of the page rather than the "generics" section.

**Comment by pawamoy** [comment] 2023-10-01 14:44
Looking at the page source, the heading is static (not generated dynamically): `<h2 id="generics">Generics<a class="headerlink" href="#generics" title="Permanent link">&para;</a></h2>`.

- Firefox Linux ✅
- Firefox Android ✅
- Firefox iOS ❔
- Firefox macOS ❔
- Chrome Linux ✅
- Chrome Android ✅
- Chrome iOS ❌
- Chrome macOS ❔
- Safari iOS ❌
- Safari macOS ❌

I'm definitely not an expert here. Maybe other users (@squidfunk since the theme is Material for MkDocs) could test the link on iOS/macOS with Safari, Chrome and Firefox.

**Comment by squidfunk** [comment] 2023-10-02 07:21
If it's an issue with Material for MkDocs, please upgrade to the latest version as @pawamoy already suggested. If the problem persists, please create a [bug report](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/) with a [reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) and we can look into it. Before, please make sure that it does not happen when you're using the `mkdocs` and `readthedocs` theme. We're currently not aware of such an issue.

**Comment by squidfunk** [comment] 2023-10-02 08:06
Ah, you're using instant loading. Yes, this problem was reported in https://github.com/squidfunk/mkdocs-material/issues/3797 and fixed in [9.1.1](https://squidfunk.github.io/mkdocs-material/changelog/#9.1.1).

**Closed** 2023-10-02 09:46 UTC
