### ISSUE TITLE
Navigation not working on Microsoft SharePoint

### ISSUE THREAD

**Issue by Cuurjol** [mkdocs/mkdocs#1573] opened 2018-08-01 13:57 UTC
Hello.

I faced the problem about working navigation-links in my project-documentation. I created my project-documentation and published all the content into Microsoft SharePoint platform. Url web-site where I published all the content: http://ilyin1/DocLib/

mkdocs.yml:
```
site_name: ИНСТРУКЦИЯ ПО СЭД ДЛЯ ТЕХНОЛОГОВ
theme: 
    name: rtd-dropdown
    custom_dir: custom_theme
extra_css: [extra.css]
use_directory_urls: false
pages:
    - Введение: index.md
    - Создание и заполнение справочников: directory.md
    - Создание сайтов картотек: cardIndexSites.md
    - Создание типов контента: contentType.md
    - Создание групп документов: documentGroups.md
    - Настройка сайтов картотек: settingUpCardIndexSites.md
    - Настройка процессов: processConfiguration.md
    - Создание рабочих мест: workplace.md
    - Настройка профиля: profileSetup.md
    - Настройка доступа: accessSetup.md
```

index.md:
```
## Порядок настройки системы:

1. [Создание и заполнение справочников](directory.md).
2. [Создание сайтов картотек](cardIndexSites.md)
3. [Создание типов контента](contentType.md) (карточек документов/проектов).
4. [Создание групп документов](documentGroups.md).
5. [Настройка сайтов картотек](settingUpCardIndexSites.md).
6. [Настройка процессов](processConfiguration.md).
7. [Создание рабочих мест](workplace.md).
8. [Настройка профиля](profileSetup.md): категории задач, персональные оповещения, типовые формулировки, шаблоны заполнения форм, управление замещением.
9. [Настройка доступа](accessSetup2.md).
```

I noticed that two files (mkdocs.yml and index.md) form links differently. For example:

1. mkdocs.yml -> `Создание и заполнение справочников: directory.md` -> `http://ilyin1/directory/index.html`
2. index.md -> `[Создание и заполнение справочников](directory.md)` -> `http://ilyin1/DocLib/directory/index.html`

Whether it is possible somehow in a file `mkdocs.yml` to make so that links for navigation were formed not so `http://ilyin1/directory/index.html`, and so `http://ilyin1/DocLib/directory/index.html`?

A similar situation occurs when I try to work with my project-documentation offline in File System. In the navigation I get links of this kind:

mkdocs.yml:
```
file:///index.html
file:///directory/index.html
etc
```

index.md:
```
file:///C:/Python/my-project/site/index.html
file:///C:/Python/my-project/site/directory/index.html
etc
```

I apologize in advance if this is somewhere written in the documentation, and I did not notice it.

**Comment by waylan** [comment] 2018-08-01 14:14
I am unfamiliar with the the Microsoft SharePoint platform. However, MkDocs default settings assume that the files will be served by a server which understands [index files][1]. If Microsoft SharePoint does not, then it is not likely to work well as a server for a MkDocs generated site.

If you are browsing the files on the file system (without a server) then you should set the [use_directory_urls][2] config setting to `False`. That will cause the navigation to point directly at the files, rather than directories. This has been improved even further in MkDocs version 1.0 (likely to be released in a few days) as in the new version we no longer put every file in an index file when `use_directory_urls` is `False`.

[1]: https://en.wikipedia.org/wiki/Webserver_directory_index
[2]: https://mkdocs.org/user-guide/configuration#use_directory_urls

**Comment by Cuurjol** [comment] 2018-08-02 07:14
I set the use_directory_urls config setting to False. Anyway links are formed the way I indicated in my first message on File System:

mkdocs.yml (Navigation links):
```
file:///index.html
file:///directory/index.html
etc
```
index.md (simple html-page where are the links):
```
file:///C:/Python/my-project/site/index.html
file:///C:/Python/my-project/site/directory/index.html
etc
```

But I accidentally found this topic in the list of other topics and you said that on the file system this is the normal behavior of the navigation links [#1367](https://github.com/mkdocs/mkdocs/issues/1367). I'm not sure that this is normal behavior for working with my project-documentation offline. Can you comment on this situation?


Second Question.
> However, MkDocs default settings assume that the files will be served by a server which understands index files.

Ok. Can I change the default settings? If this is possible, what I should do? I want that after my custom settings and command execution `python -m mkdocs build` all links are formed the same way, for example:

1.  mkdocs.yml (Navigation links) -> `Создание и заполнение справочников: directory.md` -> `http://ilyin1/DocLib/directory/index.html`
2. index.md (simple html-page where are the links) -> `[Создание и заполнение справочников](directory.md)` -> `http://ilyin1/DocLib/directory/index.html`

**Comment by waylan** [comment] 2018-08-02 13:48
It appears that you need to use version 1.0 which will be released in the next few days. You can try the release candidate now with `pip install mkdocs=1.0rc1`. In version 1.0, if you set `use_directory_urls: False`, then the only URLs which would end with `index.html` are pages which start out as `index.md`. Unfortunately, that is not the case in previous versions. In the previous version all pages are put in `index.html` pages regardless of any settings with no way to override it.

Also, the navigation code has been rewritten in 1.0 so you should never get any URLs in the navigation which start with a `/` unless you specifically include one in the `nav` config setting.

Regardless, MkDocs is primarily designed to be used behind a traditional web server. In any other use case, things are not going to work as smoothly. There is even some debate regarding whether we should support the local file system (`file://`). As it is now, with `use_directory_urls: False`, it mostly works, but a few things are known to be broken (the search feature) with no plan to fix them.

**Comment by Cuurjol** [comment] 2018-08-02 13:57
I can't execute command line: `pip install mkdocs=1.0rc1`

https://image.ibb.co/hENNQe/13.png

**Comment by trel** [comment] 2018-08-02 14:00
You missed the last '1' after 'rc'.

**Comment by waylan** [comment] 2018-08-02 14:01
Look at that again. You have a  typo. You are missing the `1` at the end. Also, if you are upgrading from a previously installed version, you may need to include the `-U` flag.

**Comment by Cuurjol** [comment] 2018-08-03 13:47
Ok, I see. I have done it, The problem is solved. I apologize for my inattentiveness.

I still have a few questions for you:

> As it is now, with use_directory_urls: False, it mostly works, but a few things are known to be broken (the search feature) with no plan to fix them.

1) Did I understand correctly that the search will not work in version 1.0?

2) I executed command line: `pip install mkdocs=1.0rc1`. Next, I try to set up a foreign custom theme, for example, material (https://github.com/squidfunk/mkdocs-material) or rtd-dropdown (https://github.com/cjsheets/mkdocs-rtd-dropdown). Correctly I understand that for the version of `mkdocs = 1.0rc1` the foreign custom themes will not work? And will these themes work in the official version 1.0?

Output Console:
https://image.ibb.co/iBtkDz/14.png
https://image.ibb.co/f08JYz/15.png

**Comment by waylan** [comment] 2018-08-03 14:11
> Did I understand correctly that the search will not work in version 1.0?

Search will not work when using `file://` URLs. This is not something we will likely ever fix. The problem is that the browser's security settings will not let it work and we cannot in good conscience recommend that users disable their browser's security settings.

> Correctly I understand that for the version of `mkdocs = 1.0rc1` the foreign custom themes will not work? And will these themes work in the official version 1.0?

That depends entirely on the developers of those themes. I know some have been making changes in anticipation of 1.0, but you may need to wait until they release a new version. You will need to check with them about that.

In any event, the issue raised seems to be resolved, so I'm closing this.

**Closed by waylan** 2018-08-03 14:11 UTC
