### ISSUE TITLE
Improve documentation on how to test MkDocs plugins

### ISSUE THREAD

**Issue by lyz-code** [mkdocs/mkdocs#2330] opened 2021-03-19 12:44 UTC
I've started developing a plugin some weeks ago, and I had to spend a considerable amount of time deducing how to test it. I think it would be good to have a section in the official docs giving some insights.

I've published how I did it [here](https://lyz-code.github.io/blue-book/linux/mkdocs/#testing). I don't know if it's the best approach, but if you like it, I can make a PR to include the content to the official docs.

**Comment by waylan** [comment] 2021-03-19 13:33
We have a plan laid out to significantly improve our documentation in #1629. If you would like to contribute even a small piece, that is certainly welcome. I simply ask that whatever you contribute fits into the plan laid out in #1629.

That said, I see your writeup makes use of pytest, which is not in the Python Standard Library. We rely exclusively on the Python Standard Library's `unittest` and should not require plugin devs to do any different. Of course, if a plugin dev wants to use pytest or any other third party tool, they are certainly welcome to. We just don't expect or require it.

Note that there are a few helpers we have defined in [`mkdocs/tests/base.py`][1] which we use in our tests. The expectation is that third party plugin devs could make use of them as well (if they choose to do so). Those helpers certainly need to be documented.

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/tests/base.py

**Comment by waylan** [comment] 2021-03-19 14:11
I'm closing this as a duplicate of #1629.

**Closed by waylan** 2021-03-19 14:11 UTC
