### ISSUE TITLE
Unable to get Page Title

### ISSUE THREAD

**Issue by barreeeiroo** [mkdocs/mkdocs#1600] opened 2018-08-21 22:30 UTC
As you can see [here](https://docs.makeroid.io/components/user-interface/linear-progressbar/#visible), if I add `{{ page.title }}` to my documents, they aren't being processed with page title (I would like to get "_Linear Progressbar_" of "_Linear Progressbar - Makeroid Docs"_)
The original file is [this one](https://github.com/Makeroid/Documentation/blob/master/docs/includes/visible-property.md)

**Comment by waylan** [comment] 2018-08-22 01:54
How page titles are determined is defined [here][1]. Note however, that template variables are only available within templates, not within the Markdown document, which is the subject of #304. In fact, I'm closing this as a duplicate of #304. However, since that issue was last discussed, the Plugin API has been completed and it shouldn't take much effort for someone to create a plugin which offers such a feature. Some existing plugins are listed in the [wiki][2]. Not sure if any of them meet your needs.

[1]: https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data
[2]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins

**Closed by waylan** 2018-08-22 01:54 UTC
