### ISSUE TITLE
MkDocs container doesn't rebuild / refresh page itself

### ISSUE THREAD

**Issue by happicamper** [mkdocs/mkdocs#1175] opened 2017-03-21 07:44 UTC
I just rebuilt a MkDocs image from docker hub, my problem is whenever I put changes on my file (both tried inside the container and mounted file) doesn't auto-reload itself. I didn't execute any rebuild parameter or something. Here is my Dockerfile:
```
FROM centos:7
MAINTAINER gilroy <gilroy.toledano@toro.io>

RUN yum install epel-release -y && yum clean all
RUN yum install python-pip -y && yum clean all
RUN pip install mkdocs && pip install --upgrade pip
RUN pip install markdown-include && pip install mkdocs-material
RUN useradd --shell /bin/bash -d /home/user -u 1000 -o -c "" -m user \
 && usermod -aG root user

EXPOSE 80

WORKDIR /home/user

CMD ["mkdocs", "serve", "-a", "0.0.0.0:80"]
```
I just customized or rather added few things from thinkcube/mkdocs [dockerfile](https://hub.docker.com/r/thinkcube/mkdocs/~/dockerfile/).

Thanks in advance!

**Comment by happicamper** [comment] 2017-03-21 08:04
Thank you for such rapid response! So this might be the limitation for now, am I gonna close this issue for now cause you as an experienced developer think it's not possible to run the auto reload on a container. Or should I wait for others to contribute in this issue so that we can solve this one. 😄 .

**Comment by waylan** [comment] 2017-03-21 13:32
If this is not related to Docker, then this is a duplicate of #1174. That fix will be available in the next release. If this is related to Docker, then it is outside our control. Either way, there should no need to keep this open.

**Closed by waylan** 2017-03-21 13:32 UTC

**Comment by rickpeters** [comment] 2017-03-21 14:30
Hi @happicamper,

I use docker also and this feature does work. If I look at the difference I think your problem is the command you use for running mkdocs itself.
I do a `mkdocs serve --dirtyreload --dev-addr=0.0.0.0:8000`
Also if I remember correctly it does not work if I remap the port that is used natively by MkDocs
I do have a host bound volume mapping to the container for my documents directory (else there would be no point in doing a livereload :-))
You could also look at my two mkdocs images:
* https://hub.docker.com/r/rickpeters/mkdocs/
* https://hub.docker.com/r/rickpeters/mkdocsbeta/

The last one is a current version that supports livereload

regards,
Rick

**Comment by happicamper** [comment] 2017-03-22 00:00
@waylan Thanks Waylan, looking forward to the next release.
@rickpeters Hi mate! thanks for the suggestion, I'm going to look at these images. Really appreciate your help, thank for dropping by!
