### ISSUE TITLE
Submenus in default theme not usable on mobile

### ISSUE THREAD

**Issue by Vampire** [mkdocs/mkdocs#1555] opened 2018-07-17 12:39 UTC
Navigating docs generated with the default theme on mobile using the menu is not possible.
I tried with Firefox and standard browser on Android.
As example look at http://gitolite.com.
I can open the menu, I can expand a menu like "Use", but when I try to open a submenu like "basic", the parent menu collapses and there is no way to access the actual pages in the submenu.
If I test the same with the Desktop Firefox feature to test various display sizes I see that the behavior is like on normal Desktop browsing.
The first level of menus is only highlighted on hovering and opened on clicking.
The second level of menus is expanded on hovering but on clicking just closes.
As you cannot really hover on a mobile browser, this is actually unusable.

**Comment by waylan** [comment] 2018-07-17 13:59
This appears to be a duplicate of #1107 which was addressed via documentation in #1522.  That update will be available in a few weeks when we release version 1.0.

**Closed by waylan** 2018-07-17 13:59 UTC

**Comment by Vampire** [comment] 2018-07-17 15:29
Oh, sorry, I searched, but my search-fu failed me this time :-(
