### ISSUE TITLE
Drop `include_nav`, `include_next_prev` from config and context.

### ISSUE THREAD

**Issue by tomchristie** [mkdocs/mkdocs#679] opened 2015-07-02 16:17 UTC
We should consider dropping the `include_nav` and `include_next_prev` config.
The only theme that currently references them is the builtin `mkdocs` theme, and this could presumbly instead use...

    {% if nav|length > 1 %}

...and...

    {% if next_page or prev_page %}

For contextual switching, instead of using the current context variables.

**Comment by d0ugal** [comment] 2015-07-02 17:54
Sounds good. That'll resolve #479

**Comment by standage** [comment] 2015-11-06 20:32
I have found disabling the next/prev buttons sitewide with a single config option is very helpful.

**Comment by waylan** [comment] 2015-11-06 21:10
This appears to be a duplicate of #663, or at least very much related.

**Closed** 2016-03-31 20:25 UTC
Labels: Cleanup
