### ISSUE TITLE
Support include of markdown files

### ISSUE THREAD

**Issue by eshreveUTD** [mkdocs/mkdocs#777] opened 2015-12-22 22:02 UTC
Support the ability to include markdown files within other markdown files. 

My use case is that I have a list of [abbreviations](https://pythonhosted.org/Markdown/extensions/abbreviations.html) that I want to use on every markdown page. I can run my own preprocessing script to add them, but it would be nice if it was baked in.

Perhaps the following could be used: https://pypi.python.org/pypi/markdown-include.

Thanks.

**Comment by waylan** [comment] 2015-12-22 23:48
As you point out, this is already possible. Simply import the "markdown-include" extension, then open your config file and tell MkDocs about it. See the [docs] for instructions on using Python-Markdown extensions.

[docs]: http://www.mkdocs.org/user-guide/configuration/#markdown_extensions

**Comment by d0ugal** [comment] 2016-01-28 11:13
Closing as there seems to be a reasonable answer for this.

**Closed by d0ugal** 2016-01-28 11:13 UTC

**Comment by mathiasrw** [comment] 2016-03-27 20:50
After  a successful `pip install markdown-include` and and added

```yaml
markdown_extensions:
    - markdown_include
```

I get `ImportError: Failed loading extension 'markdown_include' from 'markdown_include', 'markdown.extensions.markdown_include' or 'mdx_markdown_include'`

Any inputs to get the extension working?

**Comment by banj** [comment] 2016-03-27 20:54
I believe you need ```markdown_include.include:```

**Comment by mathiasrw** [comment] 2016-03-27 21:29
Perfect - thanks...

**Comment by spatialsteve** [comment] 2016-04-05 08:18
Declared mkdocs rookie here,

I am getting the following error when loading a page that should include another page.

`Warning: could not find file support.md. Ignoring include statement. Error: [Errno 2] No such file or directory: u'support.md'`

`{!support.md!}` This is what I include in the file that is trying to include the file. Both files are in the same location. Any tips?

also I have included the following in mkdocs.yml

`markdown_extensions:
    - markdown_include.include:`

**Comment by basejump** [comment] 2017-06-13 22:24
In case anyone else stumbles on this here is how it works. 
`pip install markdown-include`
add the following to your mkdocs.yaml
```yaml
markdown_extensions:
    - markdown_include.include:
        base_path: docs
```
The syntax is {!filename!}

see https://github.com/cmacmackin/markdown-include

**Comment by emmavault** [comment] 2018-01-25 15:32
I did exactly that but I'm still having the issue:

```bash
INFO    -  Building documentation... 
INFO    -  Cleaning site directory 
ERROR   -  Error building page index.md 
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 11, in <module>
    load_entry_point('mkdocs==0.17.2', 'console_scripts', 'mkdocs')()
  File "/usr/local/Cellar/mkdocs/0.17.2/libexec/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/mkdocs/0.17.2/libexec/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/mkdocs/0.17.2/libexec/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/mkdocs/0.17.2/libexec/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/mkdocs/0.17.2/libexec/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/mkdocs/0.17.2/libexec/lib/python2.7/site-packages/mkdocs/__main__.py", line 127, in serve_command
    livereload=livereload
  File "/usr/local/Cellar/mkdocs/0.17.2/libexec/lib/python2.7/site-packages/mkdocs/commands/serve.py", line 117, in serve
    config = builder()
  File "/usr/local/Cellar/mkdocs/0.17.2/libexec/lib/python2.7/site-packages/mkdocs/commands/serve.py", line 112, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/usr/local/Cellar/mkdocs/0.17.2/libexec/lib/python2.7/site-packages/mkdocs/commands/build.py", line 282, in build
    build_pages(config, dirty=dirty)
  File "/usr/local/Cellar/mkdocs/0.17.2/libexec/lib/python2.7/site-packages/mkdocs/commands/build.py", line 242, in build_pages
    _build_page(page, config, site_navigation, env)
  File "/usr/local/Cellar/mkdocs/0.17.2/libexec/lib/python2.7/site-packages/mkdocs/commands/build.py", line 137, in _build_page
    page.render(config, site_navigation)
  File "/usr/local/Cellar/mkdocs/0.17.2/libexec/lib/python2.7/site-packages/mkdocs/nav.py", line 293, in render
    extension_configs=config['mdx_configs'] or {}
  File "/usr/local/Cellar/mkdocs/0.17.2/libexec/lib/python2.7/site-packages/markdown/__init__.py", line 159, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/usr/local/Cellar/mkdocs/0.17.2/libexec/lib/python2.7/site-packages/markdown/__init__.py", line 185, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/usr/local/Cellar/mkdocs/0.17.2/libexec/lib/python2.7/site-packages/markdown/__init__.py", line 264, in build_extension
    module = importlib.import_module(module_name_old_style)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: Failed loading extension 'markdown_include.include' from 'markdown_include.include', 'markdown.extensions.markdown_include.include' or 'mdx_markdown_include.include'
```
My `mkdocs.yml`:

```yaml
markdown_extensions:
    - markdown_include.include:
        base_path: docs
```

The versions of all packages involved:

```bash
macbook% python --version
Python 2.7.10
macbook% pip2 --version
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
macbook% pip2 install markdown-include
Requirement already satisfied: markdown-include in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: markdown in /usr/local/lib/python2.7/site-packages (from markdown-include)
macbook% brew install mkdocs
Warning: mkdocs 0.17.2 is already installed
```

I don't know what I'm doing wrong. I suspect the location `/usr/local/Cellar/` is the correct place to install that dependency? It's different from @mathiasrw 's output. Any idea? Is it only my mistake or anyone have the same issue?

**Comment by waylan** [comment] 2018-01-25 17:05
@emmavault My guess is you have multiple Python versions installed on your system. I see that you used `pip2` to install `markdown-include`, but you used `brew` to install `mkdocs`. Are you sure both are installed in the same Python?

Try running the command `pip2 freeze`, which will list all installed packages. Are both `mkdocs` and `markdown-include` included in the list? If not, you have two options:

1. Use `brew` to uninstall `mkdocs` and then use `pip2` to install mkdocs (`pip2 install mkdocs`).
2. Leave mkdocs as-is and install `markdown-include` to the same Python as mkdocs. Unfortunately, without more info, I can't say how best to do that. Perhaps using `pip` or `pip3`)? Try using `pip freeze` or `pip3 freeze` (also `pip --version` or `pip3 --version`) to determine where mkdocs is installed. Then install `markdown-include` to the same place.

**Comment by emmavault** [comment] 2018-01-25 17:27
Perfect man!:

```
macbook% pip2 freeze
Markdown==2.6.11
markdown-include==0.5.1
meld==3.16.1
pygobject==3.20.1
```

I did the following:
- `brew uninstall mkdocs`
- `pip2 install mkdocs`

and everything runs ok! Thanks!

**Comment by mollieswenson** [comment] 2019-05-17 01:02
I know this is a long-since-closed issue, but I'm having a somewhat related problem. I'm guessing I just don't have the config syntax right. Can anyone advise? Thanks :)

I have markdown_include working, but when I try to add the `inheritHeadingDepth: True` config value, I get an error. 

From my mkdocs.yml

```
markdown_extensions:
    - markdown_include.include:
        base_path: docs
        inheritHeadingDepth: True
```
Config instructions: https://github.com/cmacmackin/markdown-include#configuration

And the error:

```
ERROR   -  Config value: 'markdown_extensions'. Error: inheritHeadingDepth
[E 190516 17:55:31 ioloop:801] Exception in callback <bound method type.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "c:\python27\lib\site-packages\tornado\ioloop.py", line 1229, in _run
        return self.callback()
      File "c:\python27\lib\site-packages\livereload\handlers.py", line 67, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "c:\python27\lib\site-packages\livereload\watcher.py", line 73, in examine
        func and func()
      File "c:\python27\lib\site-packages\mkdocs\commands\serve.py", line 107, in builder
        site_dir=site_dir
      File "c:\python27\lib\site-packages\mkdocs\config\base.py", line 210, in load_config
        "Aborted with {0} Configuration Errors!".format(len(errors))
    ConfigurationError: Aborted with 1 Configuration Errors!
```

**Comment by waylan** [comment] 2019-05-17 13:54
@mollieswenson I don't see any obvious problems. Could you provide the output of `mkdocs build -v`? That might provide some clues.

**Comment by steve-todorov** [comment] 2019-09-27 11:51
Interesting - I'm having the exact same issue. I don't see anything obvious while running `build -v` as well: 

```
DEBUG   -  Loading configuration file: /docs/mkdocs.yml 
ERROR   -  Config value: 'markdown_extensions'. Error: inheritHeadingDepth 
DEBUG   -  Config value: 'config_file_path' = '/docs/mkdocs.yml' 
DEBUG   -  Config value: 'site_name' = 'Strongbox' 
DEBUG   -  Config value: 'nav' = [...] 
DEBUG   -  Config value: 'pages' = None 
DEBUG   -  Config value: 'site_url' = '' 
DEBUG   -  Config value: 'site_description' = None 
DEBUG   -  Config value: 'site_author' = None 
DEBUG   -  Config value: 'theme' = {'name': 'material', 'custom_dir': 'theme', 'logo': '', 'palette': {'primary': 'blue grey', 'accent': 'indigo'}, 'language': 'en', 'feature': {'tabs': True}} 
DEBUG   -  Config value: 'docs_dir' = '/docs/docs' 
DEBUG   -  Config value: 'site_dir' = '/docs/site' 
DEBUG   -  Config value: 'copyright' = None 
DEBUG   -  Config value: 'google_analytics' = [None, 'auto'] 
DEBUG   -  Config value: 'dev_addr' = Address(host='127.0.0.1', port=8000) 
DEBUG   -  Config value: 'use_directory_urls' = False 
DEBUG   -  Config value: 'repo_url' = '...' 
DEBUG   -  Config value: 'repo_name' = '...' 
DEBUG   -  Config value: 'edit_uri' = '...' 
DEBUG   -  Config value: 'extra_css' = ['assets/stylesheets/style.css'] 
DEBUG   -  Config value: 'extra_javascript' = ['assets/javascripts/medium-zoom.min.js', 'assets/javascripts/main.js'] 
DEBUG   -  Config value: 'extra_templates' = [] 
DEBUG   -  Config value: 'markdown_extensions' = ['admonition', 'meta', {}, {}, 'footnotes', 'tables', 'pymdownx.arithmatex', {}, 'pymdownx.caret', 'pymdownx.critic', 'pymdownx.details', 'pymdownx.extra', {}, 'pymdownx.inlinehilite', 'pymdownx.magiclink', 'pymdownx.mark', 'pymdownx.smartsymbols', 'pymdownx.superfences', {}, 'pymdownx.tilde', {}, {}] 
DEBUG   -  Config value: 'mdx_configs' = None 
DEBUG   -  Config value: 'strict' = False 
DEBUG   -  Config value: 'remote_branch' = 'gh-pages' 
DEBUG   -  Config value: 'remote_name' = 'origin' 
DEBUG   -  Config value: 'extra' = {'url': 'http://localhost:8000', 'assets': 'http://localhost:8000/assets', 'resources': 'http://localhost:8000/assets/resources'} 
DEBUG   -  Config value: 'plugins' = PluginCollection([('search', <mkdocs.contrib.search.SearchPlugin object at 0x7f80ea4c66d8>), ('markdownextradata', <markdownextradata.plugin.MarkdownExtraDataPlugin object at 0x7f80ea4c7c18>), ('git-revision-date', <mkdocs_git_revision_date_plugin.plugin.GitRevisionDatePlugin object at 0x7f80eb7025f8>)]) 

Aborted with 1 Configuration Errors!
```

**Comment by steve-todorov** [comment] 2019-09-27 12:31
Apologize, it looks like you can now do this by using [pymdown-extensions](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/) instead of `markdown-include`. The "right" way is to enable the extension:

```
markdown_extensions:
  - pymdownx.snippets:
      base_path: docs
```

And then use `--8<-- "path/to/file"` :)

**Comment by waylan** [comment] 2019-09-27 12:47
@steve-todorov the error is reported on line 2 of your verbose output:

    ERROR   -  Config value: 'markdown_extensions'. Error: inheritHeadingDepth 

It would appear that you have an error with the `inheritHeadingDepth` setting of the extension. Personally, I've never used the extension, so I'm not sure what the problem is, except that it outside the scope of MkDocs to fix. In any event, it appears that you worked out a solution with a different extension.

**Comment by eddie-velez** [comment] 2020-02-06 20:39
I've followed all directions and I'm still getting the markdown-include failed to load extension error.  

`Requirement already satisfied: markdown-include in /usr/local/lib/python2.7/site-packages (0.5.1)
Requirement already satisfied: markdown in /usr/local/lib/python2.7/site-packages (from markdown-include) (2.6.11)`

AND

`Requirement already satisfied: markdown-include in /usr/local/lib/python3.7/site-packages (0.5.1)
Requirement already satisfied: markdown in /usr/local/lib/python3.7/site-packages (from markdown-include) (3.1.1)
Requirement already satisfied: setuptools>=36 in /usr/local/lib/python3.7/site-packages (from markdown->markdown-include) (41.6.0)`

Just to cover basis.  That being said, I'm using docker to run mkdocs locally.  Has anyone run into this problem running it locally this way?

**Comment by waylan** [comment] 2020-02-06 21:57
@eddie-velez what does `mkdocs --version` report? In addition to the version number it will report  which Python it is associated with. If it is associated with a different Python than markdown-include, then that is your problem.
