### ISSUE TITLE
link URL arguments incorrectly translated to html

### ISSUE THREAD

**Issue by fyliu** [mkdocs/mkdocs#3760] opened 2024-06-27 17:58 UTC
**Note**: I'm using Material theme which I understand does some custom stuff for certain things, so I'm not entirely sure if the problem is from there or from MkDocs itself.

### URL

- `https://github.com/orgs/hackforla/projects/61/views/4?filterQuery=label%3A"ready+for+dev+lead"+-status%3ADone+-ready-for%3A"Dev+Lead"`

### Problem link

note: this renders fine in github but not after being processed by mkdocs in the live server

- [dev lead](https://github.com/orgs/hackforla/projects/61/views/4?filterQuery=label%3A"ready+for+dev+lead"+-status%3Adone+-ready-for%3A"Dev+Lead")

URL input:
- `https://github.com/orgs/hackforla/projects/61/views/4?filterQuery=label%3A"ready+for+dev+lead"+-status%3Adone+-ready-for%3A"Dev+Lead"`

URL rendered (**cursor right-click > Copy link address**):
- `https://github.com/orgs/hackforla/projects/61/views/4?filterQuery=label%3A`

### Workaround:

I moved `status` to the end of the arguments list within `filterQuery`

- [dev lead](https://github.com/orgs/hackforla/projects/61/views/4?filterQuery=label%3A"ready+for+dev+lead"+-ready-for%3A"Dev+Lead"+-status%3Adone)

URL input:
- `https://github.com/orgs/hackforla/projects/61/views/4?filterQuery=label%3A"ready+for+dev+lead"+-ready-for%3A"Dev+Lead"+-status%3Adone`

URL rendered:
- `https://github.com/orgs/hackforla/projects/61/views/4?filterQuery=label%3A%22ready+for+dev+lead%22+-ready-for%3A%22Dev+Lead%22+-status%3Adone`

### Observations

- The problem seems to be from having the last `+-ready-for...`. The URL shows up fine if I removed it.
- It seems like if I put the arguments in alphabetical order (or some order that matters to MkDocs), they show up correctly in the link. e.g. **l..r..s..** or `label...+ready-for...+status...`

## Different example problem

This one has to do with &-delimited arguments in the URL, but it has the same issue where MkDocs seems to care about the position of certain parts of the URL.

### URL

- `https://github.com/orgs/hackforla/projects/61/views/11?filterQuery=-label%3A"role%3A+missing"+status%3A"Prioritized+Backlog"%2C"New+Issue+Review"++label%3A"role%3A+back+end"+&sliceBy%5Bvalue%5D=_noValue&layout=table&sliceBy%5BcolumnId%5D=117220806&visibleFields=%5B"Title"%2C"Labels"%2C117220806%2C"Milestone"%5D`

#### components I reordered (& delimited)

- `https://github.com/orgs/hackforla/projects/61/views/11?`
  **filterQuery=-label%3A"role%3A+missing"+status%3A"Prioritized+Backlog"%2C"New+Issue+Review"+label%3A"role%3A+back+end"
  sliceBy%5Bvalue%5D=_noValue
  layout=table
  sliceBy%5BcolumnId%5D=117220806
  visibleFields=%5B"Title"%2C"Labels"%2C117220806%2C"Milestone"%5D**

### Working link

moved `filterQuery` to 2nd position

- [back end](https://github.com/orgs/hackforla/projects/61/views/11?sliceBy%5Bvalue%5D=_noValue&filterQuery=-label%3A"role%3A+missing"+status%3A"Prioritized+Backlog"%2C"New+Issue+Review"++label%3A"role%3A+back+end"&layout=table&sliceBy%5BcolumnId%5D=117220806&visibleFields=%5B"Title"%2C"Labels"%2C117220806%2C"Milestone"%5D)

URL input:
- `https://github.com/orgs/hackforla/projects/61/views/11?sliceBy%5Bvalue%5D=_noValue&filterQuery=-label%3A"role%3A+missing"+status%3A"Prioritized+Backlog"%2C"New+Issue+Review"++label%3A"role%3A+back+end"&layout=table&sliceBy%5BcolumnId%5D=117220806&visibleFields=%5B"Title"%2C"Labels"%2C117220806%2C"Milestone"%5D`

URL rendered:
- `https://github.com/orgs/hackforla/projects/61/views/11?sliceBy%5Bvalue%5D=_noValue&filterQuery=-label%3A%22role%3A+missing%22+status%3A%22Prioritized+Backlog%22%2C%22New+Issue+Review%22++label%3A%22role%3A+back+end%22&layout=table&sliceBy%5BcolumnId%5D=117220806&visibleFields=%5B%22Title%22%2C%22Labels%22%2C117220806%2C%22Milestone%22%5D`

### Working link

moved `filterQuery` after `sliceBy columnId`

- [back end](https://github.com/orgs/hackforla/projects/61/views/11?sliceBy%5Bvalue%5D=_noValue&layout=table&sliceBy%5BcolumnId%5D=117220806&filterQuery=-label%3A"role%3A+missing"+status%3A"Prioritized+Backlog"%2C"New+Issue+Review"+label%3A"role%3A+back+end"&visibleFields=%5B"Title"%2C"Labels"%2C117220806%2C"Milestone"%5D)

URL input:
- `https://github.com/orgs/hackforla/projects/61/views/11?sliceBy%5Bvalue%5D=_noValue&layout=table&sliceBy%5BcolumnId%5D=117220806&filterQuery=-label%3A"role%3A+missing"+status%3A"Prioritized+Backlog"%2C"New+Issue+Review"+label%3A"role%3A+back+end"&visibleFields=%5B"Title"%2C"Labels"%2C117220806%2C"Milestone"%5D`

URL rendered:
- `https://github.com/orgs/hackforla/projects/61/views/11?sliceBy%5Bvalue%5D=_noValue&layout=table&sliceBy%5BcolumnId%5D=117220806&filterQuery=-label%3A%22role%3A+missing%22+status%3A%22Prioritized+Backlog%22%2C%22New+Issue+Review%22+label%3A%22role%3A+back+end%22&visibleFields=%5B%22Title%22%2C%22Labels%22%2C117220806%2C%22Milestone%22%5D`

### Problem Link

moved `filterQuery` to last place

- [back end](https://github.com/orgs/hackforla/projects/61/views/11?sliceBy%5Bvalue%5D=_noValue&layout=table&sliceBy%5BcolumnId%5D=117220806&visibleFields=%5B"Title"%2C"Labels"%2C117220806%2C"Milestone"%5D&filterQuery=-label%3A"role%3A+missing"+status%3A"Prioritized+Backlog"%2C"New+Issue+Review"+label%3A"role%3A+back+end")

URL input:
- `https://github.com/orgs/hackforla/projects/61/views/11?sliceBy%5Bvalue%5D=_noValue&layout=table&sliceBy%5BcolumnId%5D=117220806&visibleFields=%5B"Title"%2C"Labels"%2C117220806%2C"Milestone"%5D&filterQuery=-label%3A"role%3A+missing"+status%3A"Prioritized+Backlog"%2C"New+Issue+Review"+label%3A"role%3A+back+end"`

URL rendered:
- `https://github.com/orgs/hackforla/projects/61/views/4?filterQuery=label%3A%22ready+for+dev+lead%22+-ready-for%3A%22Dev+Lead%22+-status%3Adone`

**Comment by pawamoy** [comment] 2024-06-30 10:55
Can you show us how you add this link to your Markdown documents? Using the `[]()` syntax or pasted directly? Please also share your mkdocs.yml configuration.

**Comment by pawamoy** [comment] 2024-06-30 10:59
My intuition is that double-quotes are messing up the regex for HTML links.  One workaround seems to be to escape double-quotes with `%22`. See https://stackoverflow.com/a/62087250/3451029.

**Comment by pawamoy** [comment] 2024-06-30 11:04
Even VSCode seems to only match up to the first double-quotes (look at the underline):

![editorurl](https://github.com/mkdocs/mkdocs/assets/3999221/bf5406c4-a8bb-4eaa-85d0-28e62809a6e2)

**Comment by fyliu** [comment] 2024-06-30 13:54
I used the []() syntax exactly like the bullet links I put in this issue (with the bullets). I copied them directly from the page.

Here’s my [mkdocs.yml link](https://github.com/hackforla/peopledepot/blob/main/mkdocs.yml) and it’s using the same setup as the project.

The workaround I did above (rearranging the ordering of things in the input url) made it render the entire url correctly in the output, which is why I suspect it to be caused by mkdocs, or material (or some dependency that processes the url).

**Comment by pawamoy** [comment] 2024-06-30 21:41
Yes I already tried and can confirm the issue. Thank you for sharing your configuration.

However what I tried to emphasize is that the Markdown parser used by MkDocs, Python-Markdown, is probably correct and users *must* encode double-quotes with `%22`.

Would love to get @waylan's feedback here.

**Comment by waylan** [comment] 2024-07-01 13:40
Please note that Markdown does not have support for plain URLs in documents. Yes, GitHub does parse plain URLs, but that is a non-standard [extension](https://github.github.com/gfm/#autolinks-extension-). Of course, MkDocs doesn't support all of GitHub's non-standard stuff. Therefore, you can't expect Markdown, and by extension, MkDocs to properly parse plain URLs.

If you want a plain URL to be converted to a link, then you must enclose the link in angle brackets as documented [here]()https://daringfireball.net/projects/markdown/syntax#autolink):

```markdown
<https://github.com/orgs/hackforla/projects/61/views/4?filterQuery=label%3A"ready+for+dev+lead"+-status%3Adone+-ready-for%3A"Dev+Lead">
```

Alternatively, you may find a [third-party Markdown extension](https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions) exists which adds support for plain URls without needing the angle brackets.

This is a Markdown issue, not a MkDocs issue. Unless this constitutes a request for plain autolinks to be added as a default Markdown extension for MkDocs. Personally, I have always been against them. There was a reason links have always required angle brackets. As a document author I want full control over whether the parser sees a string as a link or not. For the users who want the convenience, they can chose to add an extension which gives them that without forcing that behavior on me.

**Comment by squidfunk** [comment] 2024-07-01 14:09
[MagicLink](https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/) might be useful here (I did not test it)

**Comment by pawamoy** [comment] 2024-07-01 15:13
Thank you @waylan and @squidfunk.

@fyliu, I don't see `pymdownx.magiclink` listed in the config you shared, so I suppose something else (markdown extension or plugin) is automatically converting them to HTML links, otherwise you wouldn't be mentioning this:

> URL rendered (cursor right-click > Copy link address)

...because pasting plain URLs by default renders them as text, not links (as explained by @waylan above). In the end, I cannot reproduce your issue. If you want us to investigate further, please provide a minimal reproduction example (a repository or archive containing a very simple MkDocs site and config that shows the issue).

In the mean time, I believe there is nothing actionable for MkDocs so I'll close this. Feel free to comment further of course :slightly_smiling_face:

**Closed by pawamoy** 2024-07-01 15:13 UTC

**Comment by facelessuser** [comment] 2024-07-01 15:20
MagicLink will do about as good as GitHub does with this specific case (it doesn't capture the last quote). See the example below processed by GitHub, this what MagicLink is capable of as well..

https://github.com/orgs/hackforla/projects/61/views/4?filterQuery=label%3A"ready+for+dev+lead"+-status%3ADone+-ready-for%3A"Dev+Lead"

**Comment by facelessuser** [comment] 2024-07-01 15:22
My advise, put your link in `<...>` as this case is just a bit too complicated for auto-linking.

**Comment by pawamoy** [comment] 2024-07-01 16:00
Thanks for the clarification, that makes a difference indeed. Don't hesitate to use code blocks to make it absolutely clear which syntax you use (avoiding any rendering from GitHub):

````
```md
***
### Problem link

note: this renders fine in github but not after being processed by mkdocs in the live server

- [dev lead](https://github.com/orgs/hackforla/projects/61/views/4?filterQuery=label%3A"ready+for+dev+lead"+-status%3Adone+-ready-for%3A"Dev+Lead")
***
```
````

---

I think Python-Markdown supports links like `[alt text](<url> "title")`, so once again double-quotes are probably the problem here. Try wrapping the URL in angle brackets, as @facelessuser suggested.

**Comment by facelessuser** [comment] 2024-07-01 16:07
Hmm, this is related to the bulit-in URL handling in Python Markdown then.

There is logic for titles, in quotes. Python Markdown, currently, doesn't care if there are spaces between the URL and first quote or not, so as soon as it sees a quote, it enters title mode.

It is possible that a change to require whitespace before the first quote, signifying a break between URL and title,  should be a requirement. Such a requirement may allow for the URL handling to be altered to allow this URL to pass through undisturbed. I think it may be worth bringing up over at the Python Markdown repo as I personally don't feel that such an expectation is completely out there.

**Comment by facelessuser** [comment] 2024-07-01 16:10
It does seem like this works though (URL in traditional format, but the URL part enclosed in `<...>`.

```
[test](<https://github.com/orgs/hackforla/projects/61/views/4?filterQuery=label%3A"ready+for+dev+lead"+-status%3ADone+-ready-for%3A"Dev+Lead"> "title")
```

**Comment by fyliu** [comment] 2024-07-01 17:04
Here's the minimal demo [repo](https://github.com/fyliu/mkdocs-link-issue-demo) and [rendered page](https://fyliu.github.io/mkdocs-link-issue-demo/) in ghpages

@facelessuser Thanks for the insights about the <...>. That's handy to know for getting it working without messing with the URL.

Yeah, it parsed the whole thing and decided part of it belonged to the title. But if I put a + mark at the end, I guess it makes it clear that the whole thing is the URL. A space to delimit the break sounds reasonable to me.

**Comment by fyliu** [comment] 2024-07-01 18:40
@waylan thanks! I didn't realize you already answered my question before I asked them. I blame reading messages on the phone.

I think I'll look into making a python markdown plugin to require the space between url and title starting double-quotes. Just for fun, and I need the programming practice.

**Comment by waylan** [comment] 2024-07-01 19:16
@fyliu I still don't fully understand your issue as you have not provided clear examples. As @pawamoy stated, you need to provide a code block which shows your entire Markdown markup, not rendered markup. And when discussing expected versus actual output, you need to provide a code block showing the generated HTML. This issue is closed and any change in behavior would need to be addressed upstream at [Python-Markdown/markdown](https://github.com/Python-Markdown/markdown) So keep that in mind if/when you open an issue there.

**Comment by pawamoy** [comment] 2024-07-01 19:24
@waylan they are using `[alt text](url_with_"double_quotes")`, and the last quote (or quotes before it) is parsed as the beginning of a title. @facelessuser suggested maybe a space could be required before a title to prevent this URL parsing issue.

**Comment by waylan** [comment] 2024-07-01 19:41
Yes thank you @pawamoy I sort of gathered that from you and @facelessuser's comments. I was simply trying to help @fyliu understand that it was not clear from their own comments.

Regardless, we don't require a space between the URL and title because that is the behavior of the reference implementation (`markdown.pl`). My recollection is fuzzy on this, but I want to say that there may be some related issue with supporting spaces in URLs and that conflicting with titles (and that is why the workaround exists of wrapping a URL in angle brackets within a Markdown link). I believe that this is one of the things that Commonmark changed from the original rules. Of course, as Python-Markdown is not a Commonmark parser, we have not (and will not be) making that change (and therefore we will never match GitHub's behavior). Therefore, @fyliu pursing this as a third party extension is probably the right way forward here.

**Comment by facelessuser** [comment] 2024-07-01 19:47
To be honest, knowing that `<...>` can be used to allow any URL, it makes something like requiring a space before titles less pressing. Embarrassingly, I did not realize I could use `<...>` around a URL within the `[text](url "title")` form until now 😅.

**Comment by fyliu** [comment] 2024-07-01 20:36
@waylan thanks. I should be better than this, but I failed to point out that I was using []() syntax at least twice where I tried to explain it.

Yes, I meant I was going to look at doing an extension to [Python-Markdown/markdown](https://github.com/Python-Markdown/markdown) after seeing your comment at https://github.com/Python-Markdown/markdown/issues/847

Thank you for your explanation of the extra space thing.

**Comment by squidfunk** [comment] 2024-07-01 21:39
> To be honest, knowing that `<...>` can be used to allow any URL, it makes something like requiring a space before titles less pressing. Embarrassingly, I did not realize I could use `<...>` around a URL within the `[text](url "title")` form until now 😅.

Same!
