### ISSUE TITLE
Can not automatically reload the page 

### ISSUE THREAD

**Issue by zibuyule** [mkdocs/mkdocs#1208] opened 2017-04-12 03:33 UTC
Hello,

I found that this version (0.16.3) can not automatically reload the page when the file is modified.
So I have to use the old version.

**Comment by waylan** [comment] 2017-04-12 14:01
Are you sure you are on version 0.16.3? We had a bug in 0.16.2 related to this which was fixed in 0.16.3. Could you provide some more information so that we can replicate the problem?

**Comment by waylan** [comment] 2017-04-18 15:10
As I can't reproduce the reported problem in the latest release and no additional information has been provided, this is being closed.

**Closed by waylan** 2017-04-18 15:10 UTC
