### ISSUE TITLE
Allow to specify what media is copied to site_dir

### ISSUE THREAD

**Issue by bachp** [mkdocs/mkdocs#342] opened 2015-02-05 10:13 UTC
We have a bit a special mkdocs setup. The markdown files are distributed accross the source folder.
I.e. our scripts folder has a `README.md` that describes all the scripts inside.

In order to do this we set `docs_dir` to the root of the repository. We then use the `pages` list in `mkdocs.yml` to link these files in a meaningful structure.

This work well and gives us a nice looking documentation.

However one issue is that mkdocs is copying the whole source tree into the `site` directory.

It would be nice to have a way to specify what media is copied, either by having a white and/or blacklist. Or by explicitly setting an option like `media_dirs` that specifies the folders that should be copied.

**Comment by d0ugal** [comment] 2015-02-05 10:17
I can see this being useful, but I dont think this is a use case we want to try and target initially. So I've marked this as post-1.0 which we are currently trying to drive towards with the minimum features required.

**Comment by achton** [comment] 2015-03-30 20:25
This is a feature I could use as well. We also have a custom `site_dir` called `web` which results in the output being built as:
```
<root>
 - README.md
 - other.md
 - mkdocs.yml
 - web/
     - .git/
     - README/
     - other/
     - mkdocs.yml
     - site/
        - css/
        - fonts/
        - etc..
     - web/
        - .git/
        - css/
        - fonts/
        - etc..
        - mkdocs.yml
        - site/
          - etc..

Something wacky is going on, and I feel that it should only look at .md files in the source folder structure, and then replicate only that in the `site_dir`.

**Comment by d0ugal** [comment] 2015-03-31 08:16
@achton The problem is that your `site_dir` is within your `docs_dir` - you shouldn't do this, we should stop people doing this (#384). We can't only look at `.md` files because people include images and all sorts of other assets which are perfectly valid in documentation.

There was a change recently (#254) that stopped us copying dotfiles, so your `.git` wont be copied - but this hasn't yet been released. Keep an eye on on the [0.12.0 milestone](https://github.com/mkdocs/mkdocs/milestones/0.12.0) for that being available - I'm pushing to get that out the door soon.

**Comment by waylan** [comment] 2016-12-02 18:57
I believe this has been sufficiently address in #1020. Yes, we still copy everything in the `doc_dir`, but that is the way it should be (if you don't want a file in your `site-dir`, then don't put it in the `doc_dir`). However, we no longer assume all CSS/JavaScript should be linked in the templates. I'm closing this as "fixed."

**Closed by waylan** 2016-12-02 18:57 UTC
Labels: Enhancement
