### ISSUE TITLE
Add support to extract underline-ish title (setext-style headings)

### ISSUE THREAD

**Issue by hason** [mkdocs/mkdocs#1886] opened 2019-10-18 04:44 UTC
The util function [`get_markdown_title`](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/utils/__init__.py#L332) supports only ATX-style headers. It should also support:
```markdown
A level-one heading
===================

A level-two heading
-------------------
```

**Comment by waylan** [comment] 2019-10-18 14:26
I'm closing this as a duplicate of #1826. As the discussion there is long and covers multiple issues, I've copied the relevant [comment][0] below. Also note that in #1843 we have explicitly documented that setext style headers are not supported.

> The page title is set in [`mkdocs.structure.pages.Page._set_title`][1].  The [`mkdocs.utils.get_markdown_title`][2] function actually extracts the title from the Markdown source and would need to be significantly refactored as it currently assumes the header is contained on one line only (it doesn't support setext-style headers because they take 2 lines). Note that the title is set on the page before the Markdown source is rendered to HTML and this is non-negotiable. It would be easier to get the header from the rendered HTML (which would eliminate any concern about which format was used), but MkDocs needs the title to be set at an earlier stage than when it renders the Markdown to HTML. This is documented behavior in the Plugin API which we have promised to continue supporting. Also, I will only consider a change which enforces the use of an H1. If the first header is an H2, then the page title should be defined elsewhere (such as in meta-data) and a custom theme template would presumably be inserting the page title as an H1 separate from the page body.
> 
> Finally, this is very much something which could be addressed by a plugin. I expect either the [on_page_markdown][3] or [on_page_content][4] events could be used to overwrite the page title based on the Markdown source or rendered HTML respectively. As a third-party plugin, you could then use whatever criteria you want to define a page title.

[3]: https://www.mkdocs.org/user-guide/plugins/#on_page_markdown
[4]: https://www.mkdocs.org/user-guide/plugins/#on_page_content
[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/structure/pages.py#L143
[2]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/utils/__init__.py#L332

[0]: https://github.com/mkdocs/mkdocs/issues/1826#issuecomment-511497060

**Closed** 2023-05-29 19:59 UTC
