### ISSUE TITLE
Crash on first use (attribute six.moves.UserDict not exist)

### ISSUE THREAD

**Issue by jyuhuan** [mkdocs/mkdocs#590] opened 2015-06-04 02:20 UTC
I installed mkdocs by the command `sudo pip install mkdocs`. The installation was successful. However, when I run `mkdocs new xxx`, or simply `mkdocs`, the following error appears: 

	$ mkdocs
	Traceback (most recent call last):
	  File "/usr/local/bin/mkdocs", line 7, in <module>
	    from mkdocs.cli import cli
	  File "/Library/Python/2.7/site-packages/mkdocs/cli.py", line 11, in <module>
	    from mkdocs import serve
	  File "/Library/Python/2.7/site-packages/mkdocs/serve.py", line 6, in <module>
	    from mkdocs.config import load_config
	  File "/Library/Python/2.7/site-packages/mkdocs/config/__init__.py", line 1, in <module>
	    from mkdocs.config.base import load_config
	  File "/Library/Python/2.7/site-packages/mkdocs/config/base.py", line 17, in <module>
	    class Config(six.moves.UserDict):
	AttributeError: '_MovedItems' object has no attribute 'UserDict'

**Comment by d0ugal** [comment] 2015-06-04 09:13
Duplicate of #583

**Closed by d0ugal** 2015-06-04 09:13 UTC
