### ISSUE TITLE
Quick question regarding mkdocs.yml structure

### ISSUE THREAD

**Issue by qikkeronline** [mkdocs/mkdocs#587] opened 2015-06-03 11:03 UTC
Hi there,

I'd like to have a top-level menu with link and under there multiple subpages. I've tried to format it like this:

	site_name: QO - Read the Docs Testcase
	pages:
	- Home: 'index.md'
	- About: 'about/about_index.md'
	    - 'License': 'about/license.md'
	    - 'Code': 'about/code.md'
	    - 'Release Notes': 'about/release-notes.md'

But it does not seem to pick up the 'about/about_index.md' file in the navigation. Is this a limitation or am I doing it wrong?

Thanks, and kind regards,

Gerben van Dijk

**Comment by ProfYaffle** [comment] 2015-06-03 11:27
Try:

    site_name: QO - Read the Docs Testcase
    pages:
    - Home: index.md
    - About:
        - About: about/about_index.md
        - License: about/license.md
        - Code: about/code.md
        - Release Notes: about/release-notes.md

... with documents structured similarly:

docs/index.md
docs/about/about_index.md
docs/about/license.md
docs/about/code.md
dpcs/about/release-notes.md

**Comment by d0ugal** [comment] 2015-06-03 11:27
That is a limitation. You can do this, but it still won't quite do what you want:

```
site_name: QO - Read the Docs Testcase
pages:
- Home: 'index.md'
- About:
    - index: 'about/index.mf'
    - 'License': 'about/license.md'
    - 'Code': 'about/code.md'
    - 'Release Notes': 'about/release-notes.md'
```

This will make localhost:8000/about/ work, but you will have an extra navigation item for the index. We need to add a way for people to hide them.

**Comment by qikkeronline** [comment] 2015-06-03 12:00
Thanks guys. I already tried it several ways, so good to know that it's a limitation. Thanks @d0ugal that solves the URL issue for me. Is there a way to make sure that also the top level navigation link (see my attached screenshot) also links to that URL?

![schermafbeelding 2015-06-03 om 13 59 33](https://cloud.githubusercontent.com/assets/10937470/7959385/e1a8c8c8-09f8-11e5-8c10-b97100f5856c.png)

**Comment by ProfYaffle** [comment] 2015-06-03 14:54
@qikkeronline If you find a way, let me know...

It gets worse if you shrink the viewport down so that it reverts to more of a mobile interface (with the hamburger menu in the top right). Then, there's no real way to tell the menu items apart since they get compressed into a vertical list, and you inevitably end up clicking on a link-less entry.

I wondered whether there was simply some CSS styling I could apply to make it more obvious that 'this is a heading' but 'this is a heading with a link'...?

**Comment by d0ugal** [comment] 2015-06-03 15:01
@qikkeronline No, there isn't a way at the moment. I don't think it is easily possible without some nasty hackery.

**Comment by d0ugal** [comment] 2015-06-05 07:30
Closing this as the offshoot is basically a duplicate of #73

**Closed by d0ugal** 2015-06-05 07:30 UTC
