### ISSUE TITLE
How can I downgrade 0.17.2 version to 0.16.3?

### ISSUE THREAD

**Issue by alexsnw** [mkdocs/mkdocs#1358] opened 2017-11-29 10:57 UTC
Hi :)

We need to use the yeti bootstrap theme and these don't work with this version.

Cheers!

**Comment by waylan** [comment] 2017-11-29 13:51
The standard [pip method][1] will work fine. However, you may need to uninstall the current version first:

    pip uninstall mkdocs
    pip install mkdocs==0.16.3

I'm closing this as this is not a bug report or feature request. In the future, please direct support questions to the [mailing list][2].

[1]: https://pip.pypa.io/en/stable/user_guide/#installing-packages
[2]: https://groups.google.com/forum/#!forum/mkdocs

**Closed by waylan** 2017-11-29 13:51 UTC
