### ISSUE TITLE
mkdocs serve, not run

### ISSUE THREAD

**Issue by wisnubaldas** [mkdocs/mkdocs#1956] opened 2020-01-07 03:21 UTC
hi i just installed this on windows 10. how do I run the server? what is the meaning of this error?
![gambar](https://user-images.githubusercontent.com/10908214/71865985-4c393000-3137-11ea-95a1-9527ccb63173.png)

**Comment by waylan** [comment] 2020-01-07 03:29
This is a duplicate of #1885.

**Closed by waylan** 2020-01-07 03:29 UTC
