### ISSUE TITLE
UnboundLocalError: local variable 'l_1_nav_item' referenced before assignment

### ISSUE THREAD

**Issue by squidfunk** [mkdocs/mkdocs#1121] opened 2017-01-07 17:15 UTC
I'm encountering a very strange bug. Suddenly when building my theme in Travis CI, I get the following error:

```
Traceback (most recent call last):
  File "/home/travis/.local/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/.local/lib/python2.7/site-packages/mkdocs/__main__.py", line 156, in build_command
    ), dirty=not clean)
  File "/home/travis/.local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 379, in build
    build_pages(config, dirty=dirty)
  File "/home/travis/.local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 306, in build_pages
    build_template('404.html', env, config, site_navigation)
  File "/home/travis/.local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 166, in build_template
    output_content = template.render(context)
  File "/home/travis/.local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/travis/.local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/travis/build/squidfunk/mkdocs-material/material/404.html", line 1, in top-level template code
    {% extends "main.html" %}
  File "/home/travis/build/squidfunk/mkdocs-material/material/main.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/travis/build/squidfunk/mkdocs-material/material/base.html", line 68, in top-level template code
    {% block site_nav %}
  File "/home/travis/build/squidfunk/mkdocs-material/material/base.html", line 73, in block "site_nav"
    {% include "partials/nav.html" %}
  File "/home/travis/build/squidfunk/mkdocs-material/material/partials/nav.html", line 20, in top-level template code
    {% include "partials/nav-item.html" %}
  File "/home/travis/build/squidfunk/mkdocs-material/material/partials/nav-item.html", line 16, in top-level template code
    {% for nav_item in nav_item.children %}
UnboundLocalError: local variable 'l_1_nav_item' referenced before assignment
```

The part of the file where the error is thrown:

``` jinja
<ul class="md-nav__list" data-md-scrollfix>
  {% for nav_item in nav_item.children %} <!-- The error is thrown in this line -->
    {% set temp = path %}
    {% set path = path + "-" + loop.index | string %}
    {% include "partials/nav-item.html" %}
    {% set path = temp %}
  {% endfor %}
</ul>
```

I don't have a variable with that name defined and it works perfectly on my machine (Mac OS). The Travis environment is a Linux container. I'm using MkDocs 0.16.1 for both environments. Any ideas?

**Comment by d0ugal** [comment] 2017-01-07 21:50
Interesting. There was a new jinja2 release today, could that be related?

I've never seen anything like it before.

**Comment by jacebrowning** [comment] 2017-01-07 21:55
I believe it's a Jinja2 regression. `pip install jinja2==2.8` fixes the issue for me.

**Comment by laf** [comment] 2017-01-07 22:04
Yes this is a regression in pallets/jinja#640. Is it possible to update jinja2 >= 2.7,<2.9 and tag a new release?

**Comment by d0ugal** [comment] 2017-01-07 22:17
I can do a quick requirements fix release tomorrow if there isn't a jinja2 fix first. I'm out and on my phone at the moment.

**Comment by d0ugal** [comment] 2017-01-07 22:18
It looks like Armin is way ahead of me. https://github.com/pallets/jinja/commit/e3022523a51a4c6569f9e21625ca2cebcc7ce98a

**Comment by d0ugal** [comment] 2017-01-07 22:19
Going to close this as I don't think we can do anything. I expect a jinja2 release soon.

**Closed by d0ugal** 2017-01-07 22:19 UTC

**Comment by laf** [comment] 2017-01-07 22:31
That change hasn't actually made it into 2.9.1 and even if it did it would mean those how have already pulled it in will still have issues until a new release is issued.

We've worked round it for now but you could just update https://github.com/mkdocs/mkdocs/blob/master/requirements/project.txt to be `jinja2>=2.7,<2.9`

**Comment by d0ugal** [comment] 2017-01-08 08:05
Jinja 2.9.2 was released. This should now be fully resolved.

**Comment by laf** [comment] 2017-01-08 09:09
👍

**Comment by squidfunk** [comment] 2017-01-08 13:55
Perfect, thanks for the quick analysis and feedback! There's another scoping error now, but I will investigate and directly post to the jinja issue tracker.

**Comment by d0ugal** [comment] 2017-01-08 13:56
Thanks, feel free to also link it here - I'm quite interested :)

**Comment by squidfunk** [comment] 2017-01-08 17:30
There was one other issue when I override a variable which is defined in outer scope inside a for block. It always told me "not defined", because the variable had the same name in the inner, as in the outer scope. However, defining a reference before the for block and using that reference seems to fix it for me. The build is working again.
