### ISSUE TITLE
Building hidden pages

### ISSUE THREAD

**Issue by jhamman** [mkdocs/mkdocs#699] opened 2015-07-27 00:54 UTC
Is it possible to tell mkdocs to build pages but not have them show up in the side bar?  If it is possible, an example of how to do this in the documentation would be great.

I asked this question here as well: https://groups.google.com/forum/#!topic/mkdocs/ILW9-SIdERs

**Comment by keelii** [comment] 2015-07-27 05:28
I have the same question 
mkdocs only build specified .md files in yml. Sometimes i use relative path to reference md file, but it not working for me .

if there is a `glob pattern` to  set, It would be better ^!^ : 

    mdFiles: docs/\*/\*.md

**Comment by waylan** [comment] 2015-07-27 12:45
No this is not possible as this time. I am not aware that it is on the road-map either, although I am not the one to make such a decision. I would suggest that if such a feature was to be implemented, it would use the page meta-data to define a page as "hidden" (perhaps by adding a `hidden: true` key-value pair to the meta-data for the page). Then, when building the nav, it would simply be skipped.

**Comment by jhamman** [comment] 2015-07-27 15:16
Thanks @waylan - Good to know.  

Any thoughts on how difficult this feature would be to add? The `hidden: true` api is exactly what I was envisioning.

**Comment by robodude666** [comment] 2015-07-29 21:13
I've ran across this same exact issue a few weeks ago, and adopted the same method that [Docker](https://docs.docker.com/) used for their docs (they recently adopted Hugo):

- Set the Page Title in the [mkdocs.yml](https://github.com/eolamey/docker/blob/212dfb45dec64b470307aec22623f2d80be6695f/docs/mkdocs.yml) file to a special value (they used \*\*HIDDEN\*\*).
- Update the [Template](https://github.com/docker/docs-base/blob/641e94642573c34fea7894441e0f3b5a2b7ba477/theme/mkdocs/nav.html) to not include a pages with the above special value.

It feels very hacky, but it's working well enough for me right now. The docs base I'm maintaining is far smaller than Docker's so it's OK for now. I can imagine if you have a larger documentation base it might get annoying to maintain.

@waylan From trying to figure out how to get around this limitation, and reading older issues people opened on this topic it doesn't seem to be something that plans to be supported by mkdocs; and I would agree. mkdocs is intended to be used for simple documentation. Having dozens of hidden pages to be used for links only is a step above simple. Personally, I'd rather see this handled via a extension once API support is added.

**Comment by waylan** [comment] 2015-07-29 21:51
According to a recent edit to the first comment on #689 this is addressed by the work there. That said, it is not clear to me how or when that work will be merged in. 

In any event, I agree that this seems more like a feature for a plugin API.

**Comment by jhamman** [comment] 2015-07-29 23:59
Thanks for the input @robodude666 and @waylan.  I went ahead and modified the read-the-docs theme to exclude nav items == 'hidden'.  That seems to be working locally and on read-the-docs.

This solution came from @martinzugnoni and works like a charm, albeit a bit hackish...

>This is the original "base.html" file:
>https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/readthedocs/base.html

#### mkdocs.yml
```yml
# Pages not available to end users
- 'hidden': 'internal_endpoints.md'
```
### base.html
```yml
      <div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="main navigation">
        <ul class="current">
          {% for nav_item in nav %}
            {% if nav_item.title != "hidden" %}               <=== this is the important line
              <li>{% include "toc.html" %}<li>
            {% endif %}
          {% endfor %}
        </ul>
      </div>
```

Given that this was pretty easy to implement, and has nothing to do with the complexity of the site, I would still like to see this become part of the larger package.

**Comment by d0ugal** [comment] 2015-07-30 08:39
Neat, good to see that you found a work around for this. I would like to see this work with the Markdown metadata. For example, you might add "hidden: true" to the top of the file and then it will be excluded from the nav. I am not sure how #689 is looking to add this. @tomchristie?

**Comment by tomchristie** [comment] 2015-07-30 09:10
Rather than having to include them in the nav with 'hidden' it'd make more sense to just build all .md pages irrespective of if they're in 'pages' or not.

>  I am not sure how #689 is looking to add this

At the moment that'd build all md files, and warn if any of them are not in pages. For this behavior we'd simply want to turn that warning off.

**Comment by robodude666** [comment] 2015-07-31 16:57
@tomchristie If `pages` is being used by a project I'd rather see mkdocs warn when a page is built but not in `pages`, and then add the ability to list only the filename/globs w/o a name.

For example:

```
pages:
- 'Introduction': 'index.md'
- 'User Guide': 'user-guide.md'
- 'About': 'about.md'
- hidden_file.md
- hidden/folder/*.md
- extension/generated/apis/*.md
```

This makes it explicit that these files are intended to be hidden, as no title is given to them (title can be extracted from filename/metadata in these cases).

It'll also help catch cases where the author or contributor creates a new file but forgets to update pages. This way they'll get a warning, which they can explicitly silence by adding it to the pages list.

It also makes it possible for extensions to generate pages that will be included, though albeit extensions would _probably_ have access to modify the `pages` config...

**Comment by waylan** [comment] 2015-08-03 17:28
> This makes it explicit that these files are intended to be hidden, as no title is given to them (title can be extracted from filename/metadata in these cases).

My preference would be to always define the Title in the meta-data and never in the config. But according to the above proposal, that would make all my pages "hidden" which is not what I want. 

All "hidden" means is that the page is excluded from the nav menu. Interestingly, if no pages config is provided, all pages are auto-discovered and included in the nav menu. All the pages config gives you is a clear way to define order and nesting of the nav menu (I see the ability to define a title as a convenient side effect). It would follow quite naturally then, that any pages not listed in the pages config would then not be listed in the nav menu. As #689 gives us this already (albeit with a warning), I don't see much room for improvement.

**Comment by robodude666** [comment] 2015-08-03 18:09
> My preference would be to always define the Title in the meta-data and never in the config. 

I would agree with you, as I don't personally like my recommendation of excluding the title; it was just a simply example to illustrate explicitly hiding pages without having to add a whole bunch of new config options. If we would rather have a boolean flag in the metadata of a page, that would be fine too.

> As #689 gives us this already (albeit with a warning), I don't see much room for improvement.

The improvement I'm suggesting is to only give warnings for pages that weren't explicitly hidden. If I have 100 API docs that I'm trying to hide from the navigation I don't want to see 100 warnings when I build my docs. That will make the warnings meaningless if I'm always going to ignore them as it makes it very easy for an important warning to go unnoticed.

**Comment by waylan** [comment] 2015-08-03 19:51
>   I don't want to see 100 warnings when I build my docs.

Right, and as @tomchristie stated, those warnings should be able to be turned off. I assumed that that was clear and didn't restate it. Sounds like we are on the same page here.

**Comment by robodude666** [comment] 2015-08-04 07:10
I'm trying to point out that they should only be turned off for **specific** pages, not all. If I mark 5 pages as hidden, and create a new *.md file I should get 1 warning. If that's understood then I'm okay :smile:.

**Comment by dmehra** [comment] 2015-11-18 09:09
I found the same need to hide pages from the sidebar nav, as our docs have ~200 pages, and we don't want all of them present in the sidebar menu (if collapsible nav were available per https://github.com/mkdocs/mkdocs/issues/588, that may remove the need for hiding, or perhaps still not). 

What I ended up doing (in a custom theme override of toc.html) is this, inspired by comment https://github.com/mkdocs/mkdocs/issues/699#issuecomment-126132312 above, but replacing the word `hidden` with underscores `________` so it's easy to see in my mkdocs.yml which pages are hidden, it looks like this:
```
pages:
- Concepts:
   - 'Overview': 'concepts/overview.md'
   - '________': 'concepts/quick_ref.md'
   - '________': 'concepts/hello_world.md'
- Modules:
  - 'String': 'modules/string.md'
  - '________': 'modules/string_intro.md'
```

This is the salient part of my toc.html:
```
  {% if nav_item.title != "________" %}
    <li class="toctree-l1 {% if nav_item.active%}current{%endif%}">
        <a class="{% if nav_item.active%}current{%endif%}" href="{{ nav_item.url }}">{{ nav_item.title }}</a>
...
    </li>
  {% endif %}
{% endif %}
```

The reason I prefer this approach to using markdown metadata is that I'd rather specify what is hidden or included in the same place where I'm organizing the menu layout. If it had to be in the metadata, it would be spread across individual markdown files. That would be useful if I didn't have to list out all the pages in mkdocs.yml, but that only works if `pages` is omitted altogether, in which case I cannot control the menu layout at all (undesired for my project with lots of files and structure).

If you'd like the underscores hack upstream in readthedocs theme, I'm happy to put up a 2-line PR (plus documentation). Perhaps by now there is a better solution for what I'm doing, if so please advise. I couldn't tell what behavior would be delivered by the referenced #689.

**Comment by jberkel** [comment] 2015-11-18 12:06
@dmehra a bit more flexible approach is simply to check for a title beginning with '_': 
```
{% if not nav_item.title.startswith("_") %}
```

```yaml
pages:
- Concepts:
   - 'Overview': 'concepts/overview.md'
   - '_QuickRef': 'concepts/quick_ref.md'
```

This way you can easily enable / disable headings, and you don't need to count the number of "_" used.

**Comment by robodude666** [comment] 2015-11-19 23:03
@jberkel That's a great idea! Certainly less ambiguous than having a whole bunch of `**HIDDEN**` titles in your `pages`.

This got me thinking... What if mkdocs "borrows" from Python, and any `*.md` filenames that started with a `_` or `__` were "hidden" and not published in the toc (unless a flag is disabled in the yml config)?

This allows users who don't use `pages` and rely on mkdoc's self-discovery to maintain hidden pages, while allowing users of `pages` to specify pages without voodoo hacks.

**Comment by dmehra** [comment] 2015-11-19 23:12
I am using @jberkel `title.startswith("_")` successfully in my custom scheme right now. The _*.md filename based idea by @robodude666 is interesting, it would avoid having to maintain a long list of "____ Page Title XYZ" entries in mkdocs.yml; however to make the pages appear/disappear in the sidebar, one would have to rename the files, as opposed to editing in a single config file. I think the top-down vs bottom-up specification comes down to a personal preference, so perhaps supporting both ways (with a config flag) is worthwhile.

**Comment by shichao-an** [comment] 2016-01-14 01:40
My workaround is to hack the `nav.html` template by adding the following line somewhere in the very beginning:
```
{% set hidden_titles = ["foo", "bar"] %}
```

Then, the nav for loop is something like this: 
```
...
{% for nav_item in nav %}
  {% if nav_item.title not in hidden_titles %}
...
```

This does not affect the naming structure of your pages and you can restore the hidden pages by removing them from the `hidden_titles` anytime you want.

**Comment by slackmoehrle** [comment] 2016-01-29 19:30
+1 for the ideas. Thanks everyone. This was what I needed.

**Comment by slackmoehrle** [comment] 2016-01-29 19:59
@waylan So I have:
```
- 'Editors & Tools':
      - 'Studio': 'editors_and_tools/studio.md'
      - '________': 'editors_and_tools/Workspace_Overview/en.md'
```

and in `nav.html`:
```
<!-- Expanded navigation -->
        <div class="navbar-collapse collapse">
            {% if include_nav %}
                <!-- Main navigation -->
                <ul class="nav navbar-nav">
                {% for nav_item in nav %}

                  {% if nav_item.title != "________" %}

                      {% if nav_item.children %}
                          <li class="dropdown{% if nav_item.active %} active{% endif %}">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ nav_item.title }} <b class="caret"></b></a>
                              <ul class="dropdown-menu">
                              {% for nav_item in nav_item.children %}
                                  {% include "nav-sub.html" %}
                              {% endfor %}
                              </ul>
                          </li>
                      {% else %}
                          <li {% if nav_item.active %}class="active"{% endif %}>
                              <a href="{{ nav_item.url }}">{{ nav_item.title }}</a>
                          </li>
                      {% endif %}

                  {% endif %}
                  
                {% endfor %}
                </ul>
            {% endif %}
```
but when I deploy, I still see items with `________`

I also tried: `{% if not nav_item.title.startswith("_") %}` too

What mistake did I make?

**Comment by shichao-an** [comment] 2016-01-29 20:05
@slackmoehrle 

I think `nav_item.title` is refers to upper-level titles, e.g. 'Editors & Tools'.

 `________` is in `nav_item.children`.

You need to put the `if` inside `{% for nav_item in nav_item.children %}`

**Comment by dmehra** [comment] 2016-01-29 20:08
If I correctly remember (set up mkdocs a few months ago, works great!) nav.html is for the main page navigation. What you want to modify is `toc.html` because that controls the left pane menu. Here is mine, using `if not nav_item.title.startswith("_")`:

```
{% if nav_item.children %}
    <ul class="subnav">
    <li><span>{{ nav_item.title }}</span></li>

        {% for nav_item in nav_item.children %}
            {% include 'toc.html' %}
        {% endfor %}
    </ul>
{% else %}
  {% if not nav_item.title.startswith("_") %}
    <li class="toctree-l1 {% if nav_item.active%}current{%endif%}">
        <a class="{% if nav_item.active%}current{%endif%}" href="{{ nav_item.url }}">{{ nav_item.title }}</a>
<!-- Removed the subsection list that duplicates subsection title in most cases -->
    </li>
  {% endif %}
{% endif %}
```

**Comment by slackmoehrle** [comment] 2016-01-29 20:11
@dmehra I am trying to modify both the left hand pane and the menu navigation so that pages with "________" don't appear at all, anywhere. They are just linked to in other docs.

**Comment by slackmoehrle** [comment] 2016-01-29 20:12
@shichao-an Thank you. It works as it should. I appreciate your reply very much.

**Comment by gsouf** [comment] 2016-03-24 13:28
Instead of finding workaround, it there a plan to make it a native feature ?

**Comment by waylan** [comment] 2016-03-24 14:16
This appears to be one of the more popular feature requests and possibly something we should be working on in the short term. Unfortunately, there seems no clear direction on which way we should resolve it.  A number of proposals have been discussed with no clear "winner." Therefore, I have summarized the various options below:

1. Only pages listed in the `pages` config setting get included in the nav, while all pages in the `docs` dir get built. Thus, any pages omitted from the `pages` config are "hidden" by their exclusion.

    This was the solution proposed by @tomchristie and implemented in #689. However, #689 has now been closed at it has fallen way behind and was significantly incomplete to begin with. I believe there was some good stuff in there, but I don't think this was part of it.

    The problem with this solution is that some users have sites with hundreds of pages and they (understandably) like the current behavior where the `pages` config is auto-populated with all pages in the `docs` dir. Manually listing all of their hundreds of pages would be less than desirable. If they have even one "hidden" page, they would now need to list all of their hundreds of pages in the config just to exclude that one page.

2. Mark pages listed in the `pages` config as "hidden" in the config.

    While there are a few different proposals for how to indicate "hidden" status, this has the same problem as the previous solution. It requires all pages to be listed in the `pages` config.

    Although, one possible solution I haven't seen proposed is to add a new config setting `exclude` which takes a list of pages to "exclude" from the nav. While this helps the people with large numbers of pages in their nav, it could be a problem for people who have large numbers of pages to "exclude". It also adds another setting, which is something we generally try to avoid.

3. Mark a file as "hidden" at the file level. A few different methods have been suggested:

    a. Use a "hidden" meta data key in each file you want excluded (i.e., `hidden: true`).

    b. Use a special file naming convention to indicate the file is "hidden" (such as starting the file name with an underscore).

    This method does not change the current behavior with auto-generating the `pages` config and therefore is more usable with large projects. However, there is no single place you can go to see all "hidden" files, which may or may not be an issue for people.

    We already use the meta-data in other ways (defining the page title), so we have precedence for using that method. The downside is that you actually have to open a file to see if it is "hidden".

    Using a file-naming convention makes identifying "hidden" files easy (for humans browsing the file system), but MkDocs has not used file names for any other behavior (except, of course, file extensions), so from that perspective it feels like a departure from MkDocs norms to me.

Obviously, I'm partial to 3.a., but without a clear path, I doubt anyone will be implementing a solution (including myself). To complicate matters, with a complete Plugin API (see #206) I can see how either 3.a. or 3.b. could be implemented as a Plugin. @d0ugal do you have any direction on how someone working on a solution for this should precede?

**Comment by gsouf** [comment] 2016-03-24 14:48
Instead of choosing a solution in the core, why not providing a way to use one of them from the config? For instance we could provide a configuration option to control how the menu behaves. That could be additional to any of the 3 solutions you proposed. 

The pros:
- By default it allows to keep the current behavior
- It allows to implement new menu strategies in the future
- Depending on your project, and as your project grows, you can choose what menu strategy to use for your menu.
- You can implement and ship strategies for the menu as plugins

The cons:
- Every solution needs to be implemented and maintained

### Some Example: 

In your config you have an option named ``menuStrategy``, by default it is ``menuStrategy: onlyListedPages``, and the behaviour would be the same as the current one: only the listed files are in the menu. Perfect for BC. (in addition of that strategy, you can provide an option ``compileEvertying: true`` that would tell to compile files that are not in the menu)

Now you change the ``menuStrategy`` value to ``menuStrategy: hideUnderscoredFiles``: then all files begining with an underscore would not appear in the menu.


Of course each strategy needs an implementation, but even if only 1 solution is implemented at the begining it's a good things for the future. What do you think?

**Comment by waylan** [comment] 2016-03-24 15:37
We generally try to decrease config settings and are very cautious about adding new ones. If we were looking for the fix that allows multiple solutions, then we would punt this to a Plugin. Truth be told, most of the recent feature requests could all be handled by a  good plugin API. I wonder if the best solution would be to focus our efforts on #206 and let users create solutions of there own for all of these various features. If so, multiple of the proposals above could be implemented in tandem as third party plugins. Over time, as some of them mature, its possible that a single clear "winner" will become apparent, in which case we could consider incorporating that solution into MkDocs proper.

**Comment by robodude666** [comment] 2016-03-24 16:28
@waylan +1 to developing a plugin API. and +1 to the rest of your post.

I feel like page titles is currently the best solution to hiding pages, and no effort should be taken in adding it as a feature to the MkDocs core (at the moment).

Given how many people would want to hide pages, the title feature should be documented and included as an example of the `mkdocs-basic-theme` project to demonstrate the flexibility of custom templates.

**Comment by waylan** [comment] 2016-03-24 17:28
Oops, I missed the page title option. I've just added that as 3.c. in my summary above. Thanks for the reminder @robodude666. Although, personally I find that the most distasteful of them all. It is clever in that it could either be addressed by file name (when the title is obtained from the file name) or from meta data (when the title is obtained from meta data) or from the config (when the title is defined in the config) giving the user some added flexibility. But I don't like the idea that the page title needs to be altered. I want my page title to be *the actual title*. Remember, the page title can also be obtained from the first `h1`. So will this cause the text of my document to be altered? That's unacceptable. Although, in retrospect, maybe the problem is that there are so many ways to define a page title -- but that is another issue for another discussion.

**Comment by jasonnator** [comment] 2016-07-09 16:55
Subscribing as this is a very much a feature I want and need for my project

**Comment by davidandgoliath** [comment] 2016-09-06 20:28
Just a note, we started using  the following so that the hidden character doesn't show up in the titles. There might be an easier way — but, this works for us for now:
`{% if not nav_item.title.startswith("&nbsp;") %}`

Thanks for all the help getting this working. Thread was a good read.

**Comment by gar1t** [comment] 2016-09-15 20:40
Under what circumstances would one include a *.md file in the docs directory and not want (or expect) it to be compiled?

**Comment by slackmoehrle** [comment] 2016-09-15 20:48
of course you want it compiled. You might not want it displayed in menu's and the TOC.

**Comment by gar1t** [comment] 2016-09-15 20:54
Of course, that's the point of this issue.

The implication here is that mkdocs should just compile the files.

mkdocs bothers to issue a warning when a md file is referenced but not listed in pages. Would not that be the point to just compile it?

pages might then be renamed to toc.

**Comment by waylan** [comment] 2016-09-16 22:39
> pages might then be renamed to toc.

That would not be necessary. In fact, it would be quite confusing as we already have a toc which is something quite different. There are currently three different collections:

1. `nav`, which is the nested collection of links used to build the site navigation/menu.
2. `pages` which is a flat list of all Markdown pages rendered (in order by next/previous links).
3. `toc`, which is a nested list of the headers in a page and unique to each page.

As MkDocs works today, all rendered pages are included both in the `nav` and `pages`. This issue is about allowing a page to be included in `pages` but not in `nav` (and for completeness, #989 is about allowing links to be included in `nav` but not in `pages`).

> mkdocs bothers to issue a warning when a md file is referenced but not listed in pages. Would not that be the point to just compile it?

Not necessarily. By that point, the list of `pages` (and `nav`) had long been compiled.  The warning is issued when parsing the Markdown link and it is noted that what appears to be an internal link, links to an unknown page (no such page exists in `pages`). That is not the time to add the page. The warning is based on the assumption that you misspelled a URL or deleted a page and forgot to delete a link to it, etc. We would need to add any such pages to `pages` before we begin rendering the first page (for example, when we scan the `docs_dir` for non-Markdown files).

Another issue is the next/previous links. With no clear order, presumably such pages would not have next/previous links. Not sure that that is what is desired (and if it is, how would that order get defined?). They would just be widow pages which would need to be linked within the body of other pages. But, the templates assume that any `page` has next/previous links. And, in fact, the UI of the templates assume that all pages have next/previous links. This feature is completely outside the original goals of the project IMO. However, with the Plugin API, anyone should be able to make such a feature work in whatever way they need.

**Comment by mdd41** [comment] 2017-07-06 02:14
@waylan This seem to be a very popular request. Do we have a proposed solution?

**Comment by waylan** [comment] 2017-07-06 12:50
This is being addressed as part of a refactor to the code base I'm working on for version 1.0. However, my time is extremely limited right now so work is mostly on hold for a couple months.

**Comment by itviewer** [comment] 2017-10-17 14:36
This features is so important, please improve its priority

**Comment by AntoineMazuyer** [comment] 2017-11-15 17:38
I totally agree with the previous comment :)
You do awesome work, thanks !

**Comment by brandongc** [comment] 2018-01-04 00:23
So my issue #1369 was closed with a reference to this one. "#699 will undo anything here" 

However, after reading the thread I do not see any clear path forward decided upon (or how that is not orthogonal to the behavior my issue was about, but that is besides the point). Only a vague mention of a refactor. 

@waylan What is the intended behavior of the refactor?

**Comment by waylan** [comment] 2018-01-04 00:43
The code is currently in my private repo and incomplete at this time. The short answer is that before taking any action, MkDocs will walk the `docs_dir` and compile a list of all files. Any files in that list which are not Markdown files (based on file extension) will be copied to the `site_dir`. Any Markdown files (based on file extension) will be rendered as pages regardless of whether they are included in the `pages` config or not. The `pages` config will simply provide the user with a way to customize the site navigation. In fact, `pages` may even be renamed to `nav` to make that clear (with `pages` as an alias for at least a couple versions to provide a smooth transition). Whether the `nav` alias happens or not (haven't discussed or decided yet), the config would be auto-populated if not defined, so most users would not see any difference in behavior.

Of course, as any pages not listed in the config will still be rendered, but will not be linked to in the nav, they will be "hidden" pages and the user will need to provide their own links to such pages.

**Comment by brandongc** [comment] 2018-01-04 00:55
Thank you for the explanation. This sounds almost identical to what I would consider ideal behavior.

>Any files in that list **which are not Markdown files (based on file extension)** will be copied to the site_dir.

Can this clause be made optional (emphasis mine)? 

"Hidden" pages in this case may be *legitimate* "raw" media files I want to link to in my documentation.

**Comment by waylan** [comment] 2018-01-04 01:27
> > Any files in that list **which are not Markdown files (based on file extension)** will be copied to the site_dir.
>
> Can this clause be made optional (bold emphasis mine)?

No, that would require a new config setting (`exclude_pages`?), which we are not interested in adding. If you want to add something like that, that should be done via a Plugin. I suppose a generic "exclude pages" plugin may even make for a useful third-party plugin, although I expect a "draft" plugin would be more popular (where the meta data of a page may define a page's publish/draft status). In fact, if we were going to implement anything of the sort, I'd be inclined to do the later. However, as this time, I'm leaving both to be addressed by third party plugins. If such a plugin becomes wildly popular, then we will reconsider.

**Comment by majkinetor** [comment] 2018-01-16 14:23
This is highly needed - its typical to have pages that should be accessed only by knowing the link (for instance application help for administrators) and hidden from the navbar so that regular users can't see them for both overloading and security reasons.

**Comment by froschdesign** [comment] 2018-01-17 09:09
@majkinetor 
> …and security reasons.

If you hide something, that's no security!

**Comment by majkinetor** [comment] 2018-01-17 15:32
That depends on the context. Hidding is often enough - can u guess my secret gist link?

**Comment by majkinetor** [comment] 2018-01-17 15:33
Besides,  you can configure web server to ask for auth on specific pages/dirs. 

But you need to have files,  hence the request.

**Comment by gsouf** [comment] 2018-01-17 16:31
Not sure that's the subject of the ticket

**Comment by waylan** [comment] 2018-01-17 16:45
Ok, let's keep the conversation on topic please. As it stands, this feature is definitely going to be added and more "me too" comments will only add to the noise. As stated in a  previous comment, it is a work in progress. We are volunteers working on this in our spare time and more noise here doesn't give us more spare time.

**Closed** 2018-06-28 19:08 UTC
Labels: Enhancement

**Comment by experimentalles** [comment] 2019-07-15 08:06
# General aliases
/p /part $1+
/me /action $destination $1+
/j /join $1+
/q /query $1+
/w /whois $1+
/raw /quote $1+
/connect /server $1+
/cycle $channel? /lines /part $channel | /join $channel
/active /back $1+
/umode /mode $nick $1+

# Op related aliases
/op /quote mode $channel +o $1+
/deop /quote mode $channel -o $1+
/hop /quote mode $channel +h $1+
/dehop /quote mode $channel -h $1+
/voice /quote mode $channel +v $1+
/devoice /quote mode $channel -v $1+
/k /kick $channel $1+
/bans /mode $channel +b
/ban /quote mode $channel +b $1+
/unban /quote mode $channel -b $1+

# Misc aliases
/slap /me slaps $1 around a bit with a large trout
/tick /msg $channel ✔

**Comment by tomchristie** [comment] 2019-07-15 08:14
Bot blocked.

**Comment by ojacques** [comment] 2020-03-13 10:35
Side note, but helpful for some: [`mkdocs-awesome-pages-plugin`](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin/#hide-directory) allows to build, but hide an entire directory.

![image](https://user-images.githubusercontent.com/5385290/76613549-a8954300-651e-11ea-9bdc-157035c56457.png)

**Comment by matchavez** [comment] 2021-01-11 21:44
Can you just make it a "" in the nav?

**Comment by matchavez** [comment] 2021-01-12 20:31
Well, turns out this was updated with #1504 - all pages are now built; just leave them out of the nav structure.
