### ISSUE TITLE
Feature request for ignoring specific directories in serve mode

### ISSUE THREAD

**Issue by grbd** [mkdocs/mkdocs#1280] opened 2017-09-11 14:53 UTC
Hi,
I'd like to request a feature of being able to ignore specific directories when using the serve mode of mkdocs.

One of the ways I tend to use mkdocs is to
  * Build an initial site with mkdocs
  * Run a script which harvests the menu from the built site and puts it into a doxygen template
  * Run doxygen which then uses that template / source code to output it's html etc to the docs/doxygen directory
  * Build mkdocs again but this time to pick up the doxygen files at the same time.
  * Publish to github pages.

This all works fine, except when it comes to using the serve mode.
I have to make sure the doxygen directory is not present in some cases if there's a lot of doxygen content otherwise it just takes forever to load it all into memory.

**Comment by waylan** [comment] 2017-09-11 16:04
The server is provided as a convenience for development within the general MkDocs use-case. If you are doing non-standard things, my suggestion would be to use your own server which meets your specific needs. There is no way we could anticipate every single use-case out there, and in order to avoid feature creep, I'm inclined to not add a new feature every time someone encounters a need for some new non-standard behavior.

What is not clear to me, is if there is some general use-case that we could support which would also meet your specific needs. I'll leave this open for now to discuss it, but without any good proposals/arguments it will likely be closed in the future.

**Comment by waylan** [comment] 2017-09-11 17:20
So I just re-read the original request and this jumped out to me.

> I have to make sure the doxygen directory is not present in some cases if there's a lot of doxygen content otherwise it just takes forever to load it all into memory.

The problem is likely not related to serving the files, but that the `serve` command starts with a "build". I expect the "build" is where the delays are happening. In fact, `serve` does not scan through all the files. It simply listens for requests and when it receives one, it checks the file system and responds based on the file system's response. However, the "build" does need to scan through all the files, coping non-Markdown files and converting all Markdown files. Therefore, it's not the `serve` command which needs to ignore anything, but the `build` command.

At this time, there is no mechanism for including non-MkDocs content in a build (aside from blindly copying it to the `site_dir`). However, there are a few existing proposals (#1223, #989, #1134). which I expect might make for a reasonable solution.

**Comment by grbd** [comment] 2017-09-11 22:51
I timed it and serve is taking longer than build, it might be because the doxygen content is just .html files instead of markdown. (I have a combination of pages I write in markdown and doxygen content generated from the sources of the project).

  * As a starting point I have about 128Mb of data (3,877 Files, 1 Folder)
    sitting in source directory of docs/doxygen, this basically just .html and .png files (mostly .html)
  * running build copies this across to site/doxygen along with everything else in about 10 seconds
  * running serve results in waiting for around 50 seconds before the page will load

With the above project it's kind of useable, but with projects of larger source code where there's a lot more doxygen content. It can take a long time before serve becomes responsive.
As a workaround I'm just removing docs/doxygen before running serve as part of a wrapper script for now

**Comment by waylan** [comment] 2017-09-11 23:08
Our server is just a light wrapper around [lepture/python-livereload][1]. I wonder if the live reload stuff is slowing things down. After all, it is watching all 3,877 of your files for changes. Have you tried the `--no-livereload` option. That option uses an even lighter wrapper around the Tornado flat-file server.

[1]: https://github.com/lepture/python-livereload

**Comment by grbd** [comment] 2017-09-12 08:15
yep that seems to be it, disabling --no-livereload narrows it down to 10 seconds
I might see if I can create my own wrapper around lepture/python-livereload

**Closed** 2017-10-31 17:10 UTC
