### ISSUE TITLE
navigation with a lots of items has not possibility to scroll down

### ISSUE THREAD

**Issue by somenxavier** [mkdocs/mkdocs#1947] opened 2019-12-26 21:59 UTC
I have this items in my subdirectory `activitats`:
```
ls zync/candoc4/docs/activitats/
95-propostes-per-treballar-estadistica-i-probabilitat
activitats.atom.xml
activitats.atom.xml.erb
activitats.md
activitats.md.html
cau-una-xinxeta
cervesa-consumida
cervesa-consumida.md
cervesa-consumida.md.html
construim-marcs-i-mirem-que-valen
construim-marcs-i-mirem-que-valen.md
construim-marcs-i-mirem-que-valen.md.html
educacion-digital-a-distancia
egg-roulette
egg-roulette.md
egg-roulette.md.html
el-cercle-dels-centims
el-cercle-dels-centims.md
el-cercle-dels-centims.md.html
el-diposit-de-aigua
el-diposit-de-aigua.md
el-diposit-de-aigua.md.html
el-punt-de-llibre
el-punt-de-llibre.md
el-punt-de-llibre.md.html
el-tunel-major
el-tunel-major.md
el-tunel-major.md.html
fitxes-anton-aubanell
funcions-rectes.md
funcions-rectes.md.context.pdf
hipsometre
idees
la-capsa-de-cereals
la-capsa-de-cereals.md
la-capsa-de-cereals.md.html
la-graduacio
la-graduacio.md
la-graduacio.md.html
la-linia-temporal-del-curs
la-linia-temporal-del-curs.md
la-linia-temporal-del-curs.md.html
la-pausa-musical
la-pausa-musical.md
la-pausa-musical.md.html
la-piscina-de-cola
la-piscina-de-cola.md
la-piscina-de-cola.md.html
marques-pneumatiques
marques-pneumatiques.md
marques-pneumatiques.md.html
materials-per-eso-maria-del-mar-rigo
modelitzacio-exponencial.md
modelitzacio-exponencial.md.context.pdf
pay-it-forward
pay-it-forward.md
pay-it-forward.md.html
phone-home
phone-home.md
phone-home.md.html
plou
plou.ca.md
plou.ca.md.html
plou.en.md
plou.en.md.html
probabilitat-de-encistellar-paper
probabilitat-de-encistellar-paper.md
probabilitat-de-encistellar-paper.md.html
proves-pisa
que-costaria-el-segon-marc
que-costaria-el-segon-marc.md
que-costaria-el-segon-marc.md.html
trobar-mesures-figures-vnps
trobar-mesures-figures-vnps.md
trobar-mesures-figures-vnps.md.html
```

but mkdocs does not display an scroll down in submenu (see attachment)
![Captura de pantalla_2019-12-26_22-58-12](https://user-images.githubusercontent.com/89915/71491822-5d2e9b00-2833-11ea-9686-2e7a90d64d6e.png)

Please put a right bar for scroll down

**Comment by waylan** [comment] 2019-12-27 00:24
This is a duplicate of #1234.

**Closed by waylan** 2019-12-27 00:24 UTC
