### ISSUE TITLE
Display h3 and h4 on sidebars menu

### ISSUE THREAD

**Issue by JeremieGuez** [mkdocs/mkdocs#1270] opened 2017-08-30 15:21 UTC
Hi,

I would like to know if it's possible to extend depth of sidebar. I would like a sidebar menu iso to my toc but on the sidebar i can only have #h1 and #h2

Below a screenshot:
<img width="827" alt="capture d ecran 2017-08-30 a 17 20 15" src="https://user-images.githubusercontent.com/15033641/29880232-8a7676d8-8da7-11e7-9d59-505ecca1f3b6.png">

On my sidebar, when I click on 1 Prerequisites I do not have a rolling menu.

Is it possible to do it ?

**Comment by waylan** [comment] 2017-08-30 15:37
I'm closing this as a duplicate of #544. You have already commented on that issue and an answer has been provided.

While this is a support question rather than a feature request (as we find in #544), support questions should be asked on the [mailing list][1]. GitHub Issues is for bug reports and feature requests.

[1]: https://groups.google.com/forum/#!forum/mkdocs

**Closed by waylan** 2017-08-30 15:37 UTC
