### ISSUE TITLE
Possible to use liquid tags on .md file?

### ISSUE THREAD

**Issue by dimative** [mkdocs/mkdocs#1635] opened 2018-09-24 07:31 UTC
Hello. I want to use liquid tags to in my .md files. 

{% capture example %}
{% for color in config.theme.bs-colors %}
<span class="badge badge-{{ color.name }}">{{ color.name | capitalize }}</span>
{% endfor %}
{% endcapture %}

like this. Is it possible?

**Comment by waylan** [comment] 2018-09-24 12:55
This is a duplicate of #304, and is not likely to be implemented outside of a plugin.

**Closed by waylan** 2018-09-24 12:55 UTC
