### ISSUE TITLE
Possibility to use different file.md for the homepage

### ISSUE THREAD

**Issue by leokun** [mkdocs/mkdocs#896] opened 2016-04-14 12:45 UTC
Hi there,

I was wondering if there is any option to change the index.md by any other defined *.md  as homepage ?
I wanted to use Mkdocs with GitLab which start there wiki by home.md and not index.md.

I didn't find anything in the configuration page about that, also, is there a way to rename one page and still use the automatic md detection ?

Thanks a lot for your help.

Regards.
Léo

**Comment by waylan** [comment] 2016-04-14 13:49
I was about to suggest this is a duplicate of #608. However, in that case, the Markdown source file may use a different name (`README.md`), but the HTML file output by MkDocs would still be `index.html`. As I understand it, this is asking for the output file to retain its original name (`homepage.md => homepage.html` as opposed to `homepage.md => index.html`). Therefore, this would be an additional add-on to that feature.

**Comment by leokun** [comment] 2016-04-15 12:26
Hi, and thanks a lot for your answer.

I think it could be a duplicate of #608 as I would like to be able to define which file is the first parsed file.

I have suscribe to both issues, if you need close this one :)

Best regards.

**Comment by d0ugal** [comment] 2016-04-23 16:55
> I was about to suggest this is a duplicate of #608. However, in that case, the Markdown source file may use a different name (`README.md`), but the HTML file output by MkDocs would still be `index.html`. As I understand it, this is asking for the output file to retain its original name (`homepage.md => homepage.html` as opposed to `homepage.md => index.html`). Therefore, this would be an additional add-on to that feature.

It is possible to not have an index and have a `home.md` file only I think. I've not tried this for a while. Of course this means there is no index.html page so I'm not sure when that would be desirable.

So, I'd say this is either invalid (it's already possible to have a `home.md` -> `home.html`) or a dupe of #608 (as that would require `home.md` -> `index.html`). I'll close this, feel free to correct me and I can reopen it.

**Closed by d0ugal** 2016-04-23 16:55 UTC
Labels: Needs design decision
