### ISSUE TITLE
Trouble with readthedocs theme and 0.11.1

### ISSUE THREAD

**Issue by Regner** [mkdocs/mkdocs#349] opened 2015-02-17 17:06 UTC
Hey guys,

I have a few issues with the readthedocs theme and my documentation. Not sure if it's something I am doing wrong or if it's something wrong with MkDocs. Happy to be corrected if it's me.

You can view the readthedocs hosted version here: http://eveonline-third-party-documentation.readthedocs.org/en/latest/

Source is here: https://github.com/Regner/eveonline-third-party-documentation

The first issue is the home link is not showing up on the left sidebar navigation menu. I have it listed in the mkdocs.yml as `- ['index.md', 'Home']` but it doesn't show up. I am trying to get it to show up like it does on your docs here: http://mkdocs.readthedocs.org/en/latest/

The second maybe related maybe not related issue is that I cannot get all the navigation links to expand correctly. If you take the Image Server Test link, last one in the list from my example, it does not expand to show the headings when selected.

Any and all help is greatly appreciated and thanks for your awesome work on this project. :)

**Comment by d0ugal** [comment] 2015-02-17 17:16
i was able to reproduce this locally. Not sure what the cause is yet tho'

**Comment by burdiyan** [comment] 2015-02-18 10:46
I believe home page is never listed because "House" icon in the sidebar header serves as link to the homepage. I'm not sure if it should be like this.

**Comment by Regner** [comment] 2015-02-18 10:54
If you look at the MkDocs hosted on readthedocs, http://mkdocs.readthedocs.org/en/latest/, they have the Home link on the sidebar.

**Comment by rkday** [comment] 2015-03-07 09:38
Is this not fixed by https://github.com/tomchristie/mkdocs/commit/bfdab5fafa834de6288bf058b95010b3982bbb65 and https://github.com/tomchristie/mkdocs/commit/f98f73c46f40643b3510394d3c7eb3ac28e7e730 (both post-0.11.1 commits)?

**Comment by d0ugal** [comment] 2015-03-07 19:24
@Regner I've no idea when that MkDocs documentation was built and what version it was built with.

I do think this was a recent regression however, so probably my fault. I can't pin down where it happened tho'

**Comment by d0ugal** [comment] 2015-04-02 20:31
I've retested with the latest master, as @rkday said, this has been fixed.

**Closed by d0ugal** 2015-04-02 20:31 UTC
Labels: Bug

**Comment by Regner** [comment] 2015-04-02 23:29
Awesome! Thanks guys, I look forward to this release. :)

**Comment by d0ugal** [comment] 2015-04-02 23:36
It should land soon. Keep an eye on milestone 0.12.0 for the remaining tasks.
