### ISSUE TITLE
Escaping * character

### ISSUE THREAD

**Issue by armaldio** [mkdocs/mkdocs#830] opened 2016-02-19 14:19 UTC
Hello,

I'm trying to render C code like this one : 

```c
...
t_tekgui		*gui;

   gui = tekgui_load("full.ini");
...
```

But all what is after the * is not right interpreted.
And escaping the * not work (it render like this \*)
Can you help me ?
Thank you

**Comment by waylan** [comment] 2016-02-19 14:25
You should be putting your code in a code block. Indent the entire block by at least four spaces. If you are, can you provide both the source Markdown and the HTML output?

**Comment by d0ugal** [comment] 2016-02-22 09:31
I'll close this for now as it seems we have a solution in the previous comment - but happy to reopen if you can give us a

**Comment by armaldio** [comment] 2016-02-22 09:58
Here are the files, I tried the solution and it doesn't work with my code.
[files.zip](https://github.com/mkdocs/mkdocs/files/140373/files.zip)

**Comment by d0ugal** [comment] 2016-02-22 10:22
It looks fine to me, I don't really understand what the problem is. You should either use ``` OR indent the code four spaces, not both. It looks like the highlighting works best if I explicitly tell it to highlight as C code with the following approach (this shouldn't be indented at all):

    ```c
    // code
    ```

It would be useful if you included which version of MkDocs you are using and which theme you are using.

**Comment by armaldio** [comment] 2016-02-22 10:34
It render like this, threre are eird colors between stars.

![screenshot](https://cloud.githubusercontent.com/assets/3089715/13215770/2064928e-d958-11e5-9a0b-21a28907c42b.png)

**Comment by d0ugal** [comment] 2016-02-22 10:43
Can you show me your mkdocs.yml? Which MkDocs version are you using? `mkdocs --version`

**Comment by armaldio** [comment] 2016-02-22 11:17
mkdocs, version 0.15.2

```
site_name: Tekgui
theme: slate
pages:
- 'index.md'
- 'doc-fr.md'
- 'doc-en.md'
- 'fonction-fr.md'
- 'function-en.md'
- 'exemple-ini.md'
- 'basic-c-program.md'
```

Thank you.

**Comment by waylan** [comment] 2016-02-22 14:41
So this appears to be a problem with the syntax highlighter, not the Markdown parser. 

@armaldio do you perhaps have some custom CSS of your own? If so, it may be conflicting with the CSS for the syntax highlighter. Or maybe it is the "slate" theme. Does the problem persist with a different theme?

**Comment by armaldio** [comment] 2016-02-22 14:51
Yes the problem persist

**Comment by d0ugal** [comment] 2016-03-01 09:48
This method works well. I have verified it works on Slate and readthedocs and mkdocs themes. I would use that. https://gist.githubusercontent.com/d0ugal/6e0acfea12a94d07e443/raw/0ac4e6191d9a88c435b951b8e2ce17e1980ec29b/example.md

**Closed by d0ugal** 2016-03-01 09:48 UTC
Labels: Needs information
