### ISSUE TITLE
Clicking an image returns the user to the top of the page

### ISSUE THREAD

**Issue by chang-brian** [mkdocs/mkdocs#1506] opened 2018-06-11 19:45 UTC
For example, click this image (1/4 of the way down this article):
https://docs.branch.io/pages/deep-linking/universal-links/#add-your-branch-link-domains

You will notice that you are returned to the top of the page. This is really annoying if you are trying to read an article from beginning to end!

I noticed that `#dialog-image` overrides the other anchors:
https://docs.branch.io/pages/deep-linking/universal-links/#dialog-image?src=../../../img/pages/deep-linking/universal-links/subdomain-setting.png

Is there any way to get rid of this behavior and let the user stay on the correct anchor?

**Comment by waylan** [comment] 2018-06-12 00:02
That does not appear to be either one of the two themes included with MkDocs. I would suggest reporting this to the developers of the theme you are using.

**Comment by waylan** [comment] 2018-06-20 00:29
As I cannot reproduce the reported problem and it appears to be related to a third party theme, I am closing this.

**Closed by waylan** 2018-06-20 00:29 UTC
