### ISSUE TITLE
index.md in subfolders to be the default link in a nested navigation

### ISSUE THREAD

**Issue by emmaindal** [mkdocs/mkdocs#2217] opened 2020-10-26 08:26 UTC
I have a nav structure like this in my mkdocs.yml

```
nav:
   - non nested nav item: test.md
   - nested nav item: 
          - test: subfolder/test.md
          - test2: subfolder/test2.md
```

In my `subfolder` I have a `index.md` file. I want that page to be the default link for the "nested nav item" but instead that nav item is not clickable, but rather just responsible for expanding the nested sub nav. And I can not make the "nested nav item" a link since that will be invalid YAML.

Would like to hear thoughts, ideas, solutions to my problem here. Thanks!

**Comment by waylan** [comment] 2020-10-28 14:03
This is a duplicate of #73 and many other issues. Note that an attempt was made to modify the builtin themes to support this in #1042 but it was rejected for the reasons stated there (in short, the UI doesn't work with the existing themes). However, it could certainly be adopted by a third party theme. The basics of how to make it work are described [here](https://stackoverflow.com/questions/54596774/how-to-add-permalinks-to-tree-nodes-in-markdown-nav-file-mkdocs-yml/54598748#54598748).

As no modification to MkDocs are necessary for this to work, I'm closing this.

**Closed by waylan** 2020-10-28 14:03 UTC
