### ISSUE TITLE
How to set a different language for the document?

### ISSUE THREAD

**Issue by enricobasso** [mkdocs/mkdocs#1829] opened 2019-07-17 00:48 UTC
I'd like to set `<html lang='it>` but I didn't find any reference in the documentation.

**Comment by waylan** [comment] 2019-07-17 01:26
This feature is not yet implemented. The beginnings can be found in #1778. I'm closing this as a duplicate of #211.

That said, you may find a third party theme which has some support for languages other than English. You can find a list of themes in the [wiki](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes).

**Closed by waylan** 2019-07-17 01:26 UTC

**Comment by jorgeponto** [comment] 2020-01-14 01:11
What I need in MkDocs is not i18n of the theme. This, with the main.html and blocks I managed. What I need is something "more simple". Because I'm doing a website in Portuguese, I need to change the html lang="en" to html lang="pt-PT" (inform all technologies that my text page is in Portuguese. If not, for example, the blind people, who used screenreaders, will read my portuguese text with an English Synthesizer by default or read portuguese braille with the english braille code . :(
