### ISSUE TITLE
Subheadings auto-nesting in table of contents

### ISSUE THREAD

**Issue by ryanfox** [mkdocs/mkdocs#1466] opened 2018-04-10 03:24 UTC
Hello, does mkdocs support auto-indenting nested subheadings in a document, like is shown in the table of contents here?
http://documentation-style-guide-sphinx.readthedocs.io/en/latest/style-guide.html#whitespaces

Expanding/collapsing isn't necessary, but would be a nice touch as well. Ideally there's a configuration option for it I'm not seeing, but a custom theme would be workable too.

**Comment by waylan** [comment] 2018-04-10 14:09
I assume you are speaking about the readthedocs theme? If so, then this is likely a duplicate of #588. We would love to have this working but no one seems to be interested in working on it. Of course, PRs are always welcome.

**Closed as completed** 2018-04-10 14:23 UTC
