### ISSUE TITLE
Bad path for Mahtjax CDN.

### ISSUE THREAD

**Issue by AndreWin** [mkdocs/mkdocs#1339] opened 2017-11-06 14:16 UTC
Hello!

Mkdocs 0.17.1 on Windows 8.1

mkdocs.yml:

```
site_name: My Docs

dev_addr: 0.0.0.0:8000

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
```

Try to run `serve`:

```
$ mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory

Bad path: https:\\cdnjs.cloudflare.com\ajax\libs\mathjax\2.7.2\mathjax.js?config=tex-mml-am_chtml
```

I have no ideas why so. It's only on Windows, not on Ubuntu.

Best regrads,
Andrey.

**Comment by waylan** [comment] 2017-11-06 14:26
This is a duplicate of #1336. The fix will be available in the next release (0.17.2).

**Closed by waylan** 2017-11-06 14:26 UTC

**Comment by vsimko** [comment] 2017-11-09 09:05
A workaround for those who need the CDN functionality until 0.17.2 is released:

### In `mkdocs.yml`:
```yml
extra_javascript:
  - extra.js
```

### In `extra.js`:
```js
const urls = [
  'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML',
  'https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js',
  'https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js',
  'https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js',
  'https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js',
]

const bodyEl = document.querySelector('body')
for(url of urls) {
  const s = document.createElement('script')
  s.src = url
  bodyEl.appendChild(s)
}
```

**Comment by AndreWin** [comment] 2017-11-09 09:09
I have been just found [this fix](https://github.com/mkdocs/mkdocs/pull/1337/commits/636dedbeef414bf04ce11fcb8d79ff2149c01a77) and have been corrected code in `mkdocs/config/config_options.py` manually.

Best regards,
Andrey.
