### ISSUE TITLE
Unicode Literals Warning

### ISSUE THREAD

**Issue by bitHero** [mkdocs/mkdocs#795] opened 2016-01-13 20:18 UTC
Sorry if there's a solution to this but I couldn't find one anywhere. When I run any mkdocs command I get a unicode warning from python, everything works fine though.

```
$ mkdocs --version
/Library/Python/2.7/site-packages/mkdocs/cli.py:86: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/Library/Python/2.7/site-packages/mkdocs/cli.py:100: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/Library/Python/2.7/site-packages/mkdocs/cli.py:125: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/Library/Python/2.7/site-packages/mkdocs/cli.py:145: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/Library/Python/2.7/site-packages/mkdocs/cli.py:176: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/Library/Python/2.7/site-packages/mkdocs/cli.py:194: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
mkdocs, version 0.14.0
```

It might be something to do with my python version too,

```
$ python --version
Python 2.7.10
```

It's worth note I also see the warning on Travis CI when it builds.

**Comment by waylan** [comment] 2016-01-13 20:37
This is another duplicate of #703. Ignore the warning. It will be removed in the next release.

**Closed** 2016-01-13 20:41 UTC

**Comment by bitHero** [comment] 2016-01-13 20:50
Thank you!
