### ISSUE TITLE
Autodiscovery not picking up markdown headings in site nav

### ISSUE THREAD

**Issue by spjwebster** [mkdocs/mkdocs#1469] opened 2018-04-16 19:13 UTC
Using the autodiscovery feature, real page headings (from the L1 headings in the Markdown for that page) in the nav only appear to be populated as pages are generated. The impact of this is that pages that were generated *after* the page you're looking at have a title derived from their filename, whilst the current page and any pages generated before this page have their extracted title.

I've created a super-simple example repo [here](https://github.com/spjwebster/mkdocs-headings), including the built site.

The generated navigation content for each page is linked below:

* https://github.com/spjwebster/mkdocs-headings/blob/master/site/index.html#L55-L61
* https://github.com/spjwebster/mkdocs-headings/blob/master/site/sub/index.html#L55-L61
* https://github.com/spjwebster/mkdocs-headings/blob/master/site/sub/second/index.html#L55-L61

I've had a quick glance through the mkdocs source and it seems as though autodiscovery *should* work normally, so I'm unsure if this is an issue with me using/configuring mkdocs incorrectly, is a known limitation or is a regression.

**Comment by waylan** [comment] 2018-04-16 21:34
This is a duplicate of #1347.

**Closed by waylan** 2018-04-16 21:34 UTC

**Comment by spjwebster** [comment] 2018-04-17 07:13
Thanks for the pointer. I trawled the existing issues but obviously overlooked #1347.
