### ISSUE TITLE
Grab page title from the corresponding source file

### ISSUE THREAD

**Issue by polwel** [mkdocs/mkdocs#808] opened 2016-01-27 11:58 UTC
Currently the page title is specified in the configuration file:
``` yaml
pages:
    - 'Introduction': 'index.md'
```
It would be useful if it instead it would be grabbed from the corresponding MD file, e.g. in a line as
```
title: Introduction
```
or 
```
% Introduction
```
I feel that this is where logically that information belongs to (it is content, not config). Also, building different versions (e.g. languages) from the same config file does otherwise not allow the titles to be translated.

I could not find a feature that does this.

Thanks!

**Comment by d0ugal** [comment] 2016-01-27 13:10
Duplicate of #316

**Closed by d0ugal** 2016-01-27 13:10 UTC
