### ISSUE TITLE
Can I specify the navigation but tell mkdocs to build every page as usual?

### ISSUE THREAD

**Issue by fmartingr** [mkdocs/mkdocs#1093] opened 2016-11-15 11:38 UTC
I have this hierarchy (more or less):
```
- index.md
- api/v1.md
- api/v2/index.md
- api/v2/... More stuff of the api2
- apps.md
- apps/app1.md
- apps/app2.md (and so on)
```

But I want the main menu to show: `Home | API | Apps` (API with a dropdown and the rest to the index files) but since the `pages` configuration specify which pages are built (not the navigation only) all the links I have on my docs are broken cause the rest of the mds are not built.

Is there any way to do this? I've found nothing on the issues and the docs and I don't think my use case is that weird, maybe I missed something.

**Comment by waylan** [comment] 2016-11-15 13:51
This is a duplicate of #699, which has a long discussion and multiple proposals for how to address this. No decision has been made yet.

**Closed** 2017-01-20 14:39 UTC
