### ISSUE TITLE
Favicon in default path doesn't update. 

### ISSUE THREAD

**Issue by ReeceTaylor512** [mkdocs/mkdocs#3866] opened 2024-11-17 23:40 UTC
I put a custom favicon in the path specified on the [changing the favicon icon](https://www.mkdocs.org/getting-started/#changing-the-favicon-icon) section of the docs. I saw some people had the same issue when using Material but I'm not using it. When googling I found [#1671](https://github.com/mkdocs/mkdocs/issues/1671). Not sure if something similar is happening here. 
.
└── 🗁 my-project/
    ├── 🗁 docs/
    │   ├── 🗁 img/
    │   │   └── 🗎 favicon.ico
    │   └── 🗎 index.md
    └── 🗎 mkdocs.yml

**Comment by pawamoy** [comment] 2024-11-18 11:57
> doesn't update

You mean when serving locally, or once deployed?

**Comment by pawamoy** [comment] 2024-11-18 13:25
I tried for myself and the favicon was properly updated while serving locally, so I cannot reproduce the issue you describe. I'll close the issue while waiting for you to provide a minimal reproducible example. If the favicon is not updating on your deployed site, make sure to force-refresh the page in your browser, and maybe just wait a bit (some servers will cache assets for longer than others).

**Closed by pawamoy** 2024-11-18 13:25 UTC

**Comment by ReeceTaylor512** [comment] 2024-11-18 22:09
When serving locally. I haven't deployed this unless using `mkdocs build` counts as deploying it but I wouldn't have thought so. Interestingly though when using `mkdocs build` the updated icon does show up in the files.

If I then open up index.html from the generated "site" folder then the favicon _is_ updated

![image](https://github.com/user-attachments/assets/8c2f5e39-bcda-40f1-82d4-68e8d8a9c019)

![image](https://github.com/user-attachments/assets/4775efc7-c95f-468e-bd71-7aab9bd0fc2a)

![image](https://github.com/user-attachments/assets/767ea7a0-13d9-4a18-8411-3a3b6aa556e5)

However when just using the local host version it doesn't use the updated version

![image](https://github.com/user-attachments/assets/db79f1a6-e4af-4720-b285-dfcf94106790)
