### ISSUE TITLE
How to support multiple languages?

### ISSUE THREAD

**Issue by Jinxiansen** [mkdocs/mkdocs#2063] opened 2020-04-14 10:46 UTC
Hello, how to support multiple languages? 🤔  I may have multiple menu configurations, so multiple `mkdocs.yml` files will be generated, but I do n’t know how to read the corresponding `mkdocs.yml` configuration file according to the selected language.

I searched for previous issues, but I didn't find a very effective solution, so I ask for help here.

> English is not my native language; please excuse typing errors.

**Comment by waylan** [comment] 2020-04-16 12:32
Multiple languages is complicated. The best approach is to create a separate site for each language as documented in the 'warning' for the [search plugin][1].

For more information, please see #211, #617 & #774. Between those three issues you will find all of the information that we have about using multiple languages. I am closing this as a duplicate of those issues.

[1]: https://www.mkdocs.org/user-guide/configuration/#search

**Closed by waylan** 2020-04-16 12:32 UTC
