### ISSUE TITLE
Feature Request: Support Unicode Letters in Header Links

### ISSUE THREAD

**Issue by USSX-Hares** [mkdocs/mkdocs#2190] opened 2020-09-17 14:49 UTC
Hi.

I'd like to ask the ability to use Cyrillic (Russian) letters (and probably other Unicode symbols) in the ref-links generation.
Example site: https://hares.gitlab.io/old-world-rpg/magic/spells-tier-1/#_1

Instead of transforming `"Вывести из строя"` to `"вывести-из-строя"` and generating appropriate ref-link, it generates ref #_13.

**Comment by USSX-Hares** [comment] 2020-09-17 15:24
Investigated. This is caused by the Markdown library.
Will continue to try finding the workaround

**Comment by waylan** [comment] 2020-10-28 13:17
This appears to be a duplicate of #212, Note the workaround in [this comment][1] (yes, you can point to your own slugify function from the YAML config file).

[1]: https://github.com/mkdocs/mkdocs/issues/212#issuecomment-115404162

**Closed by waylan** 2020-10-28 13:17 UTC
