### ISSUE TITLE
Link to a standalone html file in the menu

### ISSUE THREAD

**Issue by jdumas** [mkdocs/mkdocs#1441] opened 2018-03-24 16:38 UTC
Hi,

Let's suppose I have a standalone html file in my docs folder `docs/foo.html`. In the menu of my website I would like to have it listed correctly:

```yaml
pages:
  - Home: index.md
  - Foo: foo.html
```

While `foo.html` is correctly copied by mkdocs when building, it generates an incorrect link in the menu, i.e. it will point to `baseurl/foo/` instead of `baseurl/foo.html`. It seems related to #192 and #989, but it's not exactly the same issue.

Is there any reason that mkdocs does not detect that the file ends in .html and generates a different menu entry for this? (And also removes it from the prev/next navigation).

I couldn't figure out how to make it work, any tip would be appreciated.

**Comment by waylan** [comment] 2018-03-24 20:37
This is being closed as a duplicate of #989. I realize the title specifically refers to "external" links, but in [this comment][0] the problem is summarized for both external and internal links. Regardless, the fix will be the same for both. This is being addressed as part of the [Pages Refactor][1]. See [this comment][2] for an overview.

[0]: https://github.com/mkdocs/mkdocs/issues/989#issuecomment-274112420
[1]: https://github.com/mkdocs/mkdocs/projects/2
[2]: https://github.com/mkdocs/mkdocs/issues/699#issuecomment-355168759

**Closed by waylan** 2018-03-24 20:37 UTC

**Comment by jdumas** [comment] 2018-03-24 20:48
Ok my bad. I only skimmed the thread and wasn't sure if it was the same problem or not. Glad to see it's in your radar.
