### ISSUE TITLE
Python TypeError when deploying to GitHub Pages

### ISSUE THREAD

**Issue by TheBerkin** [mkdocs/mkdocs#1041] opened 2016-08-28 04:59 UTC
Windows 10, MkDocs 0.15.3, Python 3.5.2

After the initial deployment, which is successful, attempting to run `mkdocs gh-deploy --clean` again produces the following error message when attempting to push to GitHub:

```
E:\repos\rantdocs>mkdocs gh-deploy --clean
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: E:\repos\rantdocs\site
INFO    -  Copying 'E:\repos\rantdocs\site' to 'gh-pages' branch and pushing to GitHub.
Traceback (most recent call last):
  File "c:\users\nicholas\appdata\local\programs\python\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\nicholas\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Nicholas\AppData\Local\Programs\Python\Python35\Scripts\mkdocs.exe\__main__.py", line 9, in <module>
  File "c:\users\nicholas\appdata\local\programs\python\python35\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\nicholas\appdata\local\programs\python\python35\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\users\nicholas\appdata\local\programs\python\python35\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\nicholas\appdata\local\programs\python\python35\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\nicholas\appdata\local\programs\python\python35\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\users\nicholas\appdata\local\programs\python\python35\lib\site-packages\mkdocs\__main__.py", line 189, in gh_deploy_command
    gh_deploy.gh_deploy(config, message=message)
  File "c:\users\nicholas\appdata\local\programs\python\python35\lib\site-packages\mkdocs\commands\gh_deploy.py", line 69, in gh_deploy
    remote_branch)
  File "c:\users\nicholas\appdata\local\programs\python\python35\lib\site-packages\mkdocs\utils\ghp_import.py", line 163, in ghp_import
    if not try_rebase(remote, branch):
  File "c:\users\nicholas\appdata\local\programs\python\python35\lib\site-packages\mkdocs\utils\ghp_import.py", line 78, in try_rebase
    if sp.call(cmd) != 0:
  File "c:\users\nicholas\appdata\local\programs\python\python35\lib\subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\nicholas\appdata\local\programs\python\python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "c:\users\nicholas\appdata\local\programs\python\python35\lib\subprocess.py", line 1198, in _execute_child
    args = list2cmdline(args)
  File "c:\users\nicholas\appdata\local\programs\python\python35\lib\subprocess.py", line 751, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'
```

I have tried re-cloning my repository, even creating a completely new repository, but the same error occurs when I try the command after the first deploy.

**Comment by waylan** [comment] 2016-08-29 02:33
This is a duplicate of #722. The fix will be available in the next release (0.16), which should be available soon.

**Closed by waylan** 2016-08-29 02:33 UTC
