### ISSUE TITLE
syntax for deploying to specific folder?

### ISSUE THREAD

**Issue by pdimens** [mkdocs/mkdocs#1877] opened 2019-10-07 20:04 UTC
I read over the docs and didn't see anything that seemed to address this, so I apologize in advance if this question is addressed in the docs. 

In the way that Julia `Documenter.jl` deploys docs to a gh-pages repo and puts every deployed doc into a new folder relative to the version number, is there a manual command for `gh-deploy` to deploy to a folder so I can have a set of `stable` docs and another of `lastest` docs? Or perhaps a configuration line in `mkdocs.yml` to achieve this?

**Comment by waylan** [comment] 2019-10-08 00:46
This is a duplicate of #193. Check the comments for links to multiple third-party tools which implement the feature.

**Closed by waylan** 2019-10-08 00:46 UTC
