### ISSUE TITLE
HTML images not included in non-index markdown files

### ISSUE THREAD

**Issue by samrreynolds4** [mkdocs/mkdocs#1664] opened 2018-10-22 15:05 UTC
Hello,

I have a couple markdown files that I include in the mkdocs.yml file by using the pages option:
```
pages:
  - page1.md
  - page2.md
```

I include images in these markdown files using the html syntax:
```
<img src="img/image1.png">
```

when I do mkdocs build in the docs folder, I keep getting erros about image1.png not existing in the site/ directory.

It works when I just put all the content in the index.md, but I get this error when I try to break the content up into multiple files.  
  
the only reference to this kind of issue was posted in 2014 #138 
Is this issue already known or is there something I'm missing?

mkdocs version: 1.0.4  
python: 3.6

**Comment by waylan** [comment] 2018-10-22 16:00
The problem is that you are using raw HTML. As the [docs][1] explain:

> Markdown allows document authors to fall back to raw HTML when the Markdown syntax does not meets the author's needs. MkDocs does not limit Markdown in this regard. However, as all raw HTML is ignored by the Markdown parser, MkDocs is not able to validate or convert links contained in raw HTML. When including internal links within raw HTML, you will need to manually format the link appropriately for the rendered document.

See the docs for [Linking to images and media][2] for the appropriate method.

Note that the cause of this is the [use_directory_urls][3] configuration option. When `True` (the default), page URLs are rewritten which would cause relative links to other files to break; except that MkDocs is aware of this and rewrites all internal links to match, avoiding broken links between files. However, as explained above, that only happens for Markdown links within a page, not raw HTML links. If you really want to use raw HTML links, then you have two options:

1. Set `use_directory_urls` to `False` which ensures that URLs are not altered and relative URLs in the source pages match relative URLs in the built site. Of course, all your pages' URLs will now end in `.html`, which some people find undesirable.
2. Manually alter the links so they are relative to the built page, not the source page. Of course, this will break things when browsing the source on GitHub, etc. And it requires that document authors intimately understand how MkDocs manipulates URLs, so it is not recommended.

As this is not a bug, but a failure to follow the documentation, I'm closing this.

[1]: http://www.mkdocs.org/user-guide/writing-your-docs/#linking-from-raw-html
[2]: http://www.mkdocs.org/user-guide/writing-your-docs/#linking-to-images-and-media
[3]: http://www.mkdocs.org/user-guide/configuration/#use_directory_urls

**Closed by waylan** 2018-10-22 16:00 UTC
