### ISSUE TITLE
If docs_dir and site_dir are named similar things validation can fail

### ISSUE THREAD

**Issue by chalbersma** [mkdocs/mkdocs#1126] opened 2017-01-19 18:01 UTC
Using version 0.15.3 installed from repo on Ubuntu. 

Having a project like:
./mkdocs.yaml
./docs_source
./docs

And a config that specified `docs_dir: docs_source` and `site_dir: docs` throws a validation error. 

```
mkdocs.config.base.ValidationError: The 'docs_dir' should not be within the 'site_dir' as this can mean the source files are overwritten by the output or it will be deleted if --clean is passed to mkdocs build.(site_dir: '/home/chalbersma/Documents/src/git-work/chalbersma/Linux-VPN-Script/docs', docs_dir: '/home/chalbersma/Documents/src/git-work/chalbersma/Linux-VPN-Script/docs_source')
```

Changing docs_source to source_docs works. I assume it's doing some sort of matching on the validation that's being fooled if docs_* and docs are the names of the files.

**Comment by waylan** [comment] 2017-01-19 18:29
This is a duplicate of #1011 which was fixed in 536f8b4 and released as part of version 0.16. If you upgrade, the problem will be resolved.

**Closed by waylan** 2017-01-19 18:29 UTC
