### ISSUE TITLE
collapse headings in TOC by default

### ISSUE THREAD

**Issue by mehulkar** [mkdocs/mkdocs#1085] opened 2016-10-25 01:39 UTC
Hello! I'm using the `readthedocs` theme and had a question.

If I have this in my `mkdocs.yml`:

```yml
pages:
  Home: index.md
  Second Page: second.md
```

The TOC on the left shows "Home" and "Second Page" as top level nav items, but all headers inside both pages are auto expanded. How do I get those to be collapsed by default? (I'm seeing lots of examples of ReadTheDocs that have headers collapsed, but not sure how to configure it. 

Should use extra css for this or are there are other options exposed?

**Comment by waylan** [comment] 2016-10-25 01:46
The `readthedocs` theme for MkDocs is a clone of the default Sphinx theme used by the Read The Docs service. Over time, they have added features that we don't have. This is the subject of #588.

If you are able to get some CSS and/or JavaScript working which mimics the upstream theme's behavior, feel free to submit a pull request.

I'm closing this as a duplicate of #588.

**Closed by waylan** 2016-10-25 01:46 UTC

**Comment by mehulkar** [comment] 2016-10-25 01:52
Got it, thanks for the quick reply! I should have looked more closely in issues before making a new one.
