### ISSUE TITLE
Document that all internal URLs must be relative

### ISSUE THREAD

**Issue by zxcware** [mkdocs/mkdocs#1172] opened 2017-03-17 19:12 UTC
In a site, referring an image with an absolute url, for example, `/img/the-image.png`, doesn't work. The site interprets it into `http://gobblin.readthedocs.io/img/the-img.png` but expects `http://gobblin.readthedocs.io/en/latest/img/the-img.png`. Why is there the part `/en/latest` injected into the url? I searched through the documentation but didn't find any related configuration. 

Semantically, that absolute url should work. The root of the site should be  `http://gobblin.readthedocs.io/en/latest/` instead of `http://gobblin.readthedocs.io/` in this case.

Any thought?

**Comment by waylan** [comment] 2017-03-17 20:04
All internal URLs must be relative not absolute. Issue #192 addresses whether we should allow absolute URLs. This could be a duplicate of that; however, I checked the [documentation][1] and noticed that while all of the examples use relative URLs, we don't explicitly state that they must be relative. Therefore, I will leave this open to remind us to clarify the documentation regardless of what decision is made in #192.

[1]: http://www.mkdocs.org/user-guide/writing-your-docs/#images-and-media

**Closed** 2018-01-23 21:29 UTC
Labels: Documentation
