### ISSUE TITLE
Auto-detection of titles in the nav bar is inconsistent

### ISSUE THREAD

**Issue by alexwlchan** [mkdocs/mkdocs#1354] opened 2017-11-23 17:05 UTC
Suppose I have a series of pages on my site whose titles don’t match their filenames. For example, with the following repro:

```console
$ mkdocs new .
INFO    -  Writing config file: ./mkdocs.yml
INFO    -  Writing initial docs: ./docs/index.md
$ echo '# cats' > docs/1.md
$ echo '# dogs' > docs/2.md
$ echo '# parrots' > docs/3.md
```

### Expected behaviour

I’ll have three links in the navbar: "cats", "dogs" and "parrots".

### Actual behaviour

Each page shows a different set of navbar links, apparently depending on where they fall in the navbar:

![screen shot 2017-11-23 at 17 03 45](https://user-images.githubusercontent.com/301220/33183589-583505ca-d070-11e7-9ac3-ad93d04a9409.png)

![screen shot 2017-11-23 at 17 03 50](https://user-images.githubusercontent.com/301220/33183591-5aa3551e-d070-11e7-885a-95d8751d4975.png)

![screen shot 2017-11-23 at 17 03 53](https://user-images.githubusercontent.com/301220/33183595-5cacdf7e-d070-11e7-9800-ac273b8a5245.png)

![screen shot 2017-11-23 at 17 03 55](https://user-images.githubusercontent.com/301220/33183598-5e90f956-d070-11e7-8f7d-dc16af922afb.png)

It’s very inconsistent and confusing!

### Versions

```console
$ pip freeze
click==6.7
Jinja2==2.10
livereload==2.5.1
Markdown==2.6.9
MarkupSafe==1.0
mkdocs==0.17.2
PyYAML==3.12
six==1.11.0
tornado==4.5.2

$ python --version
Python 3.6.1
```

**Comment by alexwlchan** [comment] 2017-11-23 17:07
The same error persists if I define the title in the front matter:

```yml
---
title: dogs
---
```

**Comment by waylan** [comment] 2017-11-23 21:20
This is a duplicate of #1347.

**Closed by waylan** 2017-11-23 21:20 UTC
