### ISSUE TITLE
unbuilt .md files not included in site_dir

### ISSUE THREAD

**Issue by brandongc** [mkdocs/mkdocs#1369] opened 2018-01-03 20:48 UTC
I have a project where in some cases I have source code (including files such as README.md) which I want to be included as raw files in the deployed output (`site_dir`). This works fine for non `.md` files. 

e.g. README.txt is included in the output as expected, but the README.md file is not.

I don't care if README.md gets rendered or not (I understand hidden pages are a separate issue), but it would be good for consistency if it was at least copied to the output `site_dir`.

project structure
```
├── docs
│   ├── README.md
│   ├── README.txt
│   └── index.md
├── mkdocs.yml
```

docs/index.md
```markdown
# Hi
* [A](./README.md)
* [B](./README.txt)
```

```shell
> mkdocs build
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /tmp/mkdocs-issue/site
WARNING -  The page "index.md" contained a hyperlink to "README.md" which is not listed in the "pages" configuration.
```

output:
```
site/
├── 404.html
├── README.txt
├── css
│   ├── base.css
│   ├── bootstrap-custom.min.css
│   ├── font-awesome-4.5.0.css
│   └── highlight.css
├── fonts
│   ├── fontawesome-webfont.eot
│   ├── fontawesome-webfont.svg
│   ├── fontawesome-webfont.ttf
│   ├── fontawesome-webfont.woff
│   ├── fontawesome-webfont.woff2
│   ├── glyphicons-halflings-regular.eot
│   ├── glyphicons-halflings-regular.svg
│   ├── glyphicons-halflings-regular.ttf
│   ├── glyphicons-halflings-regular.woff
│   └── glyphicons-halflings-regular.woff2
├── img
│   ├── favicon.ico
│   └── grid.png
├── index.html
├── js
│   ├── base.js
│   ├── bootstrap-3.0.3.min.js
│   ├── highlight.pack.js
│   └── jquery-1.10.2.min.js
├── search
│   ├── lunr.min.js
│   ├── mustache.min.js
│   ├── require.js
│   ├── search-results-template.mustache
│   ├── search.js
│   ├── search_index.json
│   └── text.js
└── sitemap.xml
```

**Comment by waylan** [comment] 2018-01-03 21:26
> I don't care if README.md gets rendered or not (I understand hidden pages are a separate issue), but it would be good for consistency if it was at least copied to the output `site_dir`.

I was going to close this as a duplicate of #699 until I read the above. So this is about copying files to the `site_dir which are not "pages". Even if/when #699 gets implemented, "pages" will be Markdown files. Markdown files are any file with a Markdown specific file extension (a list of various common extensions are supported). If you want a file to not be seen as a "page", then don't give it a Markdown file extension. What's wrong with `README` (or `README.txt`) as a file name? I don't think there is any other reasonable way to determine which files to include/exclude from the list of copied files.

**Comment by waylan** [comment] 2018-01-03 21:29
In case it is not clear from my previous comment, the current 'copying' code assumes that any file with a Markdown extension is a "page" and skips it. It makes no reference to the config settings or anything else except the filenames themselves. I see no reason to change that behavior.

**Comment by brandongc** [comment] 2018-01-03 21:55
So it assumes it is a page even if it is *not* included in a pages config?

That assumption makes sense if the *.md files are not explicitly specified, but in the case of a specified pages config copying non-specified files seems like a clean enough choice to me.

An implementation might be to add an argument to `copy_media_files(exclude_list=[])`

`if not is_markdown_file(filename) or not filename in exclude_list`

instead of

`if not is_markdown_file(filename)`

So it can be called at `build()` as 

```
utils.copy_media_files(config['docs_dir'], config['site_dir'], exclude_list=config['pages'], dirty=dirty)
```

I think I can do this completely in a plugin `post_build` event, but then I will need to reimplement `copy_media_files()` with some slight differences. In which case the the above modification to copy_media_files will still be useful (would such a PR be accepted?)

**Comment by brandongc** [comment] 2018-01-03 21:59
The main issue I have with renaming files in this scenario is that I may be mirroring a src directory from github which contains a README.md. Then I have a consistency problem if I am renaming files (manually or automatically).

**Comment by waylan** [comment] 2018-01-03 23:57
I've given this some more thought and it doesn't make sense to act on this as implementing #699 will undo anything we could do here. Hidden pages will be any "pages" (Markdown files) not included in the `pages` config.  As #699 is slated for the next release, an interim fix for this issue would never make it to a release.

If you don't want a file to be considered as a page (hidden or not) then you must not give it a Markdown file extension. That is the only solution I anticipate MkDocs ever officially supporting. Of course, a plugin is free to alter that behavior, but that should already be possible.

**Closed by waylan** 2018-01-03 23:57 UTC
Labels: Needs design decision
