### ISSUE TITLE
Multi repo docs

### ISSUE THREAD

**Issue by adibrastegarnia** [mkdocs/mkdocs#1846] opened 2019-08-17 05:22 UTC
Hi 
I have a question about multirepo docs. Does Mkdocs support multi repo docs? If yes how? Suppose we have multiple repos and each repo has its own docs folder but we would like to present them in one documentation site.

**Comment by waylan** [comment] 2019-08-17 21:23
This sort of thing would need to be done via a third party plugin. I suppose as a shortcut, you could use symbolic links to bring all files into one "project," but I suspect that is not what you want.

**Comment by adibrastegarnia** [comment] 2019-08-17 21:30
Thanks for your response. Do you know any third party plugin that can do that?

**Comment by waylan** [comment] 2019-08-18 16:57
All of the third party plugins I'm aware of are listed on the [wiki][1].

See also #575 which included another possible way to address this. In fact, I'm closing this as a duplicate of that issue.

[1]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins

**Closed by waylan** 2019-08-18 16:57 UTC

**Comment by jdoiro3** [comment] 2021-12-20 15:44
@adibrastegarnia, I just started [mkdocs-multirepo-plugin](https://github.com/jdoiro3/mkdocs-multirepo-plugin), adding this feature. It's still in the early stages (started it this past weekend).

@waylan, please let me know if there are any glaring issues with this plugin or any other comments.
