### ISSUE TITLE
Add command to detect broken links

### ISSUE THREAD

**Issue by jonbeller** [mkdocs/mkdocs#2051] opened 2020-04-06 22:24 UTC
The feature for detecting broken links when you do `mkdocs serve` is great. 

I'd like to have a command like `mkdocs lint` that just prints broken links and then exits with a non-zero code if there are any. I'd run that on PRs to my docs repo to prevent links from breaking.

**Comment by waylan** [comment] 2020-04-06 23:16
Sounds like you are asking for a `--dry-run` option on `build` (run a build without writing to disc). Of course, you can also use the existing `--strict` option to ensure a non-zero code. I'm closing this as a duplicate of #1386.

**Closed by waylan** 2020-04-06 23:16 UTC

**Comment by ssbarnea** [comment] 2023-02-08 08:45
To be honest this bug should have not being closed because the linked one does not mention anything about broken-links. Dry-run has almost nothing to do with ability to detect broken links.

**Comment by j3mdamas** [comment] 2023-09-14 13:49
Yes, I agree with @ssbarnea. It would be good to have a functionality that checks broken links, at least at build time (maybe it would be harder for serve mode to be constantly checking the links).

**Comment by pawamoy** [comment] 2023-09-14 15:10
Are you referring to internal links, or external ones? Internal links are already checked at build time, see https://www.mkdocs.org/user-guide/configuration/#validation. To check external links, there are third-party tools one could use, such as https://github.com/linkchecker/linkchecker (serve and crawl), https://github.com/scivision/linkchecker-markdown, and probably others.

**Comment by ssbarnea** [comment] 2023-11-20 13:49
@pawamoy links are NOT checked at runtime for redirects, there is no way to detect redirects. In reality a redirect should trigger a warning because it means that content was moved, still working but some time in the future it might stop working. Without a way to detect redirects, we are unable to spot the issue and fix it beforce it becomes a breaking issue.

**Comment by pawamoy** [comment] 2023-11-20 15:17
There was no mention of redirects in the previous comments, thanks for clarifying.

**Comment by ssbarnea** [comment] 2024-03-26 08:16
For those interested, I am using linkchecker on few projects but I run into some problems when I need to ADD some documentation pages, basically I need to bypass linkchecker results for them due false positives. See https://github.com/linkchecker/linkchecker/discussions/811

Other than this, it does a decent job. IMHO, checking the built result is better than the markdown source because theme can add its own links, not all broken urls are visible in the source files.

**Comment by noeldum** [comment] 2024-09-30 10:36
a link checker is definitely missing in mkdocs.
