### ISSUE TITLE
Unable to use markdown reference links when text contains monospaced string

### ISSUE THREAD

**Issue by petemounce** [mkdocs/mkdocs#2920] opened 2022-08-09 11:16 UTC
I have some content that looks like

```markdown
- Which tickets _would have_ prevented a support interrupt?

    [`is:issue is:open label:type/question label:origin/customer`]

[`is:issue is:open label:type/question label:origin/customer`]: https://github.com/redacted/redacted/issues?q=is%3Aissue+is%3Aopen+label%3Atype%2Fquestion+label%3Aorigin%2Fcustomer
```

When I `mkdocs serve` the link is not rendered (I expect the text to be turned into a monospace-formatted hyperlink aimed at the github issues search link).

If I remove the backticks from inside the `[]` for anchor and reference, the link is rendered (but without the monospace that I want it to have).

This happens in both the `mkdocs` and `material` themes.

This does what I expect
* if I use an inline link like

    ```markdown
    [`is:issue is:open label:type/question label:origin/customer`](https://github.com/redacted/redacted/issues?q=is%3Aissue+is%3Aopen+label%3Atype%2Fquestion+label%3Aorigin%2Fcustomer)
    ```
 
    ... but I want to use reference-style links to aid markdown eyeball-reading and in some cases reduce duplication
* inside github's markdown renderer (which I appreciate is a completely different renderer!)

## Environment

* Windows 10 Pro
* powershell to run `mkdocs serve`
* mkdocs `1.3.1` via `pip`

    ```txt
    λ  pip install mkdocs
    Requirement already satisfied: mkdocs in c:\python310\lib\site-packages (1.3.1)
    Requirement already satisfied: Markdown<3.4,>=3.2.1 in c:\python310\lib\site-packages (from mkdocs) (3.3.7)
    Requirement already satisfied: ghp-import>=1.0 in c:\python310\lib\site-packages (from mkdocs) (2.1.0)
    Requirement already satisfied: packaging>=20.5 in c:\python310\lib\site-packages (from mkdocs) (21.3)
    Requirement already satisfied: watchdog>=2.0 in c:\python310\lib\site-packages (from mkdocs) (2.1.9)
    Requirement already satisfied: click>=3.3 in c:\python310\lib\site-packages (from mkdocs) (8.1.3)
    Requirement already satisfied: pyyaml-env-tag>=0.1 in c:\python310\lib\site-packages (from mkdocs) (0.1)
    Requirement already satisfied: importlib-metadata>=4.3 in c:\python310\lib\site-packages (from mkdocs) (4.12.0)
    Requirement already satisfied: mergedeep>=1.3.4 in c:\python310\lib\site-packages (from mkdocs) (1.3.4)
    Requirement already satisfied: PyYAML>=3.10 in c:\python310\lib\site-packages (from mkdocs) (5.4.1)
    Requirement already satisfied: Jinja2>=2.10.2 in c:\python310\lib\site-packages (from mkdocs) (3.1.1)
    Requirement already satisfied: colorama in c:\python310\lib\site-packages (from click>=3.3->mkdocs) (0.4.4)
    Requirement already satisfied: python-dateutil>=2.8.1 in c:\python310\lib\site-packages (from ghp-import>=1.0->mkdocs) (2.8.2)
    Requirement already satisfied: zipp>=0.5 in c:\python310\lib\site-packages (from importlib-metadata>=4.3->mkdocs) (3.8.1)
    Requirement already satisfied: MarkupSafe>=2.0 in c:\python310\lib\site-packages (from Jinja2>=2.10.2->mkdocs) (2.1.1)
    Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\python310\lib\site-packages (from packaging>=20.5->mkdocs) (3.0.7)
    Requirement already satisfied: six>=1.5 in c:\python310\lib\site-packages (from python-dateutil>=2.8.1->ghp-import>=1.0->mkdocs) (1.16.0)
    ```

* python `3.10`

**Comment by oprypin** [comment] 2022-08-10 18:37
I confirm that this happens. But, the issue is entirely under control of https://github.com/Python-Markdown/markdown, cant solve it here.

```pycon
>>> import markdown
>>> print(markdown.markdown("""[foo]\n\n[foo]: http://example.org/"""))
<p><a href="http://example.org/">foo</a></p>
>>> print(markdown.markdown("""[`foo`]\n\n[`foo`]: http://example.org/"""))
<p>[<code>foo</code>]</p>
```

**Comment by petemounce** [comment] 2022-08-20 09:01
There's an open issue https://github.com/Python-Markdown/markdown/issues/495 where fixes are welcome but it isn't something the maintainer needs personally.

**Comment by oprypin** [comment] 2022-08-20 09:06
Duplicate of #2676

**Closed by oprypin** 2022-08-20 09:06 UTC

**Comment by masterpink0** [comment] 2023-12-08 19:53
>>> import markdown
>>> print(markdown.markdown("""[foo]\n\n[foo]: http://example.org/"""))
<p><a href="http://example.org/">foo</a></p>
>>> print(markdown.markdown("""[`foo`]\n\n[`foo`]: http://example.org/"""))
<p>[<code>foo</code>]</p>
