### ISSUE TITLE
ReadTheDocs theme does not support collapsible navigation

### ISSUE THREAD

**Issue by naushadjamil** [mkdocs/mkdocs#1079] opened 2016-10-20 23:57 UTC
I read through the entire thread as of 10/20/2016 4:50PM PST. I need to have collapsible navigation because our doc tree is very deep. Readthedocs theme that comes with 0.15 mkdocs shows everything expanded. Somebody here took an attempt to do the collapsible thing and I tried it. It seems to have several issues. One major is that when expanding one item it expands many others.

I surely like the sphinx_rtd_theme with the +/- and the behavior also seems perfect. Unfortunately that theme cannot be used with MkDocs without porting.

Can somebody tell me if there is any theme that supports this collapse/expand feature in a decent functional way? If not is there a guideline to port the sphinx theme to MkDocs?

Finally - it isn't I have to use MkDocs so could somebody refer to any other markdown based static site generator which would offer a theme that supports collapsible navigation?

Thank you very much.

**Comment by waylan** [comment] 2016-10-21 00:21
The list of all known MkDocs themes are in the [wiki](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes). I haven't used any of those myself and the list is relatively short, so you should be able to check yourself.

Finally, I'm closing this as a duplicate of #588. Recent changes to the Sphinx theme used by Read the Docs have not yet been included in the MkDocs clone. Presumably this is one such feature.

**Closed by waylan** 2016-10-21 00:21 UTC
