### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by sagnikbanerjee15** [mkdocs/mkdocs#1219] opened 2017-05-05 01:40 UTC
Hello,

I am writing a documentation for a software and I can't seem to coalesce multiple options on the left side to one single heading. What I am trying to do is have multiple sections and have subsections under each section. When I am in one of the subsections then all the other sections should remain collapsed and not expanded. I can't seem to achieve that with readthedocs theme. Please help.

Thank you.

**Comment by waylan** [comment] 2017-05-05 03:05
I'm not 100% sure I understand what behavior you are trying to achieve, but if the desired behavior exists in the upstream (Sphinx) theme this is a clone of, then this is a duplicate of #588. If the behavior does not exist upstream, then we won't be adding it here.

**Comment by wagenaartje** [comment] 2017-06-01 12:23
Do you mean something like [this](https://wagenaartje.github.io/neataptic/) mkdocs website? 'docs` and 'articles' both have their own subsections, which are only shown when on the appropiate page. I did this with a workaround though...

**Comment by waylan** [comment] 2017-06-01 13:13
@wagenaartje cool use of theme customization. If that is the sort of thing the OP is looking for, then its something they can implement through their own theme customization. However, given the lack of feedback/clarification, I'm closing this with the assumption that it is a duplicate of #588. We can reopen if we get clarification and it turns out to be a something else.

**Closed by waylan** 2017-06-01 13:13 UTC
