### ISSUE TITLE
readthedocs - table formatting under 1.1

### ISSUE THREAD

**Issue by keiranmraine** [mkdocs/mkdocs#2028] opened 2020-03-20 16:29 UTC
The formatting under 1.1 has changed quite dramatically for the `readthedocs` option.  Is this intentional?

Table from 1.0.4:

![Screen Shot 2020-03-20 at 16 23 04](https://user-images.githubusercontent.com/3740323/77184234-6ee8ad00-6ac7-11ea-852e-536fa3309e79.png)

Table from 1.1:

![Screen Shot 2020-03-20 at 16 23 15](https://user-images.githubusercontent.com/3740323/77184258-760fbb00-6ac7-11ea-814f-2a23b344857b.png)

My `mkdocs.yml` (variables expanded in bash script):

```yml
site_name: CI reports - $CI_PROJECT_PATH
repo_url: $CI_PROJECT_URL
repo_name: GitLab
edit_uri: null
site_description: CI reports for $CI_PROJECT_PATH
theme:
     name: readthedocs
nav:
$NAV
```

**Comment by waylan** [comment] 2020-03-20 20:07
What is the behavior of the upstream Sphinx theme?

If the new behavior match upstream, then this is an intentional change. The MkDocs theme should not include anything which is not supported upstream. However, if this is a regression from the upstream Sphinx theme we may need to add some additional rules to `theme_extra.css`. A PR is welcome.

**Comment by keiranmraine** [comment] 2020-03-23 09:11
The sphinx theme stable demo shows the tables to have the clean formatting (as desired):

https://sphinx-rtd-theme.readthedocs.io/en/stable/demo/lists_tables.html#option-lists

**Comment by waylan** [comment] 2020-03-24 18:43
Thanks for the link. Sure enough we have a problem with table formatting. The way this works is that we provide the upstream CSS in [theme.css][1]. That file comes directly from upstream without modification. We then have a few fixes specific to MkDocs in [theme_extra.css][2]. However, the few rules in `theme_extra.css` have not changed between versions 1.04 and 1.1. What has changed is that `theme.css` was updated to a more current version from upstream. Doing a little spelunking with the inspector, it appears that all style rules for tables in `theme.css` are applied to `.rst-content table.docutils` whereas previously they simply used `.rst-content table`. Of course, Markdown does not assign a `docutils` class to tables so the rules are being ignored.

Presumably, a fix for this would be to copy all relevant rules from `theme.css` to `theme_extra.css` and alter them to be applied to `.rst-content table`. Under no circumstances should we edit `theme.css` directly. A PR is always welcome.

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/readthedocs/css/theme.css
[2]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/readthedocs/css/theme_extra.css

**Comment by waylan** [comment] 2020-03-24 18:45
As an aside, the inconsistency in the code spans depicted in the screenshots above was addressed in #2029. This would be a similar type of fix.

**Comment by mattbrictson** [comment] 2020-03-27 02:35
>  Doing a little spelunking with the inspector, it appears that all style rules for tables in theme.css are applied to .rst-content table.docutils whereas previously they simply used .rst-content table. Of course, Markdown does not assign a docutils class to tables so the rules are being ignored.

I don't think this is an issue with the CSS changing. The upstream table CSS has required the `docutils` class for quite some time. The problem is that mkdocs used to use JS to apply the `docutils` class to tables (see #257) but that was clobbered when the JS file was entirely deleted in https://github.com/mkdocs/mkdocs/commit/873b970f7f62ab22d05f347157d64e383164c15f#diff-be6164876d7aedfd5a20eab74b55c16d.

Was the removal of `theme.js` intentional? If so, could we bring back just the part of it that ensures table styles work? I.e.

```js
$('table').addClass('docutils');
```

**Comment by mattbrictson** [comment] 2020-03-27 15:17
I fixed this for my own site by adding the following:

```yaml
extra_javascript:
  - js/extra.js
```

```js
// js/extra.js

document.addEventListener("DOMContentLoaded", function() {
  document.querySelectorAll("table").forEach(function(table) {
    table.classList.add("docutils");
  });
});
```

**Comment by waylan** [comment] 2020-03-27 15:46
> Was the removal of `theme.js` intentional? 

Technically it wasn't removed. rather it was replaced with the upstream JavaScript. However, looking at it now, it appears that the previous version included both some of the upstream code and some hacks to make it work with MkDocs. Perhaps we need to bring parts of the old hacks back. If course, that should happen in a separate file. The upstream file should remain unmodified from upstream.

**Comment by rockandska** [comment] 2020-04-07 18:26
Hi

Table decoration is not the only thing who has changed, text surrounded by single quote too 

In 1.0.4
![image](https://user-images.githubusercontent.com/24546770/78705645-152d1300-790e-11ea-9c79-aa01c01906bc.png)


In 1.1.0
![image](https://user-images.githubusercontent.com/24546770/78705569-f6c71780-790d-11ea-9a97-2a45f79217eb.png)

Regards

**Comment by wodny** [comment] 2020-04-07 18:33
@rockandska As already mentioned, see #2029.

**Closed** 2021-04-08 00:22 UTC
Labels: Bug, Theme-readthedocs
